### ISSUE TITLE
[Azure] case sensitive in az aks install-connector command

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#1]
When deploying the connector you can only use lower case names. This is probably a k8 issue but it's documented here for now. 

ria@Azure:~$ az aks install-connector -g connectorDemo -n cluster --connector-name aciconnectorRia
Merged "cluster" as current context in /tmp/tmpxlp3utzn
Deploying the aci-connector using Helm
Error: release aciconnectorRia failed: Secret "aciconnectorRia-aci-connector" is invalid: metadata.name: Invalid value: "aciconnectorRia-aci-connector": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by yolo3301** [comment]
Why this issue belongs here?

**Comment by robbiezhang** [comment]
k8s only allows lowercase alphanumeric and dashes '-' in the name. In the latest `az aks install-connector` command, we add validator to enforce it. The command will fail and print an error:

> --connector-name must consist of lower case alphanumeric characters or dashes (-), and must start and end with an alphanumeric character.
