### ISSUE TITLE
[Azure] upgrade connector in az cli

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#100]
Add an --upgrade flag for the azure cli to upgrade the VK to the latest version 

---

### Environment summary

Provider (e.g. Azure, Hyper)

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal)

Install Method (e.g. Helm Chart, )

**Comment by robbiezhang** [comment]
@yolo3301 will take a step to implement this.

**Comment by yolo3301** [comment]
https://github.com/Azure/azure-cli/pull/5668

**Comment by yolo3301** [comment]
PR merged

**Comment by rbitia** [comment]
closing issue thanks Chen!
