### ISSUE TITLE
[Azure] query for dns name in az cli aks namespace 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#101]
make  the query for the dns namespace more obvious through the az aks namespace

**Comment by bnookala** [comment]
The current way to do this is using `az container show`, and querying the output. Example, for a pod named `helloworld`:

`az container show -g myResourceGroup -n default-helloworld --query ipAddress.fqdn`

If a pod is deployed to the kubernetes namespace default, the user would have to be aware of this and prepend `default-` to the name of the running pod, and query the output for the bound fqdn. 

@rbitia Do you think this subcommand should this be a part of the `az aks` namespace? From a quick glance at the available subcommands, they all appear to relate to management of the cluster itself (ie `create`, `browse`, `delete`, `upgrade`, `scale`, etc.) as opposed to the workloads/pods running on the cluster themselves.

**Comment by rbitia** [comment]
Closing because I have never actually need this :)
