### ISSUE TITLE
az aks install-connector fails

### ISSUE THREAD

**Issue by shahiddev** [virtual-kubelet/virtual-kubelet#103]
---

### Environment summary

Provider (e.g. Azure, Hyper): Azure

Version (e.g. 0.1, 0.2-beta): 0.1

K8s Master Info (e.g. AKS, ACS, Bare Metal): AKS (1.8.7)

Install Method (e.g. Helm Chart, ): AZ cli (running on Windows)

### Issue Details
Trying to install the ACI connector on Windows using AZ cli, fails with error:
**Error: failed to download "https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/virtual-kubelet-0.1.0.tgz"**
The relevant path is correct and tarball is available
### Repo Steps
Create AKS cluster (1.8.7) 
Install helm (2.8.0)
Run AZ command:
az aks install-connector -n clustername -g resourcegroupname --connector-name aci

Output:
_Merged "clustername" as current context in C:\Users\username\AppData\Local\Temp\tmpl_4au5m7
Deploying the ACI connector for 'Linux' using Helm
Error: failed to download "https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/virtual-kubelet-0.1.0.tgz"_

---------------
Could this be related to the GH change in TLS (https://github.com/blog/2507-weak-cryptographic-standards-removed)

**Comment by robbiezhang** [comment]
It's more like the helm is not initialized properly. Did you run `helm init` and `helm repo update`

**Comment by shahiddev** [comment]
I had initialised helm but not updated the repo but that doesn't work still failing with same error

**Comment by robbiezhang** [comment]
It's more like an issue in helm for Windows.
Can you check #3?

```
Assuming you are on windows navigate to & make sure these files exist.
“C:\Users<user>.helm\repository\local\index.yaml”
"C:\Users<user>.helm\repository\cache\local-index.yaml"

If the second file "C:\Users<user>.helm\repository\cache\local-index.yaml" doesn't exist copy the contents from the index.yaml file & make a new one with the added content.
```

**Comment by rbitia** [comment]
https://github.com/kubernetes/helm/issues/2456 linking the Helm issue to track in VK

**Comment by shahiddev** [comment]
@robbiezhang I was using Helm 2.8.0

**Comment by robbiezhang** [comment]
The helm issue is mentioned in #3. Can you check the following files?

```
Assuming you are on windows navigate to & make sure these files exist.
“C:\Users\<user>\.helm\repository\local\index.yaml”
"C:\Users\<user>\.helm\repository\cache\local-index.yaml"
If the second file "C:\Users<user>.helm\repository\cache\local-index.yaml" doesn't exist copy the contents from the index.yaml file & make a new one with the added content.
```

**Comment by shahiddev** [comment]
The second file was missing, creating that as per your instructions sorted it.

Thank you, its installed now.

I'll close this issue and will take a look at the helm issue you mentioned to see if I can help out.

**Comment by PatrickLang** [comment]
Seems to be working for me too. I didn't need any workaround.

az aks install-connector --resource-group plang-aks0309rg  --name plang-aks0309  --connector-name vkwin1
 --location eastus --os-type Windows
Merged "plang-aks0309" as current context in C:\Users\plang\AppData\Local\Temp\tmps1tn48fz
Deploying the ACI connector for 'Windows' using Helm
NAME:   vkwin1-windows
LAST DEPLOYED: Fri Mar  9 16:25:26 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                                    TYPE    DATA  AGE
vkwin1-windows-virtual-kubelet-for-aks  Opaque  3     0s

==> v1beta1/Deployment
NAME                                    DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
vkwin1-windows-virtual-kubelet-for-aks  1        1        1           0          0s

==> v1/Pod(related)
NAME                                                     READY  STATUS             RESTARTS  AGE
vkwin1-windows-virtual-kubelet-for-aks-5487b7784d-n86hj  0/1    ContainerCreating  0         0s


NOTES:
The virtual kubelet is getting deployed on your cluster.

To verify that virtual kubelet has started, run:

  kubectl --namespace=default get pods -l "app=vkwin1-windows-virtual-kubelet-for-aks"
