### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [virtual-kubelet/virtual-kubelet#1044]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by nate-double-u** [comment]
Hi, this is something I can help with, but it looks like only CNCF folks are administrators on your Netlify team.

We should add at least one maintainer to this team, is there anyone for whom that would be an appropriate role? (any volunteers?)

**Comment by helayoty** [comment]
Hey, yes I can volunteer.

**Comment by nate-double-u** [comment]
@cpuguy83, @helayoty, I'm happy to invite. Please let me know which email address to use (either here, or in the CNCF slack)

**Comment by helayoty** [comment]
hebaelayoty@gmail.com

**Comment by nate-double-u** [comment]
invite sent!

**Comment by nate-double-u** [comment]
A friendly reminder that this needs to be updated. virtual-kublet.io builds will now fail if the image isn't updated.

**Comment by helayoty** [comment]
The image has been updated.
