### ISSUE TITLE
Support more capacity limit settings and providerID in mock provider

### ISSUE THREAD

**Issue by JackieLan** [virtual-kubelet/virtual-kubelet#1086]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate) mock

Version (e.g. 0.1, 0.2-beta) latest

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, ) POD manifest

### Issue Details
Currently, when I use the default mock provider, only CPU, memory and PODS limit settings are allowed in provider-config file. By the way, providerID is also omitted in mock provider.
It is common to require providerID in node spec and have extra node capacities such as hugepages-1Gi, hugepages-2Mi, SRIOV device resources so that we can schedule a POD to simulate a DPDK application with hugepage and SRIOV device requirements.

It is expected to extend mock provider abilities to support extra capacity setting and providerID using the following configuration file:
```
    {
      "vkubelet-mock-0": {
        "cpu": "18",
        "memory": "80Gi",
        "others": {
          "hugepages-1Gi": "24Gi",
          "hugepages-2Mi": "1024Mi",
          "intel.com/sriov-igb-uio": "3",
          "intel.com/sriov-vfio-pci": "4"
        },
        "providerID": "mock://4218ae82-4789-afeb-b767-19948fd69eb3"
      }
    }
```
A sample code implementation can be found at https://github.com/JackieLan/virtual-kubelet/commit/403c456f36ffb03ef6576dbe0a6006a02407a281. Please help review whether it is OK to adopt this patch to support it.

### Repo Steps
```
git clone https://github.com/virtual-kubelet/virtual-kubelet
cd virtual-kubelet
```
Then:
```
make skaffold
```

**Comment by pires** [comment]
Thank you very much for your contribution. However, since the mock provider is simply used for automated testing, I wonder what is the value added here. @helayoty @cpuguy83 I'm fine merging #1087 even if it's just for community building purposes.

**Comment by JackieLan** [comment]
Thank you. @pires @helayoty
