### ISSUE TITLE
Can't install Virtual Kubelet with Helm charts repo on specified URL

### ISSUE THREAD

**Issue by KirillPushkarev** [virtual-kubelet/virtual-kubelet#1094]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
mock

Version (e.g. 0.1, 0.2-beta)
master

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
Minikube with Docker provider

Install Method (e.g. Helm Chart, )
Helm Chart (https://virtual-kubelet.io/docs/usage/#helm)

### Issue Details
$ helm repo add virtual-kubelet https://raw.githubusercontent.com/virtual-kubelet/virtual-kubelet/mas
ter/charts
Error: looks like "https://raw.githubusercontent.com/virtual-kubelet/virtual-kubelet/master/charts" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/virtual-kubelet/virtual-kubelet/master/charts/index.yaml : 404 Not Found

**Comment by helayoty** [comment]
The virtual-kubelet repo is the library. No helm chart can be found. To install the helm chart, you have to go to the provider repo and then install the provider helm chart. 

As a reference, [this](https://github.com/virtual-kubelet/azure-aci/tree/master/charts/virtual-kubelet) is the azure-aci helm chart doc.

Definitely, the documentation is old and needs to be updated. 

cc: @pires

**Comment by KirillPushkarev** [comment]
@helayoty Is there provider repo with helm charts for mock provider? It would be convenient to use it in load testing scenarios without running real nodes. Asking because it was mentioned in documentation.
