### ISSUE TITLE
Microsoft CLA is a blocker to contribution.

### ISSUE THREAD

**Issue by countspongebob** [virtual-kubelet/virtual-kubelet#110]
Propose changing CLA to CNCF.

Am happy to do a pull request if approved.

**Comment by rbitia** [comment]
https://github.com/kubernetes/community/blob/master/setting-up-cla-check.md 

I'm working through this documentation but I'm waiting on the secret for the webhook so it can be added. 
@countspongebob do you know of an easier/simple way to get it w.out adding the webhook?

**Comment by countspongebob** [comment]
I don't know, but I'm happy to reach out to the CNCF folks for some help.

**Comment by rbitia** [comment]
Just merged the new CLA! Let me know if you need anything else to contribute :)

**Comment by countspongebob** [comment]
Looks good, thank you!
