### ISSUE TITLE
Merge conflict committed in examples directory

### ISSUE THREAD

**Issue by inkel** [virtual-kubelet/virtual-kubelet#116]
In the current `master` (b35c50f7c54a339a32901aecc87cfc32b713f10c), the [`examples/nanoserver.yml`](https://github.com/virtual-kubelet/virtual-kubelet/blob/b35c50f7c54a339a32901aecc87cfc32b713f10c/examples/nanoserver.yaml) was committed with an unresolved merge conflict: https://github.com/virtual-kubelet/virtual-kubelet/blob/b35c50f7c54a339a32901aecc87cfc32b713f10c/examples/nanoserver.yaml#L20-L25

**Comment by rbitia** [comment]
Ah thanks for the issue. Thought I resolved this but it seems I didn't. It should be the nanoserver.yaml edit.

**Comment by robbiezhang** [comment]
Fixed in #117
