### ISSUE TITLE
Apache2 license preferred by CNCF/Kubernetes

### ISSUE THREAD

**Issue by countspongebob** [virtual-kubelet/virtual-kubelet#118]
Given the code might end up as a sub project in Kubernetes SIG node, suggest moving the license switched from MIT to Apache2.

**Comment by rbitia** [comment]
@resouer Are you okay with this?

**Comment by countspongebob** [comment]
If I opened a PR to change the license and then we had all the contributors reivew/approve the PR, would that suffice?

**Comment by cpuguy83** [comment]
Resolved by #214
