### ISSUE TITLE
[AWS] implement provider for ECS and Fargate

### ISSUE THREAD

**Issue by aaronwalker** [virtual-kubelet/virtual-kubelet#12]
### Summary
Add a provider for AWS ECS and Fargate 

### Description
Provide the ability to use kubectl to deploy a pod spec to AWS ECS and also to AWS Fargate. 

It should be possible to support deploying to both native ECS and to Fargate using the same provider. There are only slight differences is the task definitions between the two.

**Comment by aaronwalker** [comment]
I will mostly start working on an implementation of this in the coming weeks

**Comment by jessfraz** [comment]
Awesome!!! Thanks can’t wait to see :)

**Comment by rbitia** [comment]
Very exciting!! Let us know if you run into anything!

**Comment by dbenhur** [comment]
@aaronwalker This is pretty cool.  I imagine you're going to need to translate pods to ECS Tasks as that's the only public way to launch on Fargate atm.  You might find this container translation tool useful with that https://github.com/micahhausler/container-transform

**Comment by Raffo** [comment]
With the only objective of hacking around for a few minutes, I get an ecs/fargate integration running for the only `CreatePod` part... it's highly incomplete but it can be used for a starting point of such implementation, you can find it here: https://github.com/Raffo/virtual-kubelet/tree/master/providers/ecs . 
It would be interesting to discuss what would be the natural way of integrating such services with Kubernetes and how to map them with a Kubernetes pod. Also, not sure how we want to get the networking done in such cases as having a node is node enough to get the networking part solved.

**Comment by johanneswuerbach** [comment]
I took another try at connecting virtual-kubelet and AWS Fargate, feedback welcome https://github.com/virtual-kubelet/virtual-kubelet/pull/127
