### ISSUE TITLE
e2e is broken

### ISSUE THREAD

**Issue by pires** [virtual-kubelet/virtual-kubelet#1207]
CI needs revisiting, particularly bumping Minikube and kubectl which now requires a different package repo. FYI https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate

**Comment by pires** [comment]
I am self-assigning but feel free to pick it up and announce it here 🙏🏻

**Comment by wangrzneu** [comment]
I would love to work on this. @pires

**Comment by pires** [comment]
By all means, go ahead 🫶🏻
