### ISSUE TITLE
Support Downward API

### ISSUE THREAD

**Issue by robbiezhang** [virtual-kubelet/virtual-kubelet#123]
---

### Environment summary

Provider (e.g. Azure, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)
0.2-beta-8

K8s Master Info (e.g. AKS, ACS, Bare Metal)
AKS

Install Method (e.g. Helm Chart, )
Helm Chart

### Issue Details
VK doesn't support Downward API in the pod.

### Repo Steps
Sample pod snippet:
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName

**Comment by robbiezhang** [comment]
Kubelet Implementation:
https://github.com/kubernetes/kubernetes/blob/d7f61541364134a03a89fc3e836ad7a6c4a84384/pkg/kubelet/kubelet_pods.go#L800

**Comment by rbitia** [comment]
how do we implement internal ip - dynamic fields are harder to implement in the downward api

**Comment by rbitia** [comment]
we will pass in a "fake" value for ip to pass the conformance test for now

**Comment by rbitia** [comment]
#534 is the first PR to address this issue. We need to evaluate if we can close the downward API issue or not.

**Comment by corrieb** [comment]
We've reviewed and merged #534. The degree to which this satisfies the requirement is yet TBD, so we should leave this issue open for now. 

If attributes of a pod or container are going to show up in the filesystem of the container, that's something a provider is going to have to implement. The most that the core can do is to ensure that the resolved pod attributes are passed to the provider and that if any attributes need to be updated, that that update is also reflected.

**Comment by pires** [comment]
VK cannot provide conformance guarantees. This has been discussed in the past so I'm removing the related label from this issue.

Actually, I'd suggest this issue is edited or closed, given the functionality requested here fits the provider and not the VK. cc @cpuguy83

**Comment by yashdesai93** [comment]
https://github.com/virtual-kubelet/virtual-kubelet/pull/650 is a proposal to solve the remaining dynamic downward API envvar.

**Comment by S1yuan** [comment]
@cpuguy83 If any suggestion about how to deal with 'status.podIP' in v1.2.1 please let me know. Thanks!

**Comment by cpuguy83** [comment]
I think the best approach is to babe the provider deal with this.
We could make some helpers to make this simpler to implement, but I don't think there is anything else to do from the core the core runtime.
In fact I'd advocate for the provider handling all of the downward api through helper functions instead of implicitly through the runtime.

**Comment by pires** [comment]
As [before](https://github.com/virtual-kubelet/virtual-kubelet/issues/123#issuecomment-497957676) I agree this should be the responsibility of the provider(s).

**Comment by cpuguy83** [comment]
Closing this since we've supported downard API for some time now, but there are some gotchas that are not easily resolved.
As such I opened a new issue: #998

**Comment by MRVIOLETZ** [comment]
Hi.i'm interested
