### ISSUE TITLE
Virtual kubelet membner

### ISSUE THREAD

**Issue by cwdsuzhou** [virtual-kubelet/virtual-kubelet#1248]
@cpuguy83 @rbitia  Due 2-FA change, I was removed from the virtual-kubelet ORG, can you help me rejoin. Thank you.

![image](https://github.com/user-attachments/assets/21c5234a-51ee-47f5-89c5-f27f358e4440)

**Comment by pires** [comment]
I am unable to find your relevant contributions, I'm sorry. This sounds fishy.

**Comment by cwdsuzhou** [comment]
https://github.com/virtual-kubelet/tensile-kube/commits?author=cwdsuzhou   @pires  PTAL thanks

**Comment by cwdsuzhou** [comment]
Please add me as the matainer of `tensile-kube`
