### ISSUE TITLE
Cluster Networking

### ISSUE THREAD

**Issue by mumoshu** [virtual-kubelet/virtual-kubelet#13]
Hi, Thanks for starting the great project!

One of my concerns on this kind of solution for me is that the possibility to support cluster ndtworking i.e. pods served by virtual-kubelet are able to:

* Communicate with each other via pod and service IP regardless of where the pods are - real or virtual nodes
* Discover each other across real/virutal nodes

How would it be possible?
Are there any on-going effort(s) I can track or contribute?

**Comment by khenidak** [comment]
@ritazh @sozercan 
I will just try to list the use cases, Please correct me if i am wrong. 

**From** | **To** | **Notes**
--- | ---| ---
Virtual Pod | External IP | Currently possible
Virtual Pod | LoadBalancer Service | Possible on external ip *(insecure if no protocol level security)*
Pod | Virtual Pod External IP | Implementation specific, requires that the actual implementation (Azure/AWS) exposes public IPs. *Enhancement*: might be adding service with fixed endpoints for pods to communicate to virtual pods on fixed cluster-ip.
Pod | virtual pod on *cluster-pod-ip* | will require additional networking work, but possible. 
Virtual Pod | Pod/Cluster IP Service | Not possible as L4 traffic (as of now) however a side car can be loaded in the virtual pod proxying the traffic via well known address i.e *http://localhost:xxx:/namespaces/<ns>/pods/pod:portname-or-number/* or *http://localhost:xxx/namespaces/<ns>/services/svc:portname-or-number/* both needs to be carefully reviewed against network policies.


Virtual Pod = Pod that is running via the virtual kubelet (example a container group in Azure's case)

**Comment by rbitia** [comment]
Hi @mumoshu,  @erikstmartin was going to look into why the current implementation of "Virtual Pods to LoadBalancer service" because the currently the virtual kubelet breaks the LoadBalancer and external IPs aren't provisioned for new K8 services. I'm sure you could jump in there too or try to knock down the rest of the use cases Kal listed out. Email me ribhatia@microsoft.com if you want to get in our future stand ups and help implement the list of networking use cases.

**Comment by Raffo** [comment]
@rbitia I would also love to stay in touch with that even though I don't have many use cases for Azure itself (as I am not an Azure user myself for now).

**Comment by rbitia** [comment]
This matrix implemented for ACI and can be considered an implementation detail so we will close for now!

**Comment by alexellis** [comment]
@khenidak @rbitia not sure if you're both still working on this project, so excuse the ping if not.

What's the current state and recommendation for networking? I couldn't find details in the docs, I see good info on how to deploy a Pod, but not on how to make it accessible, or to access it in some way in a new Virtual Kubelet provider.

Thanks in advance
