### ISSUE TITLE
Issue running Helm chart

### ISSUE THREAD

**Issue by neilpeterson** [virtual-kubelet/virtual-kubelet#14]
When running the helm chart as described in the README.md file, the following is returned.

```
Error: gzip: invalid header
```

I do not think this is related, but if helpful, here are the values used with the chart. Are these correct?

- env.azureClientId - Service principal app id
- env.azureClientKey - Service principal password
- env.azureTenantId - Service principal tenant
- env.azureSubscriptionId - Azure subscription id
- env.aciResourceGroup - Name of empty resource group
- env.nodeName - Name for node, "virtual-kublet"
- env.nodeOsType - "Linux"

**Comment by MarkWme** [comment]
The CHART_URL is incorrect. It should be:

https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/virtual-kubelet-0.1.0.tgz

I set CHART_URL to that and it worked just fine.

**Comment by listonb** [comment]
Thanks to @MarkWme This has been fixed with PR #17
