### ISSUE TITLE
ResourceManager.watchSecrets() isn't implemented correctly

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#140]
Just looking at the code, it would appear that there's a cut and paste error in ResourceManager.

It seems like watchConfigMaps() was copied to watchSecrets(), but wasn't updated to make the correct call or evict entries from the correct map. Result is that secret updates won't be picked up by the VK.

I would fix this myself, but am still going through VMware legal to get permission to contribute.

**Comment by robbiezhang** [comment]
Good catch.
#132 fixed it, but blocked by the CLA
