### ISSUE TITLE
Support Job spec and ReplicaSet spec

### ISSUE THREAD

**Issue by brobichaud** [virtual-kubelet/virtual-kubelet#148]
---

### Environment summary
ACS cluster with Windows nodes, k8s v1.7.7-7. Windows Server 2016 RTM.

Provider (e.g. Azure, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)
0.1.1

K8s Master Info (e.g. AKS, ACS, Bare Metal)
ACS

Install Method (e.g. Helm Chart, )
Helm chart

### Issue Details
Is there any intention to support Job specs or ReplicaSet specs?

Jobs actually make a lot of sense for ACI. In my scenario I want to spin up new ACI instances based on an Azure Storage Queue having excessive messages. I'd like for the ACI's to each keep running as long as they can pull messages from the queue and process work, then terminate when no messages exist. But maybe this can be done with a Pod spec and the right restart policy?

ReplicaSets I'm less sure about but it seems like there are scenarios where I might want to ensure that X replicas of my pod stay active in ACI, until I remove that replicaset. And the really big win is that I could scale out/in the replicaset easily using known k8s techniques.

I'm sure these have been considered. What's the thinking?

**Comment by rbitia** [comment]
Hey @brobichaud once you deploy your workload as a pod you can scale it up as a replica set. You could also add those fields in your pod spec itself! It will work. We are building VK so most K8 concepts will seamlessly work :D

**Comment by brobichaud** [comment]
@rbitia I'm not sure what you mean? In order to scale up a pod don't I need a ReplicaSet or Deployment to wrap it? Are you saying that in my pod spec I could somehow specify the number of pods to create? Or are you saying that the virtual kubelet supports a replicaset spec now?

**Comment by arjanschaaf** [comment]
I was wondering about the same thing. Some examples on how to configure a Job / ReplicaSet to work with the virtual-kubelet taint configuration would be a big help.

**Comment by rbitia** [comment]
This demo goes through how to make a replica set for the azure container instances that get spun up from vk: https://github.com/rbitia/aci-demos

Does this help clear up the questions?

**Comment by brobichaud** [comment]
@rbitia I had to abandon ACI a while back because it only support Windows 2016 ltsc and I'd moved on to v1709, v1803 and soon v1809. I'm hoping ACI will catch up soon with v1809 support, at which point I will circle back and take another look.

**Comment by rbitia** [comment]
Sounds good! If you need any help just reach out. I'll close the issue for now.
