### ISSUE TITLE
Azure AKS virtual-kubelet pod gets an public ip instead of a cluster ip

### ISSUE THREAD

**Issue by arjanschaaf** [virtual-kubelet/virtual-kubelet#154]
---

### Environment summary

Provider (e.g. Azure, Hyper)

Azure

Version (e.g. 0.1, 0.2-beta)

virtual-kubelet-for-aks-0.1.3

K8s Master Info (e.g. AKS, ACS, Bare Metal)

AKS

Install Method (e.g. Helm Chart, )

Helm Chart

### Issue Details

After deploying a single pod on the virtual-kubelet node in my environment, I wanted to go a couple of steps further. I wanted to create a kubernetes deployment + kubernetes service + kubernetes ingress. That way the actual pod deployed on the virtual-kubelet node by my deployment would be exposed by the NGINX Ingress Controller currently running in my AKS kubernetes cluster.
I successfully created the deployment and a pod was started on the virtual-kubelet node. Only to my suprise the pod was given a public ip instead of an ip that is private to the kubernetes cluster (which it would get if this pod was deployed on a "normal" kubernetes node) and although the pod reported *ready* the replicaset never sees the pod as *ready*. Therefore it isn't registered with the service as a healthy endpoint and consequently the Ingress isn't going to work.

```
kubectl get replicaset
NAME                 DESIRED   CURRENT   READY     AGE
http-svc-597cdc956   1         1         0         39m
```

```
kubectl get pod
NAME                       READY     STATUS    RESTARTS   AGE
http-svc-597cdc956-m9rkn   1/1       Running   0          39m
```

How do I get a kubernetes deployment/replicaset to work while deploying on virutal-kubelet?

### Repo Steps

1) Create deployment
2) See pod being started and becoming ready
3) See that the replicaset / deployment never sees the replica (pod) as ready

**Comment by arjanschaaf** [comment]
Interesting @erjadi that would help with the status of the ReplicaSet. Which is half of the problem I'm seeing. The other half is that these pods get a public IP which is a situation I don't want and need. I just need an IP address for my pod that is reachable within the Kubernetes cluster. I'll take care of the external visibility of pods that I want to expose by deploying an Ingress object for that deployment

**Comment by erjadi** [comment]
Unfortunately I believe that is a limitation of the design. The Container Instance that is running your pod does not have direct access to your AKS cluster which means on a network level there is no way of establishing a connection without assigning a public IP.

I think to fix this we would first need ACI to support deployment inside VNets, but I'm not sure if that's on the roadmap...

**Comment by robbiezhang** [comment]
@erjadi I've merged #147, and will push a new image soon. @arjanschaaf VNet support is on ACI's roadmap, and we are actively working on it.

**Comment by jbenettius** [comment]
Is there an ETA yet for VNet support with ACI?

**Comment by robbiezhang** [comment]
@jbenettius, ACI VNet support for Linux will private preview soon. If you are interested, ping me in the slack for details.

**Comment by alexellis** [comment]
@robbiezhang is there an update on this?

**Comment by robbiezhang** [comment]
ACI VNet for Linux is public preview now. The latest VK image (^0.6.0) and the helm chart have integrated with it. @rbitia is updating the doc #354.

**Comment by ai2admin** [comment]
@robbiezhang how do I prevent my Windows containers instantiated via ACI from being exposed via public IP?

**Comment by robbiezhang** [comment]
@ai2admin VNet for Windows ACI is not ready yet. Targeting early next year.

**Comment by dhkhan** [comment]
@robbiezhang Does this mean that if I try to connect to a MySQL service on a normal AKS node(Linux) from a PHP WebApp hosted on IIS which is on the Windows Virtual Kubelet. It won't work?

I can expose an external IP to connect but I would want to communicate via a DNS name instead. Is it possible?

**Comment by robbiezhang** [comment]
Correct., it doesn't work now. You need a public DNS instead of cluster DNS. 
Windows ACI is not aware of the VNet or ClusterDNS.

**Comment by erudinsky** [comment]
Looks like still the same with virtual kubelet for Windows (public IP). 1.12.5.

**Comment by rbitia** [comment]
@srrengar Do you think we need an issue for windows VNet specifically? AKS with Linux virtual node's does get private IPs.

**Comment by srrengar** [comment]
There is an existing issue for Windows VNet for ACI - #535
