### ISSUE TITLE
Feature: Exec and attach support

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#157]
**Alpha release**

Add necessary capabilities to enable a Provider to support Exec and Attach from Kubectl. Note that the Provider does not have to implement this, so there needs to be a mechanism for gracefully failing the request.

**Comment by erjadi** [comment]
Hi @corrieb , there is a similar Issue already opened https://github.com/virtual-kubelet/virtual-kubelet/issues/106
Although it specifically asks for the ACI provider implementation, it implies that VK code would need to be updated.

**Comment by corrieb** [comment]
Thanks @erjadi I can close this as a duplicate. We just need to ensure that that issue gets the "alpha release" label.

**Comment by rbitia** [comment]
I will start adding labels as "alpha"
