### ISSUE TITLE
Feature: Support secret and configmap updates

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#158]
**Alpha Feature**

Currently, there is no way to propagate updates to secrets or configmaps to a Pod in VK. There needs to be a control loop that polls the API server for secret and configmap updates and this should then be pushed to the Provider either via the UpdatePod() function or via some explicit functions. See #159 as this is related

**Comment by rbitia** [comment]
At our next VK community meeting let's go through a design for tackling this issue.

**Comment by rbitia** [comment]
@corrieb proposed having a hook for listening to events for updates to config maps and secrets. Example name of the secret and key and value for it. Providers can choose to listen for them. @cpuguy83 will think on a design further.

**Comment by cpuguy83** [comment]
Ok, here's what I'm thinking (and have largely built):


Create 2 new controllers which watch for `Update` events on configmaps and secrets and call `UpdateConfigMap` or `UpdateSecret`... but we'll also track which pods are referencing these objects and pass that along with these update calls... and of course if there are no references we don't call update.

**Comment by cpuguy83** [comment]
Here is a draft PR: https://github.com/virtual-kubelet/virtual-kubelet/pull/586

I'm not sure that we need this for 1.0 as it doesn't require changing existing interfaces, only additive optional interfaces.

**Comment by rbitia** [comment]
Moving off the VK 1.0 milestone, we can this feature to our next release.

**Comment by pires** [comment]
For reference, I built this into systemk as I think this should be delegated to the provider. VK can help by asking the provider for callbacks for ConfigMap and Secret updates, eg `UpdateConfigMap(pod, cm)`, and call those when an event arrives for the respective resources.

I think I have what it takes to pick this up but would like for us to agree if it's something we want right now or later, so I can put effort into picking things that are higher priority for us.

**Comment by cpuguy83** [comment]
Closing in favor of #998
