### ISSUE TITLE
Feature: Design and implement UpdatePod() mechanism

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#159]
**Alpha Feature**

Currently, there's an UpdatePod() function in the Provider interface, but it is not driven by anything currently. There are two things that we need to accomplish here:

1) Decide on whether the Provider is responsible for caching Pod specs and doing the comparison work to figure out what updates need to be made to the Pod. If this is something every provider would need to do (it likely is), it would make sense to make it a utility function in VK or have VK handle the comparison and then call more granular functions in the Provider to update specific things like secrets or configmaps. If we go that route, we should replace UpdatePod() and have VK handle the caching of the Pod Specs

2) Implement the polling loop and connect up to the Provider

**Comment by corrieb** [comment]
We should review the syncPod code in Kubelet if it's helpful in determining an exhaustive list of what's possible to update. If that list is small, it might be worth adding granular calls to Provider. Otherwise a callback that allows Provider to compare Pod Specs would be useful.

**Comment by rbitia** [comment]
**We need this.**

**Comment by cpuguy83** [comment]
Implemented in #613
