### ISSUE TITLE
Docs on recommended way to do development

### ISSUE THREAD

**Issue by zoidbergwill** [virtual-kubelet/virtual-kubelet#16]
It's awesome that this using `~/.kube/config` means it so smoothly works, even with `minikube`.

It'd be great to have something in the README or in a separate development doc on the recommended way to work on existing providers or new ones.

Maybe it's just cuz I'm a noob, but I'm not sure if I'm doing it right, but I basically did this:

```
go get github.com/virtual-kubelet/virtual-kubelet
cd $GOPATH/src/github.com/virtual-kubelet/virtual-kubelet
make build
./bin/virtual-kubelet --provider bash
```

**Comment by rbitia** [comment]
I agree! Check back in for improvements in the coming weeks.

**Comment by rbitia** [comment]
We should add documentation on recommending using a linux machine but otherwise your steps are correct for developing w/ VK.
