### ISSUE TITLE
Feature: Disable privileged containers for VK

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#162]
We need to figure out how to stop the API server from deploying Privileged containers to VK. This includes DaemonSets. This would likely be the mechanism we would use for preventing kube-proxy from coming up on the node.

**Comment by cpuguy83** [comment]
I think this is up to the implementation to deal with, and otherwise node taints seem appropriate.

**Comment by corrieb** [comment]
Yea I would agree.
