### ISSUE TITLE
Feature: Pass Service definitions to the Provider

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#163]
**Alpha feature**

See #161 for high-level feature

VK should listen for Services being created on the API server and pass those to the Provider with enough information that the Provider can set up the appropriate routes.

**Comment by corrieb** [comment]
Thinking about the architecture for this. There's a clear separation in the codebase between the control loop that updates the Provider with Pods (in the main server) and the control loop that updates secrets and configmaps (in resourcemanager). The difference seems to be that secrets and configmaps are specifically bound to pods when pods are created and it was probably assumed that the Provider would never need to be notified of secret or configmap updates. That's actually not the case as it happens. If a secret or configmap update impacts a Pod, then the Provider needs to be notified about that. However, that can be done through UpdatePod(). 

Services are not bound to pods and Service objects need to be created, updated and deleted as first class objects on the Provider interface. This means that the mechanism for watching for services and updating the Provider should be consistent with the mechanism for Pods.

**Comment by rbitia** [comment]
We have implemented this! Closing for now.
