### ISSUE TITLE
Feature: Specify or learn CIDR range for pods

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#164]
**Alpha feature**

It should be possible to specify a CIDR pod range for a VK when it's created and it should also be possible for VK to learn a CIDR range from the API server if that is desired. This should then be passed to the Provider so that it can allocate IP addresses to pods correctly.

**Comment by ofiliz** [comment]
I expect the way pod CIDR range is specified to be different for each provider. For Fargate, the CIDR range is implicit in the VPC subnet being passed in provider configuration. The solution needs to be flexible to account for that.

**Comment by rbitia** [comment]
So is this provider specific? Does VK need to understand CIDR ranges?

**Comment by rbitia** [comment]
We think this isn't necessary?

**Comment by rbitia** [comment]
In controller manager we might need to delegate the pod CIDR.  --allocate-node-cidr 
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
so do we support this or not.. or do we delegate whether this flag is true or false for your K8 service?

**Comment by rbitia** [comment]
Needs more experimentation in VK so see what the "pod cidr" field in the node status is

**Comment by rbitia** [comment]
Alright so we decided this range was up to a provider to implement. Closing for now.
