### ISSUE TITLE
Investigation: Decide how affinity constraints can be passed through to a Provider

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#165]
A VK node may represent multiple failure domains and there may be a separate scheduler that sits behind the VK that can handle affinity policy. In that respect, it should be possible for a node to advertise the fact that it represents multiple failure domains and can handle affinity policy for multiple pods. 

This is something that needs to be raised with #sig-architecture.

**Comment by rbitia** [comment]
Do we push this to the provider or vk to answer?
Virtual failure domain tied to policies to the pod? w/ labels
still open to discussion

**Comment by pires** [comment]
Affinity is a scheduling predicate. VK doesn't handle or interfere w/ scheduling.

**Comment by rbitia** [comment]
^ Agreed. We have specific azure documentation around affinities already. I think we should close this.

**Comment by rbitia** [comment]
Closing from the above discussion.
