### ISSUE TITLE
Investigation: What can be gained from having a VK admission controller

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#166]
There are various aspects of control that's desired with respect to scheduling pods to Virtual Kubelet which may fall outside of the scope of taints and tolerations. This includes:

- Preventing VK from deploying privileged pods
- Preventing VK from deploying daemonset pods
- Possible role in enforcing per-tenant resource limits to VK nodes
- TBD (we need to clarify these requirements better)

This is largely related to User Experience. It's much better for a Pod to fail to deploy before it gets scheduled to a node, than have the node fail to deploy it.

**Comment by rbitia** [comment]
extend kubernetes with this controller that can be edited at runtime 
cloud provider limitations and specifications can go through here too 
possibly make it general 

or we could make a new kubernetes resource (like gpus) and make some sort of capacity and auto annotations.

**Comment by rbitia** [comment]
I'll add the admission controller to this repo. We have one for VK.

**Comment by rbitia** [comment]
It's a provider specific UX to provide an admission controller. Azure's is here for reference: https://github.com/Azure-Samples/virtual-node-autoscale/tree/master/vn-affinity-admission-controller

We don't need to have admission controllers mentioned in core vk, so I'll close this for now.
