### ISSUE TITLE
Investigation: Events

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#169]
We need to understand what business value is delivered by the VK sending events back to the API Server. What classes of events do we want to support and how does that link into the Provider?

**Comment by rbitia** [comment]
Look at VK features and the corresponding events for that actual feature to create the events based off of that.

**Comment by rbitia** [comment]
Event mechanism in VK? so the provider can tell VK to send an event back.

**Comment by rbitia** [comment]
Still needs more investigation for which objects need events. Might require changes in the provider API

**Comment by rbitia** [comment]
We send out events like create pods, delete pods, from VK. Providers can choose to send more events or add issues to add more events to the VK core. 

Closing this issue since we do this today.
