### ISSUE TITLE
Feature: Implement Port forwarding

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#170]
**Alpha Release**

There's a need to be able to open a port on the host running kubectl and tunnel through to a port on a Pod. We need to implement this capability in VK, which will likely require an update to the Provider interface.

**Comment by rbitia** [comment]
What does port forwarding enable since we have exec already?

**Comment by asrivas-vmw** [comment]
Its slightly different; yes exec can be used to check on the health of the service but it cannot verify behavior and expose service internals which are possible via kubectl port forward.

**Comment by jeremyrickard** [comment]
#dibs

**Comment by erjadi** [comment]
Do we know if any providers would currently support this? Correct me if I'm wrong but I think most providers do not allow access to a port on a pod that hasn't been exposed at the time of deployment.

**Comment by rbitia** [comment]
Maybe we can implement this for CRI today and give an endpoint that a provider can take and provide port forwarding to the end user.

**Comment by rbitia** [comment]
This is an additive change but we discussed in person and we don't think we need this for 1.0.

**Comment by pires** [comment]
IIUC this is not as trivial as an interface addition but actually requires the VK to support SPDY (which is part of moby/spdystream) so the kube-apiserver can do async bidirectional streaming. SPDY is a deprecated in favor of HTTP/2 but Kubernetes still relies a lot on it and the only other supported alternative is Websockets, which I'm unsure if supports port-forwarding.

So is this something we want to tackle now, soon, later, or just a moonshot?

**Comment by cpuguy83** [comment]
Discussing this some more with azure-aci maintainers.
It looks like at this point what we need to do in the VK core is add a config option here https://github.com/virtual-kubelet/virtual-kubelet/blob/410e05878a80b9ce5e95efcfe40f801c57cdc144/node/api/server.go#L36-L46
as well as the appropriate route handling, but it will be up to the provider to wire that up.
This is very similar to how `kubectl exec` would work, I think.

**Comment by pires** [comment]
Unless I'm missing something, this is not something you can handle w/ HTTP/1 like we do for `kubectl logs` (eg https://github.com/virtual-kubelet/systemk/pull/69 and https://github.com/virtual-kubelet/systemk/pull/70), since `port-forwarding and exec are bidireccional, while logs is request-response. Therefore, I think VK would require SPDY or maybe WebSockets (it's coming!! https://github.com/kubernetes/kubernetes/pull/110142) support.

**Comment by cpuguy83** [comment]
Correct the portfoward enpoint does is similar what the exec endpoint does: https://github.com/kubernetes/kubernetes/blob/fbffe056dd03bd9c746e8819ad22043d640a4489/pkg/kubelet/cri/streaming/portforward/portforward.go#L41-L53

Note that we already support exec.

**Comment by aka-somix** [comment]
Hi there!
with @ssoBAekiL we did work on this issue on a private fork for the [LIQO provider](https://github.com/liqotech/liqo), which is currently using the proposed implementation. 

You can find the PR up here, it should solve the issue reported.
