### ISSUE TITLE
Feature: Improve Debug Logging and log persistence

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#172]
The VK codebase currently has a rather ad-hoc approach to logging. It doesn't currently have any formal approach for log persistence/rotation. We should come up with a standard approach for debug logging, add some better logging to the code and then publish the guidelines to the contributor FAQ.

**Comment by rbitia** [comment]
TBA

**Comment by rbitia** [comment]
I think we do this now. So I'll close the issue.
