### ISSUE TITLE
[Azure] Kubectl logs not working.

### ISSUE THREAD

**Issue by aku105** [virtual-kubelet/virtual-kubelet#177]
---

### Environment summary

Provider (e.g. Azure, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)
Tried Release v0.2-beta-11 as well as built new one from Master HEAD.

K8s Master Info (e.g. AKS, ACS, Bare Metal)
Provisioned using acs-engine.

Install Method (e.g. Helm Chart, )
Installed as an add-on on acs-engine.

### Issue Details
I can create a pod on the ACI using the virtual-kubelet, but I'm not able to get logs for the pod created using `kubectl logs`. However, if I'm reading #2 correctly, that should have been working.

### Repo Steps
Using `aci-pod.yaml` below
```yml
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - image: appropriate/curl
    imagePullPolicy: Always
    name: curl
    args:
    - /bin/sh
    - -c
    - curl nginx.default.svc.cluster.local; sleep 90000
    resources:
      requests:
        memory: 1.5G
        cpu: 1
  dnsPolicy: ClusterFirst
  nodeName: aci-connector
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
```

```sh
$ kubectl create -f aci-pod.yaml
pod "helloworld" created

$ kubectl get pod -owide
NAME         READY     STATUS    RESTARTS   AGE       IP        NODE
helloworld   1/1       Running   0          2m        <none>    aci-connector

$ kubectl logs helloworld
Error from server (NotFound): the server could not find the requested resource ( pods/log helloworld)
```

I can get the logs using `az container` command
```sh
$ az container logs --ids <container-id>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: nginx.default.svc.cluster.local
```

**Comment by rbitia** [comment]
Hey @aku105 you need to do some extra configurations to enable kubectl logs: https://ritazh.com/understanding-kubectl-logs-with-virtual-kubelet-a135e83ae0ee
Rita wrote up a great article on it, scroll down to the bottom to see how to set it up!

**Comment by aku105** [comment]
Thanks @rbitia, seems like it's an implementation issue in acs-engine.

**Comment by gonarys** [comment]
I had this problem and it turned out that I had a resource that used the subnet dedicated to AKS. you have to check this and if so, remove the resource.
