### ISSUE TITLE
[Azure] Using Service Principal credentials to pull private image in ACR

### ISSUE THREAD

**Issue by jmshal** [virtual-kubelet/virtual-kubelet#192]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)

ACI

Version (e.g. 0.1, 0.2-beta)

`microsoft/virtual-kubelet:latest` (aka. 0.2-beta-12)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

AKS

Install Method (e.g. Helm Chart)

`az aks install-connector [...]`

### Issue Details

When specifying a private image hosted on an ACR (Azure Container Registry), the Azure AD Service Principal authentication credentials are not passed to the ACI. Private images work totally fine if the pods are run on the AKS nodes, but do not behave the same way using virtual-kubelet - I naively expect the same result regardless of where the underlying pod is running.

As a workaround I have created a secret (of type `kubernetes.io/dockerconfigjson`) which contains the Service Credentials details needed to pull the private image from ACR (username/appId and password). And I point the spec at the secret (via [`imagePullSecrets`](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)). As I took a look through the provider code and noticed that it supported this feature (see below).

https://github.com/virtual-kubelet/virtual-kubelet/blob/f3ebde2533f7854698df8a298386154d423854e2/providers/azure/aci.go#L444-L472

I could not find any other references that would suggest these credentials could be automatically passed to ACI. But for the time being, my workaround functions as expected - I'm not just entirely sure if it's the best way to do it.

I also noticed that when specifying multiple auths (eg. `https://example.azurecr.io` and `example.azurecr.io`) in the docker config json secret, ACI also throws an error. So this workaround requires a secret per container registry (which is probably a good idea anyway) - if you're pulling from multiple ACRs. I'm not, but it's worth noting, because the code below suggests that you could provide multiple auths, yet I'm not sure that could ever work.

https://github.com/virtual-kubelet/virtual-kubelet/blob/f3ebde2533f7854698df8a298386154d423854e2/providers/azure/aci.go#L520-L526

I hope that's enough info.

### Repo Steps

- Create an AD SP
- Create an ACR (and assign the `Reader` role to the SP)
- Push an image to the ACR
- Create an AKS cluster (using the SP)
- Install the ACI connector
- Create a deployment/pod which targets the ACI, and which uses the ACR image name (eg. `example.azurecr.io/nginx:latest`).
- Check the ACI resource group's activity log for the error message (or check the ACI connector pod's logs)

Example JSON output from the resource group's activity log:

```json
{
    ...
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": "eastus:36880b71-f747-4192-81d0-1002aa458943",
        "statusMessage": "{\"error\":{\"code\":\"InaccessibleImage\",\"message\":\"The image '[REDACTED].azurecr.io/[REDACTED]:latest' in container group 'default-[REDACTED]-7fb697cdbc-rmqpw' is not accessible. Please check the image and registry credential.\"}}"
    },
    ...
}
```

**Comment by rbitia** [comment]
Thank you for all the detail! The AD service principle creds do not get passed down to ACI so your workaround to create a secret is the recommended way to pull from ACR. I agree you shouldn't need to think about where your pod is running ACI vs. in cluster so in the future we will figure out how to enable that workflow.

**Comment by jmshal** [comment]
Thanks @rbitia! It's great to have that clarification.

**Comment by CharlesCara** [comment]
Could I make a request that you add a note to the existing virtual kubelet documentation about needing to add a kubernetes secret to the pod spec?  Would have saved me a fair amount of time today.

**Comment by lachie83** [comment]
I believe this issue has been addressed. Closing
