### ISSUE TITLE
[Azure] Run on master node

### ISSUE THREAD

**Issue by robrich** [virtual-kubelet/virtual-kubelet#198]
I'm confident this isn't the right place, but not seeing a better place, here goes:

**Problem Statement:** I'm trying to run a 0-node cluster on AKS (v 1.9.6).  E.g. the ACI-connector will be the only worker node on the system.  However, when I delete the vm worker nodes on the AKS account, it shuts off tiller and the aci connector.  It makes sense: they were running on a worker node.

**Desired Behavior:** I can run ACI-connector on AKS master node so the ACI-connector can be the only node in the cluster.

**Comment by robbiezhang** [comment]
It's not supported now. The virtual-kubelet (ACI-connector) must be run on a worker node.

**Comment by corrieb** [comment]
There's been no movement on this and @rbitia doesn't believe there are any immediate plans for it. Closing as stale.
