### ISSUE TITLE
Virtual kubelet fails initialization when using a config file with clusterrole = system:node

### ISSUE THREAD

**Issue by lcastellano** [virtual-kubelet/virtual-kubelet#210]
---

### Environment summary

Provider: mock

Version (0.2-beta)

K8s Master Info (ubuntu VM, vSphere)

Install Method (Hard Way)

### Issue Details
When given a correct kubelet config file (with clusterrole system:node), the Virtual Kubelet fails to start. It exits with a ###Forbidden error message when trying to register a watch for either: configmaps and secrets. This is the correct authorization behavior as the  clustterrole: system:node does not not have permission to watch those resources:

```kubectl describe clusterrole system:node --namespace=kube-system
Name:         system:node
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate=true
PolicyRule:
  Resources                                       Non-Resource URLs  Resource Names  Verbs
  ---------                                       -----------------  --------------  -----
  configmaps                                      []                 []              [get]
  endpoints                                       []                 []              [get]
  events                                          []                 []              [create patch update]
  nodes                                           []                 []              [create get list watch delete patch update]
  nodes/status                                    []                 []              [patch update]
  persistentvolumeclaims                          []                 []              [get]
  persistentvolumes                               []                 []              [get]
  pods                                            []                 []              [get list watch create delete]
  pods/eviction                                   []                 []              [create]
  pods/status                                     []                 []              [update]
  secrets                                         []                 []              [get]
  services                                        []                 []              [get list watch]
  tokenreviews.authentication.k8s.io              []                 []              [create]
  localsubjectaccessreviews.authorization.k8s.io  []                 []              [create]
  subjectaccessreviews.authorization.k8s.io       []                 []              [create]
  certificatesigningrequests.certificates.k8s.io  []                 []              [create get list watch]
  volumeattachments.storage.k8s.io                []                 []              [get]
```
### Repo Steps
Launch mock virtual kubelet with an appropriate kubelet config file. The process exits with an error while trying to request a watch on either configmaps or secrets (depending on the first to execute).

**Comment by rbitia** [comment]
@corrieb can you take a look at this one?

**Comment by rbitia** [comment]
Ah is this because we haven't enabled cluster roles?

**Comment by lcastellano** [comment]
I don't think that is related enabling clusterroles. Here are mode details.
The regular Kubelet runs with cluster role: **system:node**. This role is more restrictive than **admin**.  Specifically an account with **system:node** role is forbidden to perform watch operations on the resources **secrets** and **configmaps**. The following commands can be used to find the permissions of the admin role:

```kubectl describe clusterrole admin```

the actions permitted on the **secrets** resource are:

```secrets                                         []                 []              [create delete deletecollection get list patch update watch]```

when running the same command on the system:node role:

```kubectl describe clusterrole system:node```

it produces:

```secrets                                         []                 []              [get]```

Notice that the verb "watch" is present for **admin** but missing for **system:node**.

Virtual Kubelet tries to **watch** both **secrets** and **configmaps**. If the Virtual Kubelet runs with **admin** role (by using an admin config file) it succeeds in creating the watches. However, when it is run with **system:node** role (the correct role for a Kubelet) it fails to create the watches because it does not have to correct permissions. I believe that the problem is the fact that the Virtual Kubelet is instantiating watches for **secrets** and **configmaps**.

**Comment by robbiezhang** [comment]
@lcastellano Thanks for sharing the information. I believe the VK needs the watch permission to get notified effectively when the secret/configmaps is changed. I'm curious about how kubelet implement to re-mount the secret volume when secret is changed. Do you have any idea?

**Comment by corrieb** [comment]
Clearly we need to investigate how Kubelet manages to watch for Secret / ConfigMap changes with a role that doesn't appear to have authorization to do so. There's likely some kind of magic involved. I agree this should be a goal for 1.0 that VK runs as the same role as regular Kubelet

**Comment by pires** [comment]
@rbitia @cpuguy83 I've eliminated the `vk 1.0` label since we have now a milestone for it. Do you think this is reasonable to have as part of said milestone?

**Comment by pires** [comment]
The issue described here is no longer valid as `system:node` cluster role can now watch for Secrets and ConfigMaps.

```
Name:         system:node
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
PolicyRule:
  Resources                                       Non-Resource URLs  Resource Names  Verbs
  ---------                                       -----------------  --------------  -----
  leases.coordination.k8s.io                      []                 []              [create delete get patch update]
  csinodes.storage.k8s.io                         []                 []              [create delete get patch update]
  nodes                                           []                 []              [create get list watch patch update]
  certificatesigningrequests.certificates.k8s.io  []                 []              [create get list watch]
  events                                          []                 []              [create patch update]
  pods/eviction                                   []                 []              [create]
  serviceaccounts/token                           []                 []              [create]
  tokenreviews.authentication.k8s.io              []                 []              [create]
  localsubjectaccessreviews.authorization.k8s.io  []                 []              [create]
  subjectaccessreviews.authorization.k8s.io       []                 []              [create]
  pods                                            []                 []              [get list watch create delete]
  configmaps                                      []                 []              [get list watch]
  secrets                                         []                 []              [get list watch]
  services                                        []                 []              [get list watch]
  runtimeclasses.node.k8s.io                      []                 []              [get list watch]
  csidrivers.storage.k8s.io                       []                 []              [get list watch]
  persistentvolumeclaims/status                   []                 []              [get patch update]
  endpoints                                       []                 []              [get]
  persistentvolumeclaims                          []                 []              [get]
  persistentvolumes                               []                 []              [get]
  volumeattachments.storage.k8s.io                []                 []              [get]
  nodes/status                                    []                 []              [patch update]
  pods/status                                     []                 []              [patch update]
```
