### ISSUE TITLE
Reason for Having Two Helm Charts

### ISSUE THREAD

**Issue by stevenpall** [virtual-kubelet/virtual-kubelet#215]
Hi there,

I'm considering submitting a pull request to generalize the existing virtual-kubelet Helm chart(s) and I was wondering why there are currently two separate chart directories (`virtual-kubelet` and `virtual-kubelet-for-aks`). From what I can tell, these are very similar, especially considering the `virtual-kubelet` chart is really only useful on AKS at the moment anyway.

As the number "virtual infrastructure" services grow, I think having a pluggable chart that's as generic as possible makes sense, but if there are differences between the environments that warrant their own charts, then the existing layout might make sense. I just wanted to ensure that that is in fact the case before proceeding with any future work.

Thanks!

**Comment by rbitia** [comment]
Agreed, having a generic pluggable chart would work. Maybe creating one for the sample CRI provider would make sense? 

From there each provider could add their own specific chart in the charts folder for easy access or we can move them all to the separate provider folders.

**Comment by neumanndaniel** [comment]
With the AKS GA release and RBAC support available in AKS it is important to have them merged together. Per default az aks install-connector is using virtual-kubelet-for-aks without RBAC support. --chart-url does not work currently for me specifying the virtual-kubelet Helm chart. I am getting Error: gzip: invalid header

**Comment by jlegrone** [comment]
I'm happy to take a crack at this.  Just need to get an AKS subscription set up for testing. 😄
