### ISSUE TITLE
Plan to support OpenStack provider?

### ISSUE THREAD

**Issue by yihleong** [virtual-kubelet/virtual-kubelet#22]
Any plan to include support for OpenStack provider?

**Comment by resouer** [comment]
The best candidate providers are expected to has a container instance API like Azure ACI, AWS Fargate and hyper.sh. 

I am not sure if it's possible in OpenStack? Pure Nova? While Nova VM instances startup time may be kinda slow. Nova-docker? Anyway discussion and contribution are always welcome!

**Comment by yihleong** [comment]
What about OpenStack Zun? 
https://wiki.openstack.org/wiki/Zun

**Comment by resouer** [comment]
Zun looks promising. So you can write a provider for it. We are working out a working group to discuss the expectations to "providers".

**Comment by kevin-zhaoshuai** [comment]
@resouer I'm from Zun project and focusing on connect Zun with Kubernetes, we are considering to add support for virtual-kubelet to make Zun as a container backend for Kubernetes user. @yihleong  welcome to work together on this ticket.

**Comment by kevin-zhaoshuai** [comment]
I will do this now

**Comment by kevin-zhaoshuai** [comment]
Finished all the gophercloud support work for Zun now. Gophercloud is the OpenStack golang client. The WIP code for virtual-kubelet is in my [Repo](https://github.com/kevin-zhaoshuai/virtual-kubelet), will refine the code and submit a PR here in a few days.

**Comment by hongbin** [comment]
The OpenStack Zun provider is implemented and merged: https://github.com/virtual-kubelet/virtual-kubelet/pull/239 . I guess we can close this issue?

**Comment by cpuguy83** [comment]
Yep, thanks!
