### ISSUE TITLE
[Azure] Number of containers per container group limit 

### ISSUE THREAD

**Issue by martell** [virtual-kubelet/virtual-kubelet#225]
I'm glad to see great work has been done with migrating from the js/typescript version to the provider agnostic go version that is virtual-kubelet. Great work by all involved

I'm looking at rolling this out with some level of scale once the exec spec and been formalized and merged with aci support.

Looking at the MS documentation for limits.
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quotas

I see `Number of containers per container group` which does not have a citation to be increased.
You can however increase the `Container groups per subscription`.

I haven't looked too deeply but it seems we could implement support in the virtual kubelet to use multiple container groups, probably with an extra toleration or something to separate by group.

Would it be worth my time implementing that or would pushing your azure container instance team to increase the `Number of containers per container group` to match the multiple of number of groups.

In general it makes sense to limit it because a bunch of users will end up making mistakes and using too much resulting in a large bill but what about those of us that want to take advantage of the scale.
I'm not sure of any technical reason for this limit, people more knowledgeable about the inner workings of Azure feel free to chime in there.

**Comment by rbitia** [comment]
So we have a limit of about 60 containers within a container group. A container group matches what a pod is in Kubernetes. For the number of container groups you can create itself there's a limit of 20 (but this can be increased if you talk to us). 

The way you create container groups is the way you create a pod in kubernetes and if you scale that up you will have multiple container groups or pods. 

Hopefully this makes sense. The scale is something a user has to explicitly enter through Kubernetes.

**Comment by rbitia** [comment]
Closing! thanks
