### ISSUE TITLE
virtual-kubelet show error 'interface public not found'

### ISSUE THREAD

**Issue by jpds** [virtual-kubelet/virtual-kubelet#229]
### Environment summary

Provider: AWS Fargate

Version: v0.3.2

K8s Master Info: kops AWS

Install Method: virtual-kubelet binary on EC2 node

### Issue Details

When we run the virtual-kubelet on our EC2 node, we always see this as the first line of output:

```
ERRO[0000] interface public not found
```

I've tried grep'ing this git repo to find out where this comes from but I can't find where this is coming from.

**Comment by jpds** [comment]
This is possibly related to https://github.com/cloudnativelabs/kube-router/issues/468

**Comment by sabbour** [comment]
I've seen that error on AKS as well.

**Comment by robbiezhang** [comment]
The error message is printed before the first message of the virtual-kubelet. I can see the message even I just run `go run main.go`
The error message is first seen in tag 0.3.1. It doesn't appear in 0.3.0. I tried all commits between these 2 tags, and find commit 513cebe7b7cf590cd53c02ea8da1a20b58dd8f18 (#206) probably is the one introduced the issue.

@sflxn, can you take a look at this issue?

**Comment by robbiezhang** [comment]
The error is from this line:

https://github.com/virtual-kubelet/virtual-kubelet/blob/ef6ae9ecf4163441fbe3bcf1bcc9e04d0402389f/vendor/github.com/vmware/vic/lib/apiservers/engine/network/utils.go#L66

@sflxn

**Comment by sflxn** [comment]
Looking into it.

**Comment by sflxn** [comment]
To fix this issue within this project, I had to update the vendor with dep ensure -update github.com/vmware/vic to pick up the changes.  We were doing something in the go initializer that didn't belong there.

**Comment by rbitia** [comment]
Closing this issue because it looks like VIC fixed their dependency errors.
