### ISSUE TITLE
Virtual Kubelet podWatcher watches in the installed namespace only

### ISSUE THREAD

**Issue by sabbour** [virtual-kubelet/virtual-kubelet#232]
Design document says Virtual Kubelet defaults to monitoring all namespaces but it seems from this line that it actually defaults to monitoring the namespace that the Virtual Kubelet has been installed in.

https://github.com/virtual-kubelet/virtual-kubelet/blob/8068f3cac80a2cbc64e97af040ffd2caf3234f1e/vkubelet/vkubelet.go#L208

**Comment by sabbour** [comment]
Created a PR https://github.com/virtual-kubelet/virtual-kubelet/pull/233

**Comment by robbiezhang** [comment]
s.namespace is determined by the `--namespace` input parameter.
https://github.com/virtual-kubelet/virtual-kubelet/blob/027b76651da0735fa84758d8d7928e336afaf791/cmd/root.go#L75

We uses "default" namespace in the helm chart, but you can update the deployment to customize your VK. If you want the VK to monitor all namespaces, you can remove it from the start up command.
https://github.com/virtual-kubelet/virtual-kubelet/blob/027b76651da0735fa84758d8d7928e336afaf791/charts/virtual-kubelet-for-aks/templates/deployment.yaml#L50

**Comment by sabbour** [comment]
Thanks for clarifying @robbiezhang , though I think this should be a parameter in the Helm chart with a default value instead of being hardcoded. If you don't mind, I can do a PR for that.
One other aspect of this, it should be configurable from the az CLI, somewhere around this line I suppose: https://github.com/robbiezhang/azure-cli/blob/e3f6d714554c316903d850a4c0ef16f7cb8a7382/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L386

**Comment by sabbour** [comment]
Also I'm confused this:
The command says `kubernetes namespace (default is 'all')` but the Helm chart is hardcoded to use `default`.

**Comment by sabbour** [comment]
Created a PR https://github.com/virtual-kubelet/virtual-kubelet/pull/235
