### ISSUE TITLE
Add a liveness probe 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#238]
We need to add liveness probes into VK :)

**Comment by jskulavik** [comment]
What context should they run in?  Probes need to be external to the cluster, VM, process, etc in order to be effective and reliable.

**Comment by rbitia** [comment]
Here's some context: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-liveness-probe 

We are looking within the container at runtime to make sure the app is running the way it should.

**Comment by arashbina** [comment]
Is anyone looking into this? I can work on it if no one is.

**Comment by Smithx10** [comment]
I think we should use a Prometheus HTTP endpoint to report health, and put the responsibility on the application owner.   The probe struct will just inform the metric to watch for etc.    Has there been any progress on this?   I am very interested in helping.

**Comment by pires** [comment]
VK already reports `PodStatus` per pod, as computed by the provider. Therefore, I think liveness/readiness probes are to be owned by the provider implementation.

If a probe fails, the pod status is updated and next time VK asks `GetPodStatus`, the failure is reported to the Kubernetes control-plane.

**Comment by asrivas-vmw** [comment]
Right, I agree with @pires. Liveness probes should not be part of VK itself, and can be implemented by the specific providers. I think we can close this issue unless someone vehemently objects to this.

**Comment by pires** [comment]
@asrivas-vmw I'd argue we should document it before closing, though.

**Comment by rbitia** [comment]
Closing now that we have it in view to document that the provider is fully responsible for implementing this feature.
