### ISSUE TITLE
KubeNamespace for VK

### ISSUE THREAD

**Issue by fisherxu** [virtual-kubelet/virtual-kubelet#245]
Now the kubeNamespace is "all" in default, but if we set it to a specified value(ns), the VK only accepts pods under ns. But the schduler has no the strict, it can schdule pod in any namespace to VK, so pods not in ns will exec failed. So the kubeNamespace be really useful in VK? I think we should accept all pods like a node.
/cc @rbitia @robbiezhang

**Comment by sabbour** [comment]
@fisherxu are you seeing the same behavior my comment here: https://github.com/virtual-kubelet/virtual-kubelet/pull/235#issuecomment-399740348 or is this a different issue?

**Comment by cpuguy83** [comment]
Yes, this should be looking at all namespaces.

**Comment by fisherxu** [comment]
So, don't know which case the KubeNamespace option used for...

**Comment by cpuguy83** [comment]
@fisherxu I'm not sure why it was added, however I can see a case where you could have multiple controllers handling things differently per namespace... or scoping down access to a certain namespace.

I don't think it's bad to have, I'm not sure the implementation on the VK CLI is all that great for it.

**Comment by cpuguy83** [comment]
We can probably mark the flag deprecated and plan to remove for 1.0 unless someone has a solid use-case for the flag in the VK CLI.

**Comment by cpuguy83** [comment]
Since we won't be keeping a binary for the 1.0 release (providers will implement their own binary) I think we can safely close this.

We do look at all namespaces by default.
