### ISSUE TITLE
proposal: single mock virtual-kubelet simulate multiple kubelet instances

### ISSUE THREAD

**Issue by mqliang** [virtual-kubelet/virtual-kubelet#251]
We are currently working on evaluating a scheduling policy, with virtual-kubelet simulating a bunch of nodes. 

However, current virtual-kubelet mock provider can only simulate a single node, in other words, to simulate N nodes, we need launch N virtual-kubelet instances.

I am thinking using single virtual-kubelet to mock multiple nodes. WDYT?

@robbiezhang 
cc @glikson

**Comment by mqliang** [comment]
FYI: @lioncruise

**Comment by lioncruise** [comment]
@mqliang  I have already used a VK process to mock multiple nodes by multiple-threads. See 
 repos `https://github.com/lioncruise/virtual-kubelet`. In my experiment, it can perfectly support 500 k8s nodes's scheduling simulation with third-party scheduler.
