### ISSUE TITLE
proposal: provider specific label

### ISSUE THREAD

**Issue by mqliang** [virtual-kubelet/virtual-kubelet#256]
Does it sounds good to add a `Labels() (map[string]string)` method to provider interface, and merge the provider specific labels and VK generic labels (https://github.com/virtual-kubelet/virtual-kubelet/blob/master/vkubelet/vkubelet.go#L174-L179)

provider specific labels can been read from provider config files. This feature is very useful for using the mock provider to simulate a bunch of heterogeneous nodes. (add "az", "rack numbers" information as labels.)

**Comment by mqliang** [comment]
@robbiezhang
cc @glikson

**Comment by robbiezhang** [comment]
Agree. #221 was created to discuss this issue. We also have such requirement, and we believe other providers might also need this feature. 
Some ideas:
1. Do we allow the provider to overwrite the common VK labels?
2. Shall we validate the label upon k8s label name convention in the VK? https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
3. How many labels can a node have? Shall we set a limit to the provider?

**Comment by rbitia** [comment]
We use taints to solve the same purpose. Is there a reason you would rather use labels?

**Comment by pires** [comment]
The `Provider` interface defines a func `ConfiguredNode` that the provider can use to handle the `Node` object before its registration. An example on how to use it is included in the `MockProvider`

https://github.com/virtual-kubelet/virtual-kubelet/blob/0d1f6f162509a9b4b73f1d23ac133541337545b0/cmd/virtual-kubelet/internal/provider/mock/mock.go#L346-L347

Another example is how `systemk` does it

https://github.com/virtual-kubelet/systemk/blob/b1e585c6fce0b9cd86d0f109997482e8f515e118/internal/provider/node.go#L33-L70
