### ISSUE TITLE
Building the release binary

### ISSUE THREAD

**Issue by sdanbury** [virtual-kubelet/virtual-kubelet#270]
I know the Makefile is probably good enough for most people at explaining how to get/build the binary, but could you respond, or add to the docs, steps on exactly the commands one would need to run to get the binary please?

Thanks!

**Comment by sdanbury** [comment]
I ran `make deps` and got the following error:

```
...
go get github.com/goreleaser/goreleaser
# github.com/goreleaser/nfpm/deb
../../go/src/github.com/goreleaser/nfpm/deb/deb.go:175:9: unknown field 'Format' in struct literal of type tar.Header
../../go/src/github.com/goreleaser/nfpm/deb/deb.go:256:9: unknown field 'Format' in struct literal of type tar.Header
../../go/src/github.com/goreleaser/nfpm/deb/deb.go:275:9: unknown field 'Format' in struct literal of type tar.Header
../../go/src/github.com/goreleaser/nfpm/deb/deb.go:292:10: unknown field 'Format' in struct literal of type tar.Header
make: *** [setup] Error 2
```

**Comment by robbiezhang** [comment]
https://github.com/goreleaser/goreleaser/issues/585
Try upgrade your go binary to 1.10+.

**Comment by robbiezhang** [comment]
`make build` will build out the binary in Linux.
You can also build the docker image by using the Dockerfile.
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/Dockerfile

**Comment by sdanbury** [comment]
Awesome, thanks for the mega quick response. The Dockerfile worked well, thanks.
