### ISSUE TITLE
Fargate Provider Does Not Appear to Set Environment Variables

### ISSUE THREAD

**Issue by stevenpall** [virtual-kubelet/virtual-kubelet#273]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
Fargate
Version (e.g. 0.1, 0.2-beta)
0.3
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AWS, self-hosted (kops)
Install Method (e.g. Helm Chart, )
Helm chart (testing https://github.com/virtual-kubelet/virtual-kubelet/pull/258#pullrequestreview-140047435)
### Issue Details
From what I can tell, pods that specify environment variables are not created correctly in Fargate. Here is a sample task definition (notice `Environment: []`):
```
2018/07/25 15:47:04 RegisterTaskDefinition err:<nil> output:{
  TaskDefinition: {
    Compatibilities: ["EC2","FARGATE"],
    ContainerDefinitions: [{
        Command: [],
        Cpu: 1024,
        Environment: [],
        Essential: true,
        Image: "redacted",
        LogConfiguration: {
          LogDriver: "awslogs",
          Options: {
            awslogs-group: "/ecs/first-run-task-definition",
            awslogs-region: "us-east-1",
            awslogs-stream-prefix: "redacted"
          }
        },
        Memory: 30720,
        MemoryReservation: 20480,
        MountPoints: [],
        Name: "redacted",
        PortMappings: [],
        VolumesFrom: []
      }],
    Cpu: "4096",
    ExecutionRoleArn: "arn:aws:iam::412825699923:role/ecsTaskExecutionRole",
    Family: "redacted",
    Memory: "30720",
    NetworkMode: "awsvpc",
    PlacementConstraints: [],
    RequiresAttributes: [
      {
        Name: "ecs.capability.execution-role-ecr-pull"
      },
      {
        Name: "com.amazonaws.ecs.capability.docker-remote-api.1.18"
      },
      {
        Name: "ecs.capability.task-eni"
      },
      {
        Name: "com.amazonaws.ecs.capability.ecr-auth"
      },
      {
        Name: "ecs.capability.execution-role-awslogs"
      },
      {
        Name: "com.amazonaws.ecs.capability.logging-driver.awslogs"
      },
      {
        Name: "com.amazonaws.ecs.capability.docker-remote-api.1.21"
      },
      {
        Name: "com.amazonaws.ecs.capability.docker-remote-api.1.19"
      }
    ],
    RequiresCompatibilities: ["FARGATE"],
    Revision: 1,
    Status: "ACTIVE",
    TaskDefinitionArn: "redacted,
    Volumes: []
  }
}
```
I would think this functionality should be implemented [here](https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/aws/fargate/container.go#L43), however it appears to be missing. #127 specified `Container name, image, command, args, port mappings, working dir and environment variables` as working, so I was expecting this to be fine.
### Repo Steps
Create a pod that specifies environment variables and use the Fargate provider.

**Comment by ofiliz** [comment]
@stevenpall Thanks for reporting. I will investigate.
