### ISSUE TITLE
Pods (Container Instances) not able to publish metrics

### ISSUE THREAD

**Issue by abizake** [virtual-kubelet/virtual-kubelet#279]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI

Version (e.g. 0.1, 0.2-beta)
AKS : 1.10.5
Vkubelet :- 1.8.3
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )
Helm and Install ACI connector
### Issue Details
I implemented the pod auto scale and below are the events from it
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedComputeMetricsReplicas  9m (x13 over 15m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedGetResourceMetric       2s (x31 over 15m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API

**Comment by rbitia** [comment]
We will have metrics enabled within the next week! Thanks

**Comment by abizake** [comment]
@rbitia Thanks for the update.

**Comment by cpuguy83** [comment]
This was completed in #306
