### ISSUE TITLE
GCP Provider?

### ISSUE THREAD

**Issue by EamonKeane** [virtual-kubelet/virtual-kubelet#28]
This looks very promising as 'serverless' without the limitations (lock-in, function duration, event-driven model, resource size flexibility, tooling) for batch jobs that are not latency sensitive.

Does anyone know if GCP plans to launch a container instance service? If they offered pre-emptible instances this could result in very low cost containers.

**Comment by rimusz** [comment]
for now preemptible container optimised OS with specified docker image could be used

**Comment by rbitia** [comment]
GCP doesn't have a "pods as a service" like product yet.. We will visit creating a provider once they do so closing this issue for now! Thanks!
