### ISSUE TITLE
[HELM] Can't access chart for helm w/ az aks install-connector

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#3]
Sometimes files aren't created when using helm. 

The error people get when using the command
'az aks install-connector -g <rg> -n <cluster name> --connector-name <name>
Error: file "https://github.com/Azure/aci-connector-k8s/raw/master/charts/aci-connector.tgz" not found

https://github.com/kubernetes/helm/issues/2071

Work around: 
‘helm init’
‘helm repo update’
 
Assuming you are on windows navigate to & make sure these files exist. 
“C:\Users\<user>\.helm\repository\local\index.yaml”
"C:\Users\<user>\.helm\repository\cache\local-index.yaml"

If the second file "C:\Users\<user>\.helm\repository\cache\local-index.yaml" doesn't exist copy the contents from the index.yaml file & make a new one with the added content.

**Comment by PatrickLang** [comment]
BTW - there are Windows paths in the original report but this can also happen on Linux.

1. Run `helm init` on one machine to get tiller running in your cluster
2. Go to another admin machine (Linux or Windows - doesn't matter), run `helm list` - it works
3. Try running `az aks install-connector ...` there. It will fail with the error:

```
Deploying the ACI connector for 'Windows' using Helm
Error: failed to download "https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/virtual-kubelet-for-aks-0.1.3.tgz"
```

*Workaround*
Run `helm init` on each machine first

**Comment by rbitia** [comment]
We need to try this on a new windows machine before we can close this issue.

**Comment by rbitia** [comment]
Stale issue, so closing for now.
