### ISSUE TITLE
getting logs from the vk node

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#300]
Could we enable "getting logs" from the node and it routes to the pod's logs?

**Comment by robbiezhang** [comment]
is there a corresponding `kubectl` command?

**Comment by smahalingam** [comment]
I am also seeing issue with getting POD logs 
<img width="2560" alt="screen shot 2018-08-10 at 18 05 16" src="https://user-images.githubusercontent.com/6057889/43971205-2141d9ce-9cc8-11e8-80b7-2b73fa8640dd.png">

**Comment by robbiezhang** [comment]
@smahalingam can you share the VK deployment spec? Seems like you've registered the VK node on "aci-connector" domain instead of an IP address.

**Comment by cpuguy83** [comment]
I ran into this same issue. Couldn't resolve it without rebuilding the cluster.
The annoying thing is both clusters were built identically from the same acs-engine template.

**Comment by srrengar** [comment]
@smahalingam @cpuguy83 are you still running into this?

**Comment by cpuguy83** [comment]
This was a one off occurrence, but I doubt it's fixed. Also I'm not sure if the issue is a VK issue or elsewhere.

**Comment by srrengar** [comment]
@DulebT can we try to repro this with ACI?

**Comment by srrengar** [comment]
Since this was a one off occurrence, I will close this and we can reopen if it resurfaces.
