### ISSUE TITLE
Kubernetes version of VK 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#304]
Maybe we could have VK's version align with K8s and test against that K8s version so we know the functionality is stable. This will make the version make more sense to customers.

**Comment by cpuguy83** [comment]
This can get quite hairy, especially since VK is not really a GA product yet (TMK).

**Comment by rbitia** [comment]
^ Probably not going to be inline for a GA release but let's talk about the pros and cons.

**Comment by rbitia** [comment]
Pipe the VK version to the kubelet version to expose it. Otherwise the virtual kubelet version should follow the current K8s version of the cluster.
