### ISSUE TITLE
Move to "official" releases

### ISSUE THREAD

**Issue by jeremyrickard** [virtual-kubelet/virtual-kubelet#314]
We should move to "official" releases that include:

* Tagged Docker Images
* Updated helm chart (instead of using :latest)
* Updated chart tgz per tag

**Comment by rbitia** [comment]
Question: Do we want to maintain a single VK image for a first time user experience even when we split out providers to their own github repos?
Providers would have to PR changes into VK core for a single release.

**Comment by rbitia** [comment]
Within 1.0 we can just provide github releases for the interface in Virtual-kubelet/virtual-kubelet and later we could provide an entire vk image of all providers integrated if we see interest.

**Comment by cpuguy83** [comment]
We do not plan to include a binary release for 1.0 and instead will depend on providers to build their own binaries.
