### ISSUE TITLE
Remove deprecated `taint` flag

### ISSUE THREAD

**Issue by jlegrone** [virtual-kubelet/virtual-kubelet#316]
This flag should be removed after external virtual-kubelet integrations have had time to update to the new taint key configuration method.

**Comment by jlegrone** [comment]
...and the winner is 5115c1e5cd00fdec15a8f46da6d29f0a98c453e5!

`git revert 5115c1e5cd00fdec15a8f46da6d29f0a98c453e5` should do the trick when the time comes.

**Comment by rbitia** [comment]
Check with @robbiezhang to see if we can close this guy.

**Comment by jlegrone** [comment]
@pires I believe this was related to https://github.com/virtual-kubelet/virtual-kubelet/issues/259 -- we discussed using an environment variable rather than the flag for setting a taint key. On the pull request that closed that issue, we decided not to remove the taint flag temporarily for backwards compatibility, and I think I filed this issue to track that work for later.

Relevant discussion from that PR:
https://github.com/virtual-kubelet/virtual-kubelet/pull/305#discussion_r208697757
https://github.com/virtual-kubelet/virtual-kubelet/pull/305#discussion_r210056329

cc @jeremyrickard

**Comment by cpuguy83** [comment]
fyi, discussed this today on the community sync and thought it better to keep the flag, reason being:

1) Removing it isn't really helping anything
2) Removing is however potentially breaking
3) In general we (on the call) prefer flags to env vars

**Comment by rbitia** [comment]
Closing!
