### ISSUE TITLE
Please provide IoT Edge/AWS Greengrass like virtual-kubelet

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#33]
I could see a few options for this

1) Take advantage of IoT Hub/Edge servers and device runtime and just implement a virutal-kubelet that takes advantage of it.  Since right now IoT Edge seems to not allow any arbitrary container but needs it to adhere to a specific module interface this might not be ideal.
2) Take advantage of AWS Greengrass, this has similar drawbacks to IoT Hub/Edge.
3) Create a new cloud service and device runtime just for this.

**Comment by erjadi** [comment]
Hi @AceHack , it seems an IoT Edge vk provider was released last week. See https://azure.microsoft.com/en-us/blog/manage-azure-iot-edge-deployments-with-kubernetes/

Haven't tried it out myself though, let us know your experiences if you have!

**Comment by rbitia** [comment]
Azure released the IoT-Edge provider! Closing for now. 😄 😸 👼
