### ISSUE TITLE
Be more flexible w/ mem and cpu limits

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#332]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI
Version (e.g. 0.1, 0.2-beta)
latest
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )
cli
### Issue Details
In pod specs people have to specify "G" rather than GB, Gi, or other units of measurement for memory. Can we try and translate the other units to G so users aren't throttled by ACI for VK repeatedly trying to create a pod. 

We should look into doing the same thing for CPU limits.

**Comment by robbiezhang** [comment]
I'll take a look, but ACI provider converts the memory and CPU usage to make sure it satisfy ACI requirements. Can you give me an example?

https://github.com/virtual-kubelet/virtual-kubelet/blob/bb8ba567e3a33c827e0ffa56755e3fdeabb9af53/providers/azure/aci.go#L713-L744

**Comment by rbitia** [comment]
Yea I couldn't repro the issue. Super strange. Let's keep an eye out for floating memory issues in the future but closing for now :)
