### ISSUE TITLE
Please create matrix of limitations

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#34]
I found this on the old project site.

Limitations:
ConfigMaps
Secrets
ServiceAccounts
Volumes
kubectl logs
kubectl exec

Please create a feature matrix that contains native real kubelet features, potential virtual-kubelet features as defined by the virtual-kubelet interface, then features for specific implementations.  This will help with tagging and taint so deployment can be scoped accordingly.

Thanks.

**Comment by AceHack** [comment]
Also when it comes to networking this is a good starting point, should be made first class in the documentation/limitations matrix.

https://github.com/virtual-kubelet/virtual-kubelet/issues/13

Would be nice to break it out by K8s names like ClusterIP, NodePort, LoadBalancer, Ingress, ExternalName, and ClusterIP=None

https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

Thanks.

**Comment by rbitia** [comment]
Working on this! Thanks! :)

**Comment by rbitia** [comment]
#37

**Comment by AceHack** [comment]
@rbitia This is a great start.  It would be great to get this broken out by a provider like the Pure Interface Limitations, Azure Limitation, Hyper.sh Limitation.

Also under limitations, don't specifically point out volume limitation, you point out what volume types you support but not which ones you don't support.

Also getting the networking piece added would be very helpful as well.

Specifically, I'm looking for much more information on what is not supported.

Thanks.

**Comment by rbitia** [comment]
Gotcha thank you for the feedback! Work in progress

**Comment by rbitia** [comment]
I'll create a PR for this with a matrix with the providers we support.

**Comment by rbitia** [comment]
Document functionality that virtual kubelet provides and then mention what the provider needs to do to support the following.

**Comment by rbitia** [comment]
#238

**Comment by rbitia** [comment]
Closing for now because we actually think it's up to the providers to provide what their limitations are.

**Comment by ffledgling** [comment]
@rbitia I see a family of issues asking for more clarity around the feature set (cluster networking, filesystem, liveliness/readiness probe etc) supported by VK closed with "up to the individual providers".

Would it be possible to have the limitations documented for the Azure Container Interface at least, or a different mock matrix of limitations that can be used a reference for what axes/parameters should even exist in such a matrix? The lack of *any* defined minimum features from the provider seems to be a little troublesome.

At face value, it makes sense that VK would enforce a bare-minimum required feature set for some cross compatibility across VK providers and then have a list of useful, but optional features for them to implement. Is there a technical/design reason that was specifically ruled out?

**Comment by AceHack** [comment]
@ffledgling +1million

**Comment by abhideodhar-coder** [comment]
yes - this is required ... +1
