### ISSUE TITLE
Love this project, but how do I install it?

### ISSUE THREAD

**Issue by atrauzzi** [virtual-kubelet/virtual-kubelet#347]
Would love to see more detailed installation steps.  Bonus points for MSI+chocolatey on Windows, ppa on Ubuntu and homebrew for macOS!

❤️

**Comment by rbitia** [comment]
Hey Alexander! Do you want to use Virtual Kubelet with a Kubernetes cluster? If so where is the k8 cluster running?

**Comment by rbitia** [comment]
@pires I don't think we need this for 1.0.

**Comment by pires** [comment]
@rbitia I just think it should be made clear in the docs whether these are the type of installs supported or not.

**Comment by pires** [comment]
This no longer makes sense as the VK is now a lib and not a runnable daemon that users can use. Each provider will now provide its own binaries and respective instructions.
