### ISSUE TITLE
Refactor Go API interfaces

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#348]
In light of https://github.com/virtual-kubelet/virtual-kubelet/issues/160 (making VK a library)

I wanted to propose some changes to the (go) API surface:

1. Make a clean split between services provided by virtual-kubelet
i. Examples of the mentioned services: a daemon, a control loop, HTTP API routers for exec, logs, and metrics
ii. e.g., the vkubelet package should not be automatically starting up an HTTP server but instead rely on the implementation (e.g cmd/) to handle this.
iii. Do not depend on environment variables except in the actual CLI, and pass down the values of these as arguments to functions that need them 
2. Define stronger error types
i. Components should be able to determine what kinds of errors have been returned
ii. Think along the lines of GRPC error codes
iii. e.g., a Provider should be able to return an error that is a "not found' type of error and the HTTP router should be able to understand it.
iv. I have an example of this in https://github.com/cpuguy83/strongerrors, which is essentially what is used in moby (see https://godoc.org/github.com/moby/moby/errdefs)
3. Setup tracing/metrics which are propagated to all components and any potential consumers of the Go API.
i. I've been playing with OpenCencus for this as it is trivial to write exporters for whatever system the consumer wants to use (rather than enforcing a common library that must be used for any consumer).... but I'm not necessarily tied to it

Most of this is just improving the code hygiene and having a cleaner separation of responsibilities.
Right now most of this code base is assuming it's just a binary that's being run in a particular way.
The idea here is to have a framework for building a kubelet implementation, and `cmd/virtual-kubelet` would continue to provide that implementation.

All in all, this should not introduce any breaking changes to the daemon, installation methods, or anything of that nature.
This repo can still provide a daemon with all the available providers packaged up as it does today, but in addition it will make it easier to develop a custom VK daemon for providers (whether or not they exist in the repo today or not) to do their own thing.
Actually making any sort of breaking change with regard to the distribution of a daemon is a wholly separate topic.

**Comment by cpuguy83** [comment]
ping @jeremyrickard @rbitia @robbiezhang

**Comment by pires** [comment]
@cpuguy83 what is holding this back?

**Comment by cpuguy83** [comment]
Just a status update on this.
Still working on re-doing some of the provider interfaces

- #578 (exec)
- #574 (log streaming)

After these, the other big thing is defining a strong error interface between providers and the core.
The split between the core framework and the built-in CLI/daemon implementation is complete.
Metrics still need to be defined and implemented.

**Comment by cpuguy83** [comment]
This is done.
