### ISSUE TITLE
[ACI] Volume Mounts in Windows fails

### ISSUE THREAD

**Issue by jmajoor** [virtual-kubelet/virtual-kubelet#367]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI
Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )

### Issue Details
I have tried several ways to get a volume mounted, but without success.
For example a configMaps mount:
volumeMounts:
    - name: config
      mountPath: "c:/Config"
volumes:
  - name: config
    configMap:
      name: sl-config

This didn't work with the following error:
Reason:       ProviderFailed
Message:      api call to https://management.azure.com/subscriptions/xx/resourceGroups
//providers/Microsoft.ContainerInstance/containerGroups/default?api-v
ersion=2018-09-01: got HTTP response status code 400 error code "InvalidVolumeMountPath": The volume mount path 'c:/Config' in container 'smarts' is invalid. It can't contain ':'.

This is a windows container, so why is ':' an invalid character.

Using /Config instead of c:/Config result in:
HTTP response status code 400 error code "VolumesNotFound": Volumes 'Config' in container 'mypod
'are not found.

Tried a Azure File mount (as ACI supports that).
However that result into:
got HTTP response status code 400 error code "WindowsContainersVolumeNotSupported": Azure file volumes are not supported for Windows containers. 

So I guess this is an ACI limitation, but couldn't find any documentation on this

Tried an PersistentVolumeClaim on a managed disk, but that results in:
Reason:       ProviderFailed
Pod mypod requires volume my-storage which is of an unsupported type

Any help is appreciated.

**Comment by robbiezhang** [comment]
It's ACI constraints. Basically, Windows container doesn't support any volume mount.
Here are the public docs about the Windows constraints:
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-secret
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quotas

**Comment by robbiezhang** [comment]
PV and PVC is not supported by virtual-kubelet.

Can you try to use the secret environment variable to work around your case? 
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-environment-variables

If you want to mount an Azure file share into your Windows container, you can workaround it by override the start command to run ` net use I: \\\\<storage_account>.file.core.windows.net\\<file_share> /u:<storage_account> <storage_key>` to mount the file share when the container is started.

**Comment by jmajoor** [comment]
If PV and PVC were supported by virtual-kubelet then I would still have the issue that for windows containers you can't mount that in ACI. Or will this also work for windows containers?

I have tried secrets and config maps through environment variables, which works for some of my variables but I also have a file that I need to pass in (hence the config map as a volume). Passing the content of that file as an environment variable value didn't work. Not sure it is too long or whether it contains characters that aren't allowed. (May try a base64 of the content)

In addition to configuration information I also need persistent data, so I think I need PVC.

To work with AKS and windows containers I have to use virtual-kubelet. But virtual kubelet is ACI and therefore I can't have windows containers that require persistent data.

**Comment by robbiezhang** [comment]
Did you try to use the Azure file share by using `net use` in your container? It should work for your persistent data requirement. Not a k8s way, but should work around.

**Comment by jmajoor** [comment]
As you mentioned that is really not the k8s way. Sure creating a net share like that will work, but then I have to make the entire command configurable through container environment variables, make sure that each instance has its own data and I need to change my app which currently looks in the "data" directory which may or may not be a mount. May also have problems with latency on a file share as well. The thing is we have some stateless containers and for this ACI and virtual-kubelet is great, but we also have a stateful container which needs to persist data.  

Am I correct in assuming that even if you were to support PV/PVC that this still wouldn't be possible for windows containers?

**Comment by robbiezhang** [comment]
Yes, that's a constraint from ACI Windows container, and also from k8s.

**Comment by robbiezhang** [comment]
I mean k8s WIndows. https://kubernetes.io/docs/getting-started-guides/windows/#volumes

**Comment by jmajoor** [comment]
Ok, thanks for all the information. Looks like windows containers remain the underdog.  I guess there is nothing that can be done until Azure takes windows containers seriously (sad). We can probably close this issue other than it being a request to support PV/PVC.

**Comment by srrengar** [comment]
Closing this based on the discussion. Will add docs around this when it's supported

**Comment by poochwashere** [comment]
Is PVC,PV now supported for Linux containers running on an AKS Virtual Node?

**Comment by deepaksood619** [comment]
+1 for PVC and PV in Linux AKS Virtual Node. Also is there a workaround for sharing AzureFile PVC between ACI and AKS

**Comment by erewok** [comment]
We would love to be able to mount persistent volumes in AKS Virtual Node because we are using Keyvault Flexvol in all of our projects. Without being able to mount volumes, we *can't* use virtual-node.

**Comment by ameyaagashe** [comment]
Is there support for Persistent Storage for Virtual Nodes or atleast if we can have a roadmap when it would be available?
