### ISSUE TITLE
aci-helloworld linux get status ProviderFailed 

### ISSUE THREAD

**Issue by benzhi2011** [virtual-kubelet/virtual-kubelet#383]
---

### Environment summary

Provider AWS

Version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

K8s Master Info
AKS

Install Method
az aks install-connector 
 
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

### Issue Details
I followed the doc [here ](https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet). I created two virtual containers one for linux and one for windows.

### kubectl get pods -o wide
NAME                                                              READY     STATUS           RESTARTS   AGE       IP            NODE
aci-helloworld-59d9b67c59-zn8lm                                   0/1       ProviderFailed   0          19s       <none>        virtual-kubelet-virtual-kubelet-linux-westeurope
virtual-kubelet-linux-westeurope-virtual-kubelet-for-aks-62tplw   1/1       Running          87         2d        10.244.0.15   aks-agentpool-27326293-0
virtual-kubelet-windows-westeurope-virtual-kubelet-for-aksx7kqk   1/1       Running          88         2d        10.244.0.14   aks-agentpool-27326293-0

### Repo Steps
follow [this](https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet)

**Comment by robbiezhang** [comment]
@benzhi2011 can you run `kubectl describe po` on your pod and paste the result here?

**Comment by benzhi2011** [comment]
@robbiezhang I created a new AKS this morning and Virtual Kubelet seems working fine.
