### ISSUE TITLE
Deploying private Windows image from ACR

### ISSUE THREAD

**Issue by HannoSolo** [virtual-kubelet/virtual-kubelet#385]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
AKS

Version (e.g. 0.1, 0.2-beta)
1.11.3

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS

Install Method (e.g. Helm Chart, )

### Issue Details
After creating the windows Virtual kubelet node I try to deploy a windows sample image from ACR and when looking at the pods it shows "Provider Failed".

If I describe the pod I see this:
C:\Users\v-hater\AKS\dotnet-docker\samples\aspnetapp>kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                                              READY     STATUS           RESTARTS   AGE       IP            NODE
default       aci-helloworld-d75cf666c-lvgxg                                    0/1       Pending          0          11m       <none>        <none>
default       aspnetapp-7fc6d8fd6b-p9jcm                                        0/1       ProviderFailed   0          51s       <none>        virtual-kubelet-virtual-kubelet-windows-eastus
default       azure-vote-back-f9cc849fb-bprrd                                   1/1       Running          1          4d        10.244.0.46   aks-agentpool-33920650-0
default       azure-vote-front-67574b556c-qfhpj                                 1/1       Running          1          4d        10.244.0.50   aks-agentpool-33920650-0
default       virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-675ldscr   1/1       Running          0          12m       10.244.0.58   aks-agentpool-33920650-0
kube-system   heapster-7b74498c4b-2grbp                                         2/2       Running          2          4d        10.244.0.51   aks-agentpool-33920650-0
kube-system   kube-dns-v20-668899dbdc-75rhf                                     3/3       Running          3          4d        10.244.0.42   aks-agentpool-33920650-0
kube-system   kube-dns-v20-668899dbdc-b7rgm                                     3/3       Running          3          4d        10.244.0.43   aks-agentpool-33920650-0
kube-system   kube-proxy-29f8z                                                  1/1       Running          1          4d        10.240.0.4    aks-agentpool-33920650-0
kube-system   kube-svc-redirect-nxbcf                                           2/2       Running          2          4d        10.240.0.4    aks-agentpool-33920650-0
kube-system   kubernetes-dashboard-55c64b9ddb-45dps                             1/1       Running          4          4d        10.244.0.49   aks-agentpool-33920650-0
kube-system   metrics-server-76f76c6bfd-fhzw6                                   1/1       Running          2          4d        10.244.0.48   aks-agentpool-33920650-0
kube-system   tiller-deploy-759cb9df9-kz4mf                                     1/1       Running          1          4d        10.244.0.52   aks-agentpool-33920650-0
kube-system   tunnelfront-7879bbf5f5-vndg2                                      1/1       Running          1          4d        10.244.0.45   aks-agentpool-33920650-0

C:\Users\v-hater\AKS\dotnet-docker\samples\aspnetapp>kubectl describe pod aspnetapp-7fc6d8fd6b-p9jcm
Name:               aspnetapp-7fc6d8fd6b-p9jcm
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               virtual-kubelet-virtual-kubelet-windows-eastus/
Labels:             app=aspnetapp
                    pod-template-hash=3972849826
Annotations:        <none>
Status:             Pending
Reason:             ProviderFailed
Message:            api call to https://management.azure.com/subscriptions/ce1ba766-26d0-4cc5-bca6-ccaae1c275b7/resourceGroups/AKSrg/providers/Microsoft.ContainerInstance/containerGroups/default-aspnetapp-7fc6d8fd6b-p9jcm?api-version=2018-09-01: got HTTP response status code 400 error code "InaccessibleImage": The image 'hannocreg.azurecr.io/aspnetapp:v1' in container group 'default-aspnetapp-7fc6d8fd6b-p9jcm' is not accessible. Please check the image and registry credential.
IP:
Controlled By:      ReplicaSet/aspnetapp-7fc6d8fd6b
Containers:
  aspnetapp:
    Image:        hannocreg.azurecr.io/aspnetapp:v1
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-d5j6j (ro)
Conditions:
  Type           Status
  PodScheduled   True
Volumes:
  default-token-d5j6j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-d5j6j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=virtual-kubelet-virtual-kubelet-windows-eastus
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 virtual-kubelet.io/provider=azure:NoSchedule
Events:
  Type     Reason            Age              From               Message
  ----     ------            ----             ----               -------
  Warning  FailedScheduling  1m (x3 over 1m)  default-scheduler  0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had unavailable network.
  Normal   Scheduled         1m               default-scheduler  Successfully assigned default/aspnetapp-7fc6d8fd6b-p9jcm to virtual-kubelet-virtual-kubelet-windows-eastus

Why is it not able to pull my image from ACR?

**Comment by robbiezhang** [comment]
@HannoSolo did you include the private ACR secret in the imagePullSecrets in the pod spec? I didn't see it in the `kubectl describe pod` result. Please double check your pod spec.
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token
https://kubernetes.io/docs/concepts/containers/images/#using-azure-container-registry-acr

**Comment by HannoSolo** [comment]
@robbiezhang Thanks Robbie I will check out those links you provided, I figured that's what I needed to do just didn't know how.

**Comment by HannoSolo** [comment]
@robbiezhang Got it working with the instructions you provided, thanks a bunch!
