### ISSUE TITLE
Cannot deploy an ACI container from ACR to non-default namespace

### ISSUE THREAD

**Issue by ai2admin** [virtual-kubelet/virtual-kubelet#386]
---

### Environment summary

Provider: ACI

K8s Master Info: AKS

Install Method: Helm Chart

### Issue Details

If my deployment spec creates a pod in a non-default namespace, I can still use **imagePullSecrets** for a secret defined in the default namespace.

However, if I do the same deployment selecting a virtual-kubelet node, the deployment fails:

time="2018-10-24T13:07:10Z" level=error msg="Failed to create pod" error="secrets \"my-secret\" not found" namespace=my-namespace node=virtual-kubelet-virtual-kubelet-windows-eastus operatingSystem=Windows pod=my-server-574d68478c-gsvzx provider=azure 

Note that "my-secret" is defined in the default namespace.

I can keep creating the ACR secret for every namespace I add, but:
- it's a poorly scalable solution in case the namespaces are created dynamically. 
- it breaks back-compatibility with deployments to regular nodes
- it breaks security (e.g. I don't want to expose the ACR secret to the namespace)

### Repo Steps

- Create AKS cluster
- Install helm
- Install virtual-kubelet with ACI connector
- Create an Azure Container Registry
- Deploy a container to the ACR
- Create a kubernetes.io/dockerconfigjson secret for the ACR in the k8s default namespace 
- Create my-namespace
- Deploy a pod for the ACR container to "my-namespace" in the cluster node by referencing the secret - operation succeeds
- Deploy a pod for the ACR container to "my-namespace" in the ACI via virtual-kubelet by referencing the same secret - operation fails, the secret is not found.

The only difference in the YAML for the last two steps is adding the nodeSelector for the virtual-kubelet

**Comment by robbiezhang** [comment]
Looks similar to #192. According to the [k8s document](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod)
"Pods can only reference image pull secrets in their own namespace, so this process needs to be done one time per namespace."

So, I doubt it uses the secret in the default namespace in your cluster node case.
@ai2admin did you grant the AKS service principal reader permission on the ACR?

**Comment by ai2admin** [comment]
@robbiezhang : you are right, apparently it's the principal reader permissions that are used for the k8s own nodes, so the issue indeed boils down to #192

**Comment by robbiezhang** [comment]
close as a dupe
