### ISSUE TITLE
Writing back information to a pod

### ISSUE THREAD

**Issue by Raffo** [virtual-kubelet/virtual-kubelet#39]
Maybe I'm too dumb to figure it out, but it looks like that the current implementation of virtual-kubelet does not allow us to use the Pod to write some information that could ease the mapping between a Pod in Kubernetes land and the resource in the provider. 
I would envision storing some annotation to actually make the mapping between the two different system much easier (i.e. the ARN of a task in AWS ECS to have a 1:1 mapping with a Pod). 
Is this possible as of today and, if not, what do you think about this idea?

**Comment by robbiezhang** [comment]
@Raffo, thanks for the feedback. The annotation is a good use case. @erikstmartin, thoughts?

**Comment by rbitia** [comment]
We might use this for pooling resources.
