### ISSUE TITLE
Startup takes a LONG time when pods already exist

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#397]
When pods already exist that VK needs to handle, VK startup takes a long time because each pod ends up getting deleting and recreated with only a single goroutine.

**Comment by rbitia** [comment]
@cpuguy83 can you explain what you mean by this issue? What are you doing to get this behavior?

**Comment by cpuguy83** [comment]
I mean the reconciler that runs on VK startup is reconciling all pods sequentially.

When VK has been down and you bring it back up all the pods that were running are deleted by kubernetes since it didn't get a status update from VK, so all the pods must be deleted in ACI.

With this happening sequentially it takes a very long time when there are more than just a couple of pods.

**Comment by cpuguy83** [comment]
This is fixed now that reconciliation is done in parallel for each pod.
