### ISSUE TITLE
kubectl describe : Not working, dashboard showing blank values for CPU usage for virtual kubernetes cluster

### ISSUE THREAD

**Issue by AfreenShaha** [virtual-kubelet/virtual-kubelet#408]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )
Helm
### Issue Details
Issue No : 1:
>kubectl describe XXXXXXXXX
ABOVE COMMAND GIVES BELOW RESPONSE: even though "kubectl get pods -o wide" returns this pod
error: the server doesn't have a resource type "XXXXXXXXX"
Note: we are using the virtual kubernetes pod

Issue No: 2:
CPU details are coming as blank even on portal:
![image](https://user-images.githubusercontent.com/15724133/48337983-7b1a5a00-e68a-11e8-85d4-10d422c4e899.png)

Here is the yaml used from this link: https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanoserver-iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanoserver-iis
  template:
    metadata:
      labels:
        app: nanoserver-iis
    spec:
      containers:
      - name: nanoserver-iis
        image: microsoft/iis:nanoserver
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: windows
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule

**Comment by AfreenShaha** [comment]
thanks @robbiezhang

**Comment by csor-dev** [comment]
@rbitia I think we can close this issue

**Comment by lachie83** [comment]
This can be closed.
