### ISSUE TITLE
Rethink pod introspection provider APIs

### ISSUE THREAD

**Issue by asrivas-vmw** [virtual-kubelet/virtual-kubelet#423]
Currently, the way we deal with Exec and Logs in the VK is a little too opinionated and might not work as generically as providers would like it to. VK makes the assumption that the provider should not deal with the SPDY protocol options as it chooses,  and tries to parse these before calling into the provider. Instead, VK should just be a thin abstraction layer that proxies the HTTP requests directly to the provider and allow the provider to deal with these options as it chooses. 

More concretely, the `ExecInContainer` provider interface would be more generic in this form:
`ExecInContainer(w http.ResponseWriter, req *http.Request)` 
instead of
`ExecInContainer(name string, uid types.UID, container string, cmd []string, in io.Reader, out, err io.WriteCloser, tty bool, resize <-chan remotecommand.TerminalSize, timeout time.Duration) error`

This applies to the GetContainerLogs interface as well, which can simply be of this form:
`GetLogs(w http.ResponseWriter, req *http.Request)`
as opposed to
`GetContainerLogs(ctx context.Context, namespace, podName, containerName string, tail int) (string, error)`

This is in line with the general philosophy of VK to be a simple abstraction and let the heavy lifting be done in the vendor specific providers. It also makes us a bit more future proof to changes that K8s might make to the SPDY protocol options used within exec / attach / portforward. `Attach` and `PortForward` could also be implemented in a similar fashion.

**Comment by cpuguy83** [comment]
So I do not agree with passing through the raw http objects to the provider, this is a breakdown of the interface.
VK needs to provide strong API guarantees to the client that should not be up to the provider to implement as it sees fit.

What kinds of things are you wanting to do in the provider with these streams?

**Comment by asrivas-vmw** [comment]
> So I do not agree with passing through the raw http objects to the provider, this is a breakdown of the interface.

Sure, that was just an example; we need not expose raw HTTP requests if there are better abstractions that we can use.

> VK needs to provide strong API guarantees to the client that should not be up to the provider to implement as it sees fit.
> 
> What kinds of things are you wanting to do in the provider with these streams?

Parts of our provider are not in process and this would allow us to proxy the standard input output streams for these commands from another endpoint, kind of similar to what the CRI (Container Runtime Interface) allows for. We don't need to get hung up on the specifics of the interface for the purposes of this discussion, but we found that raw HTTP headers served our purpose pretty well. The provider can route those requests as it pleases to any remote entity or handle them itself, providing for much greater flexibility overall.

**Comment by erjadi** [comment]
Hi @asrivas-vmw thanks for a thoughtful message on exec in VK, I actually originally implemented it in VK and the Azure provider so I read your comment with great interest.

The questions you raise are indeed valid points that actually crossed my mind when I did the first implementation, my original version was too provider specific in the VK interface and although I think the current version is workable (implementable) I agree it's not as clean as I would have liked it.

In the end different people prefer different things: I've read comments as well that the exec interface is too complicated, see https://github.com/virtual-kubelet/virtual-kubelet/issues/413#issuecomment-440458329. Having to handle protocol selection and SPDY/WS session establishment from Kubernetes would not simplify things.

Moreover, I may be mistaken but my guess would be that every provider would write similar/the same code to handle the SPDY/WS protocols which would point to it being more at home in VK code. Did you have any use case for the http responses/requests that you would want to implement?

One thing though:

> This is in line with the general philosophy of VK to be a simple abstraction and let the heavy lifting be done in the vendor specific providers. It also makes us a bit more future proof to changes that K8s might make to the SPDY protocol options used within exec / attach / portforward.

Wouldn't the current implementation be futureproof since it's referencing remotecommand from K8s?

**Comment by cpuguy83** [comment]
@asrivas-vmw I think the best approach here may be to build a custom VK implementation, which is the direction I'm really wanting to take here.

Note that currently the API server is built at the daemon level... and in fact most things are, this would allow supplying a custom handler for Exec or any other endpoint.

The provider interface itself, I think, should be as simple as possible for this, e.g.

```go
type AttachIO interface {
    Stdin()  io.Reader
    Stdout() io.WriteCloser
    Stderr() io.WriteCloser
}

type Provider interface {
    ...
    Exec(ns, pod, command string, io AttachIO) error
    ...
}
```

Or possibly something like this:

```go
type PodIO interface {
     Stdin()  io.WriterCloser
     Stdout() io.Reader
     Stderr() io.Reader
}

type Provider interface {
    ...
    Exec(ns, pod, command string) (PodIO, error)
    ...
}
```

Negotiating streams at the provider level complicates things quite a bit.
I would definitely like to see how we can support what you need, just wary of exposing transport semantics to the provider.

**Comment by cpuguy83** [comment]
Just to document our discussion:

The HTTP server is setup in such a way that you can take it or leave it. In this case VK is just taking the HTTP request and passing things to the provider.

With splitting out the providers we expect to have each provider build their own daemon CLI's that would choose to use the built-in HTTP handlers or not.

I think the best approach is to just provide your own HTTP handler in this case.

**Comment by asrivas-vmw** [comment]
Makes sense @cpuguy83. The Runtime API abstractions proposed in #520 should work for us.
