### ISSUE TITLE
Feature: use node Lease API

### ISSUE THREAD

**Issue by pires** [virtual-kubelet/virtual-kubelet#427]
In versions of Kubernetes prior to 1.13, `NodeStatus` is the heartbeat from the `Node`.

Kubernetes 1.13 introduces the node-leases, a lighter, more scalable heartbeat indicator. Node leases are renewed frequently while NodeStatus is reported from node to master only when there is some change or enough time has passed.

More on this Kubernetes feature: https://github.com/kubernetes/enhancements/issues/589

**Comment by rbitia** [comment]
#526
