### ISSUE TITLE
Should I use virtual-kubelet-for-aks or virtual-kubelet chart?

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#434]
It's not clear the difference or what one I should use.  Thanks.

**Comment by cpuguy83** [comment]
I believe the normal one will work just fine as long as you set the "targetAKS" when running on an aka cluster.

**Comment by AceHack** [comment]
@cpuguy83 why are there 2 then?  Also, why was the virtual-kubelet-for-aks last updated more recently if virtual-kubelet is the correct one to use?

**Comment by cpuguy83** [comment]
History and maintaining both.
