### ISSUE TITLE
virtual-kubelet with custom vnet failed

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#435]
I'm getting the following error inside the container logs in kubernetes.

Internal error occurred: error getting container logs?): api call to https://management.azure.com/subscriptions/xxx/resourceGroups/MC_rgp-use-arch-aks_aks-use-arch-dev_eastus/providers/Microsoft.ContainerInstance/containerGroups/kayaks-helloworld-linux?api-version=2018-09-01: got HTTP response status code 404 error code "ResourceNotFound": The Resource 'Microsoft.ContainerInstance/containerGroups/kayaks-helloworld-linux' under resource group 'MC_rgp-use-arch-aks_aks-use-arch-dev_eastus' was not found.

**Comment by rbitia** [comment]
Hey @AceHack how did you install the virtual kubelet? Can you also paste your pod spec here? And logs from the virtual kubelet pod, which is probably in the kube-system namespace.

**Comment by AceHack** [comment]
virtual kubelet is in default.

operatingSystem=Linux provider=azure 
time="2018-12-04T22:00:36Z" level=info msg="starting workers" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:00:36Z" level=info msg="started workers" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:29Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:29Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:29Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:30Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:30Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:30Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:31Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:32Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:33Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:36Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:41Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:17:52Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:18:12Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:18:54Z" level=warning msg="requeuing \"kayaks/helloworld-linux\" due to failed sync" namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure 
time="2018-12-04T22:19:12Z" level=error msg="Internal server error on request" error="error getting container logs?): api call to https://management.azure.com/subscriptions/774ccef4-d6ef-4146-a286-07226d1f9a1e/resourceGroups/MC_rgp-use-arch-aks_aks-use-arch-dev_eastus/providers/Microsoft.ContainerInstance/containerGroups/kayaks-helloworld-linux?api-version=2018-09-01: got HTTP response status code 404 error code \"ResourceNotFound\": The Resource 'Microsoft.ContainerInstance/containerGroups/kayaks-helloworld-linux' under resource group 'MC_rgp-use-arch-aks_aks-use-arch-dev_eastus' was not found." httpStatusCode=500 namespace= node=virtual-kubelet-linux operatingSystem=Linux provider=azure uri="/containerLogs/kayaks/helloworld-linux/helloworld?tailLines=5000&timestamps=true" vars="map[]"

**Comment by AceHack** [comment]
apiVersion: v1
kind: Pod
metadata:
  name: helloworld-linux
spec:
  containers:
  - image: microsoft/aci-helloworld
    imagePullPolicy: Always
    name: helloworld
    resources:
      requests:
        memory: "250Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule

**Comment by AceHack** [comment]
So I made the following modification to my manifest because my resource limits apparently were too small.

```
    resources:
      requests:
        memory: 1G
        cpu: 1
```

And now in the virtual kubelet logs I see

`time="2018-12-05T18:50:53Z" level=info msg="Pod created" namespace=default node=virtual-kubelet-linux operatingSystem=Linux pod=helloworld-linux provider=azure`

Nothing in the pod logs, it stays stuck in Waiting: Creating

In my MC_rgp-use-arch-aks_aks-use-arch-dev_eastus resource group, I see default-helloworld-linux aci created but it stays in a pending state for a very long time and then eventually goes to Failed.  I don't see any logs on why it failed. Is there somewhere else I can look for logs or do you have any insight?  Thanks.

**Comment by AceHack** [comment]
FYI these are the instructions I followed.
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md#create-an-aks-cluster-with-vnet

**Comment by AceHack** [comment]
I re-built my cluster and things are now working.

**Comment by AceHack** [comment]
Any way you can re-open this.  I'm getting the same issue now but using a windows virtual kubelet.  The linux one is working fine in the same cluster.  Thanks.

**Comment by jluk** [comment]
@AceHack not sure if you tried to setup Windows VK behind a VNET, but windows containers in ACI don't yet support VNETs so those windows vnet injection scenarios are expected to fail today. You should be able to provision non-vnet enabled windows container through VK though (abiding by the ACI Windows constraints (no mounts/pods/metrics, only WS2016 support, etc.).

**Comment by AceHack** [comment]
@jluk Thanks.
