### ISSUE TITLE
default service account's image pull secret does not work

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#442]
In our cluster our default service account is an image pull secret so each deployment does not have to specify it.  This does not work with virtual kubelet.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by pires** [comment]
Same as #441, mounting service account token (a SecretVolumeSource injected automatically) is the responsibility of the provider, not the VK.
