### ISSUE TITLE
Virtual kubelet to connect Kubernetes in docker with service fabric cluster on premise

### ISSUE THREAD

**Issue by VenkateshSrini** [virtual-kubelet/virtual-kubelet#449]
Hi All,
I know my ask is slightly obligue. I have service fabric cluster running on my local machine. I also have a docker with Kubernetes enabled. I want to register Kubernetes on docker or mini-kube with Service fabric using virtual kubelet. Can this be done? My machine is Windows 10 Pro

**Comment by dkkapur** [comment]
Hi - this can't be done at the moment, we don't have a VK provider for service fabric clusters yet. We have one for Mesh but that will not apply to a vanilla local cluster deployment or to a cluster on-prem / in Azure yet.

**Comment by pires** [comment]
Thanks, @dkkapur!
