### ISSUE TITLE
Clean up daemon CLI initialization

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#453]
The way the daemon CLI is created is becoming a huge problem for readability and maintainability.

It would be great to carry the work from https://github.com/virtual-kubelet/virtual-kubelet/pull/201 and clean this all up.

**Comment by pires** [comment]
This is relateed to #348.

**Comment by rbitia** [comment]
We don't need this in 1.0 since we are splitting providers from core.
