### ISSUE TITLE
AKS Connector KubeDNS Resolution and Service IP resolution is not working

### ISSUE THREAD

**Issue by xtophs** [virtual-kubelet/virtual-kubelet#456]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS

Install Method (e.g. Helm Chart, )
Helm Chart 0.5.0

### Issue Details
Resolution of DNS names for services running in the cluster is not running working from containers running in ACI.

A service `hostname` is deployed on a regular node in the cluster. The hello world pod is running in ACI using Virtual Kubelet
```
$ kubectl get pods -o wide
NAME                                               READY     STATUS    RESTARTS   AGE       IP            NODE                       NOMINATED NODE
dnstest2                                           1/1       Running   0          24m       10.241.0.4    virtual-kubelet            <none>
helloworld                                         1/1       Running   0          1h        10.241.0.5    virtual-kubelet            <none>
hostname-bslnp                                     1/1       Running   0          57m       10.240.0.9    aks-nodepool1-10876453-0   <none>
virtual-kubelet-virtual-kubelet-5cfc87c4cc-lscmm   1/1       Running   1          1h        10.240.0.28   aks-nodepool1-10876453-0   <none>
$ kubectl get svc
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
hostname     LoadBalancer   10.0.154.208   168.61.22.75   8000:30592/TCP   52m
kubernetes   ClusterIP      10.0.0.1       <none>         443/TCP          1h
```

From a shell running within the hello world pod (i.e. in ACI), **I can reach the hostname pod via IP address:**
```
# wget 10.240.0.9:8000
Connecting to 10.240.0.9:8000 (10.240.0.9:8000)
index.html           100% |*******************************************************************************|   280   0:00:00 ETA
```

**I cannot access the hostname pod via the hostname service, nor through the service IP:**
```
# wget hostname:8000
wget: bad address 'hostname:8000'

# wget hostname.default.svc.cluster.local:8000
wget: bad address 'hostname.default.svc.cluster.local:8000'

# wget 10.0.154.208:8000
Connecting to 10.0.154.208:8000 (10.0.154.208:8000)
```

** `/etc/resolv.conf` looks in complete**
```
# cat /etc/resolv.conf
nameserver 10.0.0.10
search
```

compared to containers running on regular nodes search order is missing.
```
# cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local q10ri0tyke2utfyjke44youebd.dx.internal.cloudapp.net
options ndots:5
```

I tried with `dnsPolicy` set to `Default` and `ClusterFirst`. `resolve.conf` looks different, but name resolution doesn't work in either case.

When trying a different container that has `dig` and `nslookup` installed I get errors for DNS resolution when running a Virtual Kubelet pod:

```
# dig
dig: parse of /etc/resolv.conf failed
# nslookup
nslookup: parse of /etc/resolv.conf failed
# cat /etc/resolv.conf
nameserver 10.0.0.10
search
```

Unfortunately, I don't seem to able to modify /etc/resolv.conf to troubleshoot further.
```
# echo nameserver 10.0.0.10 > /etc/resolv.conf
bash: /etc/resolv.conf: Read-only file system

# mount
[...]
/dev/sda1 on /etc/resolv.conf type ext4 (ro,relatime,discard,data=ordered)
``` 

### Repro Steps
- Clone setup: `git clone https://github.com/xtophs/aks-vkubelet-burst`
- Run `deploy.sh`
- deploy the dnstest pod: `kubectl create -f dns-test.clusterfirst.yaml`
- From within the dnstest container, run `dig` or `nslookup` 
- notice errors
- deploy a service onto a regular cluster node, e.g. 'kubectl create -f GitHub.com/oguzpatermaci/hostname/kubernetes-example/hostname-rs.yaml` and `kubectl create -f GitHub.com/oguzpatermaci/hostname/kubernetes-example/hostname-svc.yaml`
- From within the dnstest container, try `wget hostname:8000` or `wget hostname.default.svc.cluster.local:8000`. Notice failure
- Note hostname service cluster IP from `kubectl get svc`
- from within the dnstest container, try wget <service cluster ip>:8000
- Note failure

**Comment by xtophs** [comment]
Played more with dnsPolicies. After upgrading cluster to 1.10.9, I was able to configure a pod with

```
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.0.0.10
    searches:
      - default.svc.cluster.local
      - svc.cluster.local 
      - cluster.local
    options:
      - name: ndots
        value: "5"
```

The errors from dig and nslookup go away. Now nslookup times out, presumably because it can't reach the dns server listening on 10.0.0.10. 

Double-checking with `telnet 10.0.0.10 53` from a virtual kubelet pod and a pod running in the k8s cluster it looks like traffic from the virtual kubelet subnet 10.241.x.x cannot connect to the 10.0.x.x network. Only connections from the cluster agent subnet 10.240.x.x succeed:

** In-cluster pod **
```
# cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local q10ri0tyke2utfyjke44youebd.dx.internal.cloudapp.net
options ndots:5
# telnet 10.0.0.10 53
Trying 10.0.0.10...
Connected to 10.0.0.10.
Escape character is '^]'.
```

** Virtual Kubelet pod **
```
# cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
# telnet 10.0.0.10 53
Trying 10.0.0.10...
[times out]
```

Doesn't look like there are any NSGs on either the agent subnet or the ACI subnet that would restrict the traffic to 10.0.x.x addresses. None of the inbound and outbound rules of the NSG restrict traffic within the virtual network. 

What am I missing?

**Comment by AceHack** [comment]
I had a very similar issue but then used the guide below and did things the CLI way and it started working.
https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli


My issue for reference
https://github.com/virtual-kubelet/virtual-kubelet/issues/445

**Comment by xtophs** [comment]
@AceHack Thanks. The installing the ace-connector with the AZ CLI instead of the helm chart fixed network access to services in the 10.0.0.0/16 network. DNS resolution is still broken, presumably because of the malformed `/etc/resolv.conf`.

For AKS clusters running 1.10 you can work around this with a custom `dnsConfig` for a pod:
```
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.0.0.10
      - 8.8.8.8
    searches:
      - default.svc.cluster.local
      - svc.cluster.local 
      - cluster.local
    options:
      - name: ndots
        value: "5"
```

**Comment by xtophs** [comment]
@robbiezhang:

I know there's a lot of info in the thread. Trying to distill:

1. Following install instructions at https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md there are error messages from dig and nslookup inside a container. Services on the 10.0.0.0/16 appear not to be reachable. There are not extra steps to config NSGs, etc. Please see Repro steps above or at https://github.com/xtophs/aks-vkubelet-burst 
2. Overriding dnsConfig in the pod, error messages go away, but services on the 10.0.0.0/16 are still not reachable.
3. deploying with instructions from https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli, services on the 10.0.0.0/16 are reachable, but for Kube-DNS to work, dnsConfig override is required.

**Comment by robbiezhang** [comment]
The repo steps confused me a lot, until I notice that you updated the deploy-vkubelet.sh to use the add-on extension recently. Can you confirm that you hit the DNS resolution issue when you use the script in your initial commit?
https://github.com/xtophs/aks-vkubelet-burst/blob/15e32f86dfaf73ecdca3ab79bbf1f2626326e972/deploy-vkubelet.sh#L6
The MASTER_URI should contains `https://`. This should fix the issue.
```bash
export MASTER_URI=$(kubectl cluster-info | head -n1 | cut -d ' ' -f 6)
```

The empty search in the resolv.conf is an issue. I can repo it in my environment. ACI service should fix it. Once it's fixed, you don't have to override the dnsConfig for your pod to workaround.

However, the "malformed" resolv.conf doesn't block DNS resolution in my Virtual Node enabled AKS cluster.
![image](https://user-images.githubusercontent.com/9003737/50368355-b424d480-053c-11e9-8d91-68d0878698ac.png)
Notice that you must use the full cluster DNS, i.e. [service name].[namespace].svc.cluster.local
Can you double check in 3 above?

**Comment by jovizhangwei** [comment]
In our cloud vpc network environment, currently we are using a simple hack solution to allow ECI(Alibaba Cloud Elastic Container Instance) pod access ClusterIP. 

We add a new VPC route manually, to forward ClusterIP packet to real nodes(not virtual node), then real node's kube-proxy will resolve ClusterIP to pod IP.
