### ISSUE TITLE
Define a GOVERNANCE.md

### ISSUE THREAD

**Issue by caniszczyk** [virtual-kubelet/virtual-kubelet#459]
You list your maintainers but you don't have a process outlined on how to become a maintainer outside of emailing a maintainer. I'd advise you come up with a simple process, maybe a 2/3 super majority vote or so, you can look at what other CNCF projects do:

https://github.com/containernetworking/cni/blob/master/GOVERNANCE.md
https://github.com/envoyproxy/envoy/blob/master/GOVERNANCE.md
https://github.com/coredns/coredns/blob/master/GOVERNANCE.md

**Comment by rbitia** [comment]
https://github.com/virtual-kubelet/community/pull/1
Added in our community repo

**Comment by cpuguy83** [comment]
🎉
