### ISSUE TITLE
Please support port-forward in virtual kubernetes

### ISSUE THREAD

**Issue by xinyanmsft** [virtual-kubelet/virtual-kubelet#471]
Provider (e.g. ACI, AWS Fargate, Hyper): ACI
Version (e.g. 0.1, 0.2-beta): current
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS): AKS
Install Method (e.g. Helm Chart, ): helm chart (via AKS)

### Issue Details
Currently virtual node on AKS does not support port-forwarding. Port-forwarding helps a lot of developers scenarios such as debugging into the container. Please consider support it. Thanks!

**Comment by cpuguy83** [comment]
This looks like a dup of https://github.com/virtual-kubelet/virtual-kubelet/issues/170

If so, can you close?
