### ISSUE TITLE
async provider sync

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#476]
Right now VK loops every 5 seconds it goes through each known pod from the provider and updates k8s with any status changes.

Instead we should consider supporting some type of async API where we get notifications from the provider when something has changed state and VK can watch for these notifications.

**Comment by cpuguy83** [comment]
Here's what I'm thinking for this interface:

```go
// PodNotifier notifies callers of pod changes.
// Providers should implement this interface to enable callers to be notified
// of pod status updates asyncronously.
type PodNotifier interface {
	// NotifyPods instructs the notifier to call the passed in function when
	// the pod status changes with the key to use for fetching the pod.
	//
	// NotifyPods should not block callers.
	NotifyPods(func(string))
}
```

In the VK core we can enqueue changes to be handled by a set of workers much like we do from the k8s client.

**Comment by rbitia** [comment]
#493

**Comment by cpuguy83** [comment]
This is completed in #493
