### ISSUE TITLE
Solution for `No Auth Provider found for name "gcp"`

### ISSUE THREAD

**Issue by DazWilkin** [virtual-kubelet/virtual-kubelet#48]
I'm hacking a (Docker) Provider to explore virtual-kubelet but encountered this error when attempting to start the virtual-kubelet against a [GKE](cloud.google.com/gke) ("gcp") cluster.

The solution is to add the following GCP-specific auth to the Provider

`_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"`

Thank to https://github.com/kubernetes/client-go/issues/242

**Comment by rbitia** [comment]
Closing because it doesn't seem to be a core VK issue.
