### ISSUE TITLE
does mock provider support general kubernetes cluster except minikube and docker for desktop

### ISSUE THREAD

**Issue by wukong1992** [virtual-kubelet/virtual-kubelet#481]
---

### Environment summary

Provider mock

Version ：latest

K8s Master Info： private

Install Method ：git clone，make build，./bin/virtual-kubelet

I test the virtual-kubelet succed in minikube, but in company private kubernetes cluster, when i deploy pod the virtual node would be notready.

**Comment by robbiezhang** [comment]
do you see any log from the VK?

**Comment by wukong1992** [comment]
How to see the log from VK, the events in the node is none, it's just be notready

**Comment by wukong1992** [comment]
This is the stack when I run `./bin/virtual-kubelet --nodename vkubelet-mock-0 --provider mock --provider-config vkubelet-mock-0-cfg.json  --metrics-addr=:10258`

stack：
`2018/12/28 11:55:54 receive GetPod "calico-node-rv7w5"
E1228 11:55:54.120705   27871 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/work/jishaomin/go/src/runtime/asm_amd64.s:522
/home/work/jishaomin/go/src/runtime/panic.go:513
/home/work/jishaomin/go/src/runtime/panic.go:82
/home/work/jishaomin/go/src/runtime/signal_unix.go:390
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:230
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:77
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:62
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:45
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:286
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:257
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:195
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:209
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:155
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:142
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/work/jishaomin/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10d6cc8]

goroutine 163 [running]:
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1c91820, 0x3a8c6b0)
	/home/work/jishaomin/go/src/runtime/panic.go:513 +0x1b9
github.com/virtual-kubelet/virtual-kubelet/vkubelet.makeEnvironmentMapBasedOnEnv(0x23641e0, 0xc0006f82a0, 0xc0008a2380, 0xc000763b80, 0xc00073f950, 0x2364b60, 0xc000758f80, 0xc0006f8300, 0x0, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:230 +0xf28
github.com/virtual-kubelet/virtual-kubelet/vkubelet.populateContainerEnvironment(0x23641e0, 0xc0006f82a0, 0xc0008a2380, 0xc000763b80, 0xc00073f950, 0x2364b60, 0xc000758f80, 0xc0006d0230, 0x2050d87)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:77 +0xf0
github.com/virtual-kubelet/virtual-kubelet/vkubelet.populateEnvironmentVariables(0x23641e0, 0xc0006f82a0, 0xc0008a2380, 0xc00073f950, 0x2364b60, 0xc000758f80, 0x0, 0x23641e0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/env.go:62 +0x1da
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).createOrUpdatePod(0xc000ade6c0, 0x23641e0, 0xc0006f82a0, 0xc0008a2380, 0x2364b60, 0xc000758f80, 0x0, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:45 +0x1a6
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).syncPodInProvider(0xc000102c80, 0x23641e0, 0xc0006f8150, 0xc0008a2380, 0x0, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:286 +0x2d6
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).syncHandler(0xc000102c80, 0x23641e0, 0xc0006f80c0, 0xc00073a360, 0x1d, 0x0, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:257 +0x748
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).processNextWorkItem.func1(0xc000102c80, 0x23641e0, 0xc0006f8030, 0xc00084e2a0, 0x1bb2780, 0xc00001ad60, 0x0, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:195 +0x1af
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).processNextWorkItem(0xc000102c80, 0x23641e0, 0xc0006f8030, 0x2109bb5, 0x2, 0x0)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:209 +0x20b
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).runWorker(0xc000102c80, 0x2364120, 0xc0009e8bc0, 0x2109bb5, 0x2)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:155 +0x53
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).Run.func1()
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:142 +0x7e
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007da180)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007da180, 0x3b9aca00, 0x0, 0x1, 0xc00031a540)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007da180, 0x3b9aca00, 0xc00031a540)
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).Run
	/home/work/jishaomin/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:140 +0x223`

**Comment by wukong1992** [comment]
@robbiezhang

**Comment by robbiezhang** [comment]
The log looks similar to #444. However, I don't think VK node can run Calico. Can you try to disable Calico on it?

**Comment by pires** [comment]
Also, please compile VK from [`pires/fix_env_ref_optional_nilptr` branch](https://github.com/virtual-kubelet/virtual-kubelet/tree/pires/fix_env_ref_optional_nilptr) and give it a try.

**Comment by pires** [comment]
Fixed by #491
