### ISSUE TITLE
Split node registration from pod watch/sync

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#486]
Right now VK node registration and pod syncing are all tied together in one call to `Run`.
Implementors may want to have more control over node registration than this currently allows for.

I suggest that we split node registration and status update from the pod sync startup. This gives implementors a lot more control over when/how the node object is managed with the API server.

**Comment by cpuguy83** [comment]
ping @pires, thoughts?

**Comment by pires** [comment]
Yes, I do. I'd even add that it's not just about node registration but any node resource operation, ie #427.

**Comment by cpuguy83** [comment]
Closing since #526 addresses both of these issues.
