### ISSUE TITLE
New provider: Firecracker

### ISSUE THREAD

**Issue by inge4pres** [virtual-kubelet/virtual-kubelet#488]
### New Provider: Firecracker

Provider (e.g. ACI, AWS Fargate, Hyper)
Firecracker

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, )
TBD

### Issue Details
This is a feature request to add a Firecracker provider to connect virtual-kubelet with the Firecracker REST API (and optionally with the experimental VSOCK API too 😄 ).
Pods in k8s might be represented by VMs managed by firecracker, with the possibility to have multiple containers in one pod sharing the same TAP device on the firecracker host.

### Repo Steps
(@inge4pres) Open a PR with initial support for Firecracker as a new provider

**Comment by resouer** [comment]
One question is what would be difference with Firecracker + CRI work?

**Comment by cpuguy83** [comment]
I thought I commented on this, guess it didn't make it through for some reason.

Have you looked at https://github.com/firecracker-microvm/firecracker-containerd?
Since this is managing an actual node resource I'm wondering if integrating via containerd with the real kubelet is best.

**Comment by raravena80** [comment]
I guess the alternative would be CRI -> Containerd -> Firecracker.  Seems like that would work,  the limitation, for now, would be: launch one container per microVM

**Comment by cpuguy83** [comment]
Yeah, I believe firecraker-containerd has plans to support multiple containers in the microvm.

**Comment by inge4pres** [comment]
I did not know of the existence of the containerd project in firecracker, thanks for pointing out! 
@resouer I guess the only difference with a deployment through virtual kubelet provider would be that containerd would require the whole cluster to be setup with a CRI-containerd runtime, while with the virtual kubelet you could have only a subset of nodes provisioning firecracker VMs, isn't it?

**Comment by johanneswuerbach** [comment]
VirtualKublet generally defers the running of the kubernetes pod to a 3rd party provider (e.g. Azure ACI or AWS Fargate) so its actually never provisioning nodes or handling resource distribution.

While a firecracker provider might be possible it would be limited to spawning microvms on a single node or you would need to implement some scheduling to decide which node should be targeted etc.

As far as I know nothing prevents you from running different kubernetes nodes with different CRIs in the same cluster, but there is no stable build in support for saying „this pods needs vm based isolation“ so you would need to do this manually via node selectors or use https://kubernetes.io/docs/concepts/containers/runtime-class/, which is only alpha at the moment.

**Comment by inge4pres** [comment]
Thank you all for the info provided, closing this for now 😄
