### ISSUE TITLE
What to do with providers?

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#494]
Right now this repo is full of provider specific code which also has a separate maintenance flow from VK core.
Should this code continue to live in VK?

Part of the direction that I see for VK is to provide a good framework for providers to build their own integrations that integrate well with their infrastructure. Mostly I would expect to see that code live within a provider's org.

I do see some benefit to having a common daemon implementation, but I think realistically this limits what is possible and makes a pretty bloated daemon.

So I want to get a feel for what other maintainers/providers are thinking along these lines. Is there still a benefit to:
1. Keep existing providers in tree
2. Keep adding new providers in tree

This also brings up a slight tangent, should we continue to release an all-inclusive VK image as we do today? If so we need to formalize this release process.

**Comment by cpuguy83** [comment]
Added a bunch of people here, but sure other providers are missing... I didn't see them in the list... maybe @rbitia knows GH handles?

**Comment by resouer** [comment]
My random thoughts is, eventually I believe providers could find a new home like [cloudproviders](https://github.com/kubernetes/cloud-provider-aws) in Kubernetes org. That said, it make a lot sense for VK to follow the same maintenance/migrate pattern in kube community. 

The experience is, having providers in tree for certain period of time do benefit to accumulate issues/PRs/discussion in the same picture, especially when the interface/architecture of the main project is still quickly evolving. And of course the cost is extra maintenance effort, and dragging of release lifecycle.

I would suggest, maybe, we can try to align providers migration process with VK incubation process in CNCF? cc @ritazh

**Comment by caniszczyk** [comment]
You can also host these providers as sub projects of the VK github organization as one path forward, each other their own maintainers/governance per sub project

**Comment by pires** [comment]
+1 for making VK a clean framework anyone can use to build their provider with, and having providers living elsewhere. Eventually, a path for something like a _certified VK provider_ could be specified, which end result could be the provider code moving to the VK github org.

**Comment by caniszczyk** [comment]
My advice to the VK project would be to create a GOVERNANCE.md that dictates how projects are added/removed along with maintainers, e.g.,

https://github.com/envoyproxy/envoy/blob/master/GOVERNANCE.md
https://github.com/coredns/coredns/blob/master/GOVERNANCE.md

**Comment by zanetworker** [comment]
Should gRPC be considered? communication between the daemon and the providers would be a matter of calling the right remote RPC.

**Comment by pires** [comment]
gRPC would be an implementation detail. The discussion here is more about what VK is and what it can/shall become.

**Comment by rbitia** [comment]
We should have a list of guidelines for a beta through 1.0 status for providers.

**Comment by cpuguy83** [comment]
Just an FYI, I plan to start moving providers into their own repo in the VK org this week.
If you'd like to help with that, it would be amazing.

If you have some concerns with this please ping me ASAP.

**Comment by cpuguy83** [comment]
@resouer I have created a repo for alibaba here: https://github.com/virtual-kubelet/alibabacloud-eci
PTAL and make sure it works for you.

Once you are good with that and #668 is merged (to avoid conflicts) I can open a PR to remove the provider implementation from virtual-kubelet/virtual-kubelet.

**Comment by hongbin** [comment]
@cpuguy83 let me know if you need some helps for the OpenStack provider.

**Comment by pires** [comment]
@hongbin yes, please.

**Comment by cpuguy83** [comment]
@ofiliz I've created an aws-fargate repo: https://github.com/virtual-kubelet/aws-fargate

**Comment by cpuguy83** [comment]
More repos:


https://github.com/virtual-kubelet/openstack-zun -- @hongbin 
https://github.com/virtual-kubelet/nomad - @anubhavmishra 
https://github.com/virtual-kubelet/huawei-cci - @fisherxu 
https://github.com/virtual-kubelet/cri - @corrieb 
https://github.com/virtual-kubelet/aws-fargate - @ofiliz

**Comment by anubhavmishra** [comment]
Thanks @cpuguy83. Will have a look!

**Comment by cpuguy83** [comment]
And the final one (unless I"m mistaken): https://github.com/virtual-kubelet/web

**Comment by cpuguy83** [comment]
And here I've done one big PR to move stuff out, PTAL: https://github.com/virtual-kubelet/virtual-kubelet/pull/670

We can do it piecemeal if people are more comfortable with that.

**Comment by hongbin** [comment]
A question. After this change, how can I install Virtual Kubelet along with a particular provider. In before, I used to do:

$ go get github.com/virtual-kubelet/virtual-kubelet

above command doesn't seem to work properly recently.

**Comment by cpuguy83** [comment]
It is up to the provider to handle releases.
Note that installing from "go get" hasn't worked in some time since providers were only included via build tag.

The providers that were split from this repo, however, should be installable in this manner (at least currently) by go-getting <provider repo>/cmd/virtual-kubelet

**Comment by hongbin** [comment]
@cpuguy83 ,

Thanks for the reply. It looks I had errors on executing the command you suggested:

`
$ go get -v github.com/virtual-kubelet/openstack-zun/cmd/virtual-kubelet
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
        ignoring go.mod;
        see 'go help modules'
github.com/virtual-kubelet/openstack-zun/cmd/virtual-kubelet/commands/root
# github.com/virtual-kubelet/openstack-zun/cmd/virtual-kubelet/commands/root
cmd/virtual-kubelet/commands/root/node.go:57:4: cannot use p.Capacity(ctx) (type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".ResourceList) as type "k8s.io/api/core/v1".ResourceList in field value
cmd/virtual-kubelet/commands/root/node.go:58:4: cannot use p.Capacity(ctx) (type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".ResourceList) as type "k8s.io/api/core/v1".ResourceList in field value
cmd/virtual-kubelet/commands/root/node.go:59:4: cannot use p.NodeConditions(ctx) (type []"github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".NodeCondition) as type []"k8s.io/api/core/v1".NodeCondition in field value
cmd/virtual-kubelet/commands/root/node.go:60:4: cannot use p.NodeAddresses(ctx) (type []"github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".NodeAddress) as type []"k8s.io/api/core/v1".NodeAddress in field value
cmd/virtual-kubelet/commands/root/node.go:61:4: cannot use *p.NodeDaemonEndpoints(ctx) (type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".NodeDaemonEndpoints) as type "k8s.io/api/core/v1".NodeDaemonEndpoints in field value
cmd/virtual-kubelet/commands/root/root.go:109:58: cannot use podInformer.Lister() (type "k8s.io/client-go/listers/core/v1".PodLister) as type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".PodLister in argument to manager.NewResourceManager:
        "k8s.io/client-go/listers/core/v1".PodLister does not implement "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".PodLister (wrong type for List method)
                have List("k8s.io/apimachinery/pkg/labels".Selector) ([]*"k8s.io/api/core/v1".Pod, error)
                want List("github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/labels".Selector) ([]*"github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".Pod, error)
cmd/virtual-kubelet/commands/root/root.go:109:83: cannot use secretInformer.Lister() (type "k8s.io/client-go/listers/core/v1".SecretLister) as type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".SecretLister in argument to manager.NewResourceManager:
        "k8s.io/client-go/listers/core/v1".SecretLister does not implement "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".SecretLister (wrong type for List method)
                have List("k8s.io/apimachinery/pkg/labels".Selector) ([]*"k8s.io/api/core/v1".Secret, error)
                want List("github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/labels".Selector) ([]*"github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".Secret, error)
cmd/virtual-kubelet/commands/root/root.go:109:111: cannot use configMapInformer.Lister() (type "k8s.io/client-go/listers/core/v1".ConfigMapLister) as type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".ConfigMapLister in argument to manager.NewResourceManager:
        "k8s.io/client-go/listers/core/v1".ConfigMapLister does not implement "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".ConfigMapLister (wrong type for ConfigMaps method)
                have ConfigMaps(string) "k8s.io/client-go/listers/core/v1".ConfigMapNamespaceLister
                want ConfigMaps(string) "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".ConfigMapNamespaceLister
cmd/virtual-kubelet/commands/root/root.go:109:137: cannot use serviceInformer.Lister() (type "k8s.io/client-go/listers/core/v1".ServiceLister) as type "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".ServiceLister in argument to manager.NewResourceManager:
        "k8s.io/client-go/listers/core/v1".ServiceLister does not implement "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/client-go/listers/core/v1".ServiceLister (wrong type for GetPodServices method)
                have GetPodServices(*"k8s.io/api/core/v1".Pod) ([]*"k8s.io/api/core/v1".Service, error)
                want GetPodServices(*"github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".Pod) ([]*"github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".Service, error)
cmd/virtual-kubelet/commands/root/root.go:150:34: cannot use p (type *openstack.ZunProvider) as type providers.Provider in argument to NodeFromProvider:
        *openstack.ZunProvider does not implement providers.Provider (wrong type for Capacity method)
                have Capacity(context.Context) "k8s.io/api/core/v1".ResourceList
                want Capacity(context.Context) "github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/api/core/v1".ResourceList
cmd/virtual-kubelet/commands/root/root.go:150:34: too many errors
`

**Comment by cpuguy83** [comment]
@hongbin `GO111MODULE=on go get github.com/virtual-kubelet/openstack-zun/cmd/virtual-kubelet`

**Comment by hongbin** [comment]
@cpuguy83 , Cool.

Sorry. I have one more question. Who are supposed to maintain individual provider repo? If possible, please grant me and @kevin-zhaoshuai proper permission on the openstack-zun repo. I would like to be able to merge PRs, install app (like https://github.com/apps/theopenlab-ci), etc.

**Comment by cpuguy83** [comment]
Since @kevin-zhaoshuai is the original contributor I've added him as an admin to that repo, I'll let him add new collaborators as needed.

**Comment by hongbin** [comment]
@cpuguy83 Thanks for the hints. Kevin has added me as an admin.

There is still an issue. I wanted to install a Github app for our provider repo, but it seems neither @kevin-zhaoshuai nor I has enough permission to do that. Please https://github.com/theopenlab/openlab/issues/255 for details.

Is that related to insufficient permission for the provider admins?

**Comment by cpuguy83** [comment]
Thanks for your patience!

I've added the openlab app to the VK org for the openstack-zun.
