### ISSUE TITLE
Azurebatch doesn't launch and logs don't show up, for larger kubectl jobs

### ISSUE THREAD

**Issue by posix4e** [virtual-kubelet/virtual-kubelet#503]
As much as it's lovely to have a tf config, it would also be lovely if you provided standalone instructions on how to attach azure batch to an existing cluster with a virtual kubelet. I have created a helm chart. 

https://github.com/virtual-kubelet/virtual-kubelet/pull/504

 I am currently testing it however I am getting an error in the kubelet when I launch jobs against it. The pod has something similar
```
2019/01/15 04:02:00 Failed to get auth information
Starting create provider
2019/01/15 04:02:00 Pool active and running...
2019/01/15 04:02:00 Wrapper job missing... creating...
time="2019-01-15T04:02:00Z" level=info msg="Registered node" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
2019/01/15 04:02:00 Getting pods...
time="2019-01-15T04:02:00Z" level=info msg="starting workers" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
time="2019-01-15T04:02:00Z" level=info msg="started workers" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
2019/01/15 04:13:19 Getting Pod ...
2019/01/15 04:13:20 Creating pod...
time="2019-01-15T04:13:20Z" level=warning msg="requeuing \"polyaxon/plxjob-master0-73aef6df4c8c460da3e395e04ccb794e\" due to failed sync" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
time="2019-01-15T04:13:20Z" level=warning msg="skipping sync of pod \"polyaxon/plxjob-master0-73aef6df4c8c460da3e395e04ccb794e\" in \"Failed\" phase" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
2019/01/15 04:14:42 Getting pod logs ....
time="2019-01-15T04:14:43Z" level=error msg="Internal server error on request" error="error getting container logs?): batch.FileClient#GetFromTask: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: \"{\\r\\n  \\\"odata.metadata\\\":\\\"https://testgpu26.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element\\\",\\\"code\\\":\\\"TaskNotFound\\\",\\\"message\\\":{\\r\\n    \\\"lang\\\":\\\"en-US\\\",\\\"value\\\":\\\"The specified task does not exist.\\\\nRequestId:ae88e9b0-0267-4bd1-b394-e8a82c93e275\\\\nTime:2019-01-15T04:14:43.0370098Z\\\"\\r\\n  }\\r\\n}\" error: json: cannot unmarshal object into Go struct field RequestError.Message of type string" httpStatusCode=500 namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch uri=/containerLogs/polyaxon/plxjob-master0-73aef6df4c8c460da3e395e04ccb794e/polyaxon-experiment-job vars="map[]"
2019/01/15 04:19:03 Getting Pod ...
2019/01/15 04:19:03 Creating pod...
time="2019-01-15T04:19:03Z" level=warning msg="requeuing \"polyaxon/plxjob-master0-10a893dc047e40b691df29796a9e35bf\" due to failed sync" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
time="2019-01-15T04:19:03Z" level=warning msg="skipping sync of pod \"polyaxon/plxjob-master0-10a893dc047e40b691df29796a9e35bf\" in \"Failed\" phase" namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch
2019/01/15 04:19:08 Getting Pod ...
2019/01/15 04:19:08 Getting Pod ...
2019/01/15 04:19:53 Getting pod logs ....
time="2019-01-15T04:19:53Z" level=error msg="Internal server error on request" error="error getting container logs?): batch.FileClient#GetFromTask: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: \"{\\r\\n  \\\"odata.metadata\\\":\\\"https://testgpu26.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element\\\",\\\"code\\\":\\\"TaskNotFound\\\",\\\"message\\\":{\\r\\n    \\\"lang\\\":\\\"en-US\\\",\\\"value\\\":\\\"The specified task does not exist.\\\\nRequestId:2ded67df-aa1d-4bae-808d-3f619941a85d\\\\nTime:2019-01-15T04:19:53.1177403Z\\\"\\r\\n  }\\r\\n}\" error: json: cannot unmarshal object into Go struct field RequestError.Message of type string" httpStatusCode=500 namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch uri=/containerLogs/polyaxon/plxjob-master0-10a893dc047e40b691df29796a9e35bf/polyaxon-job-sidecar vars="map[]"
2019/01/15 04:19:59 Getting pod logs ....
time="2019-01-15T04:19:59Z" level=error msg="Internal server error on request" error="error getting container logs?): batch.FileClient#GetFromTask: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: \"{\\r\\n  \\\"odata.metadata\\\":\\\"https://testgpu26.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element\\\",\\\"code\\\":\\\"TaskNotFound\\\",\\\"message\\\":{\\r\\n    \\\"lang\\\":\\\"en-US\\\",\\\"value\\\":\\\"The specified task does not exist.\\\\nRequestId:f4b662ef-ff78-4886-879a-196e65fa0c6e\\\\nTime:2019-01-15T04:19:59.2877573Z\\\"\\r\\n  }\\r\\n}\" error: json: cannot unmarshal object into Go struct field RequestError.Message of type string" httpStatusCode=500 namespace= node=virtual-kubelet operatingSystem=Linux provider=azurebatch uri=/containerLogs/polyaxon/plxjob-master0-10a893dc047e40b691df29796a9e35bf/polyaxon-experiment-job vars="map[]"
```

and when I wanna get logs on the client 
Image
```
microsoft/virtual-kubelet:latest
```
```
Error from server (InternalError): Internal error occurred: error getting container logs?): batch.FileClient#GetFromTask: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "{\r\n  \"odata.metadata\":\"https://testgpu26.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element\",\"code\":\"TaskNotFound\",\"message\":{\r\n    \"lang\":\"en-US\",\"value\":\"The specified task does not exist.\\nRequestId:f49a2f82-d1b9-4364-8a54-61f51cbdf637\\nTime:2019-01-15T04:25:37.9619349Z\"\r\n  }\r\n}" error: json: cannot unmarshal object into Go struct field RequestError.Message of type string
```

kubectl describe is mostly normal except!
```
Status:             Failed
Reason:             ProviderFailed
Message:            batch.TaskClient#Add: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\r\n  \"odata.metadata\":\"https://testgpu26.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element\",\"code\":\"InvalidPropertyValue\",\"message\":{\r\n    \"lang\":\"en-US\",\"value\":\"The value provided for one of the properties in the request body is invalid.\\nRequestId:b88574da-cba0-4769-9086-0134c6fac81e\\nTime:2019-01-15T04:19:03.6221353Z\"\r\n  },\"values\":[\r\n    {\r\n      \"key\":\"PropertyName\",\"value\":\"commandLine\"\r\n    },{\r\n      \"key\":\"Reason\",\"value\":\"Total size of commandLine cannot be more than 32768 characters\"\r\n    }\r\n  ]\r\n}" error: json: cannot unmarshal object into Go struct field RequestError.Message of type string

```

**Comment by posix4e** [comment]
Perhaps a way to run only a subset of the terraform would be sufficient.

**Comment by posix4e** [comment]
```
xport VK_RELEASE=virtual-kubelet-for-aks-0.1.3

RELEASE_NAME=virtual-kubelet
NODE_NAME=virtual-kubelet
CHART_URL=https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/$VK_RELEASE.tgz                     


. ./createCertAndKey.sh
helm upgrade $RELEASE_NAME $CHART_URL \
        --install --wait \
        --set rbac.install=true \
        --set providers.azure.targetAKS=true \
        --set provider=azurebatch \
        --set env.apiserverCert="$cert",env.apiserverKey="$key",env.VK_TAINT_KEY="azure.com/aci"                   
        --set providers.azure.masterUri=$MASTER_URI
```
Seems not to work

**Comment by rbitia** [comment]
Thanks for the issue! I'll delegate the issue to the corresponding provider :)

**Comment by rbitia** [comment]
@lawrencegripper can you take a look?

**Comment by lawrencegripper** [comment]
Thanks the info and detailed logs and working on a `heml` chart! 

It looks like the underlying command which in getting generated and sent to batch is bigger than batch allows `Total size of commandLine cannot be more than 32768 characters`.

Do you have an example of the pod you are attempting to create in Batch? This would allow me to reproduce the issue locally and see what I can do to resolve. 

Under the covers the provider is using [pod2docker](https://github.com/lawrencegripper/pod2docker) to convert the pod definition into a set of docker commands (this allows sidecars and multi-container pods to function as expected by sharing a network etc) one option might be to move this generation out of the vkubelet code and instead ship the `yaml` pod definition to batch and run `pod2docker` inside batch for each task. I'd need to have a look and see how feasible that is. Another option might be to [minify the script](https://github.com/Zuzzuc/Bash-minifier) generated although that feels very nasty. A middle ground may be to remove [some of the logging ](https://github.com/lawrencegripper/pod2docker/blob/master/pod2docker_template.go#L89) from the `pod2docker` template.  

I'm heads down at the moment on another project atm, once I've got a pod definition I can use to repro and I get some time I'll have a look and see what I can do. In the meantime dropping or reducing the complexity of the pod will lower the `commandline` length sent to Batch (think removing sidecars, mount points etc) and may let you work around the issue for now.

**Comment by posix4e** [comment]
Sorry for missing this. I use polyaxon and spawning anything with that will break it. https://github.com/polyaxon/polyaxon/issues/364

**Comment by posix4e** [comment]
Why not upload it to azure storage as a zipf ile?

**Comment by lawrencegripper** [comment]
Yeah that is a possibility - one reason I avoided that originally is that I didn't want to persist secrets mounted by the pods onto a storage account somewhere. Guess they could be cleaned up afterwards but adds a bit more complexity.

**Comment by posix4e** [comment]
Makes sense, maybe it's worth it to support both. Generally the secrets will already be installed in the cluster no?

**Comment by lawrencegripper** [comment]
Yeah so the secrets already sit in the cluster but I wonder if people would be surprised to find that the Batch VK provider had been uploading them into the Azure Batch storage account. Probably not a big thing and just being overly cautious. 

Depending on how well it compresses I'd think the simplest approach would be to gzip then base64 the output of `pod2docker` then pass this to a batch with something like (sudo code):

```
/bin/bash -c "echo 'base64GzipdContent' | base64 -d | gunzip | bash -"
```

**Comment by posix4e** [comment]
Sorry I'm confused is that a change on my side or yours?

**Comment by posix4e** [comment]
any updates?

**Comment by lawrencegripper** [comment]
Hi, 

I'm still heads down with other work at the moment and it looks that way for the coming weeks, sorry. 

Happy to review a PR if you wanted to take a look at compressing the command output sent to Batch. 

I did get a change to spin up Polyaxion the other day and attempt to get a handle on the use case. One thing I noticed is that it has [a number of components such as Redis and RabbitMQ](https://docs.polyaxon.com/references/polyaxon-helm-reference/) which are used to coordinate work between pods. This will be a problem when using the VK and Batch as the batch nodes don't participate in the K8s network so can't a Pod in Batch can't talk to another pod on a different node in Batch. 

Do you know to what extent these service are required for inter-pod communication?

**Comment by posix4e** [comment]
I believe all of that should be fine, networkwise. Interesting point
though. I’m still confused what I need to do to move this forward.
-- 
+14045076749 Alex
