### ISSUE TITLE
imagePullSecrets does not working, later the configure the Virtual-Kubelet

### ISSUE THREAD

**Issue by andreslon** [virtual-kubelet/virtual-kubelet#505]
1. Create the Azure Kubernetes Service into Azure.
2. Create the Secret to ACR
3. Deploy any Linux image to AKS 

**Does Working prefectly.**

4. Use Virtual Kubelet with Azure Kubernetes Service [(https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet)](https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet)
5. Try deploy again any image Linux or windows

**Does No working.**

The pods status is always  "ProviderFailed", but if the image linux or windows is from DockerHub, if works correctly! :(

Image into DockerHub "andreslon/netframework-backgroundtask:277"
Image into ACR "sampleacrdev/netframework-backgroundtask:277"

I need your help.
__________________________________________

My YAML:

``` xml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netframework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netframework
  template:
    metadata:
      labels:
        app: netframework
    spec:
      containers:
      - name: netframework
        image: sampleacrdev/netframework-backgroundtask:277
      nodeSelector:
        beta.kubernetes.io/os: windows
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule
      imagePullSecrets:
      - name: acr-auth 
```

**Comment by rbitia** [comment]
Hey @andreslon thanks for the issue! Sorry we didn't reply before but you created a secret on your cluster, correct? @dkkapur can you take a look?

**Comment by dkkapur** [comment]
@srrengar

**Comment by srrengar** [comment]
@robbiezhang where should one include their secret when deploying from ACR into VK?

**Comment by robbiezhang** [comment]
@srrengar 
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by srrengar** [comment]
hi @andreslon I was able to create a pod successfully by following the docs that Robbie provided. When specifying the image, you need to include the full ACR server name, here is my YAML where the image name is **sravacr.azurecr.io/aci-tutorial-app:v1**. In your case I think it would be **sampleacrdev.azurecr.io/netframework-backgroundtask:277**

hope this helps! 

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      containers:
      - name: aci-helloworld
        image: sravacr.azurecr.io/aci-tutorial-app:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: sravacrsecret
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule`

**Comment by srrengar** [comment]
@andreslon let me know if adding the full server name for ACR in the pod spec works, I believe that's what was missing so I am closing the iossue. Feel free to reopen the issue if there is more
