### ISSUE TITLE
[Proposal] Provider over RPC calls

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#515]
We need to write an internal provider for our own container manager. This provider is not useful to the general purpose audience, even though it is open source (https://github.com/Netflix/titus-executor). I'm curious, as to whether it makes sense to have a general purpose provider that can be used to attach to other providers over the network.

For example, I could implement the Titus provider and expose a REST API, or a gRPC API, and then the virtual kubelet RPC provider would basically implement all of the endpoint that are in the provider API. This seems like a reasonable way to move providers out of the core VK codebase, and for people to write infrastructure-specific providers without maintaining a fork.

The core questions of this proposal:

1. Should a provider be built for this use case?
2. What RPC mechanism should this provider use?
3. Are there any other design considerations in building this provider?

**Comment by cpuguy83** [comment]
@sargun we are more focused on making VK easier to pull in as a library to make your own daemon implementations. 

Note there is a "web" provider which can handle out of process providers, although I'm not really familiar with the protocol.

**Comment by sargun** [comment]
Thanks! I think the web provider is exactly what I need. Any reason it's not part of the README.md doc?

**Comment by pires** [comment]
There is/was another discussion around exposing the Provider API through gRPC, but that complicated things because we would have to import many Kubernetes types, such as Pod and everything that can be part of a pod.

The web provider does seem the way to go in this case.

**Comment by pires** [comment]
Guess we can close it @sargun?
