### ISSUE TITLE
[Azure] Removing the connector doesn't remove the node

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#52]
I removed the windows connector with the az cli and it removed the pod for the windows connector but not the 2 nodes it had also created. 

Rias-MacBook-Pro:examples riabhatia$ az aks remove-connector --resource-group virtualKubelet --name virtualK8sCluster --connector-name windows-connector 
Merged "virtualK8sCluster" as current context in /var/folders/p2/6xnh48154w5_g8k_8pkfvkhm0000gn/T/tmpreiq5g88
Undeploying the aci-connector using Helm
release "windows-connector" deleted

Rias-MacBook-Pro:examples riabhatia$ kubectl get pods
NAME                                             READY     STATUS    RESTARTS   AGE
aci-demo-aci-demo-ir-1243301560-7l8qm            1/1       Running   0          15m
aci-demo-aci-demo-ir-2416843260-89ghx            1/1       Running   0          15m
demo-fr-ir-aci-1922196937-vm23w                  1/1       Running   0          15m
demo-fr-ir-aci-1922196937-xwpx1                  1/1       Running   0          15m
linux-connector-aci-connector-4084327094-5ct30   1/1       Running   0          17h
nginx                                            1/1       Running   0          17m
Rias-MacBook-Pro:examples riabhatia$ kubectl get node
NAME                       STATUS    AGE       VERSION
aci-connector              Ready     17h       v1.6.6
aci-connector-0            Ready     15m       v1.6.6
aci-connector-1            Ready     15m       v1.6.6
aks-nodepool1-21735328-0   Ready     21d       v1.7.7

**Comment by robbiezhang** [comment]
Kubernetes will remove the node automatically if the node doesn't update its status in 30 seconds. So, after you remove the connector pod, the virtual node will disappear in 30 seconds.

**Comment by rbitia** [comment]
Ah yes I just double checked that.

Thanks! I'll close this.

**Comment by sumitkute** [comment]
I tried the steps in https://github.com/Azure/AKS/issues/1427 but it was still showing in kubectl get node. Even the portal was showing virtual-node disabled. I then ran this command
>kubectl delete node virtual-node-aci-linux

and it worked for me. Now kuebctl do not show virtal node

>kubectl get nodes
