### ISSUE TITLE
Provider interface changes

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#520]
To date, the provider interface is fairly broad and many parts are not even implemented in providers. Even things that are implemented are done so identically. Other parts are just using the exact values that were passed in from the command line options.

I've also found that node management is too tangled up with pod management. Ideally, implementers can specify their own node rather than doing this in VK core.. and in some ways this is what we have with various node functions defined on the `Provider` interface, but... 1. See above paragraph, and 2. What is available is just a small portion, meanwhile VK core really doesn't care about these details. VK core *only* cares about having a node available.

Additionally we also have these loops in VK core to poll API's:
- Polls provider API (every 5 seconds) to gather pod status updates and updates k8s for changes. Note that this gathers *all* provider pods, not just changed items.
- Updates node status (every 5 seconds) in k8s API.

Proposed changes:

- Move node management functions out to a separate interface with a reduced surface area. This allows implementers to optionally manage their own node, or at least have a very light implementation and VK can do it. We can even provide a default implementation for this in VK core.
- Change the container logs interface to work with an I/O stream rather than a static `string`, reducing memory overhead
- Change Exec API to work with io Reader/Writer types, this allows the API handler to be much more flexible while simplifying implementations, and making it easier to test in isolation.
- Asynchronous pod status monitoring, reducing API calls to the providers and reduced memory overhead in dealing with list of pods.
- Asynchronous node management, only update node status on changes, uses node leases to prevent the node from being marked as unhealthy... may require fallback on older k8s versions. Makes node management much lighter weight.

```go
package providers

import (
	"context"
	"io"
	"time"

	v1 "k8s.io/api/core/v1"
	stats "k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
)

// PodProvider defines the control plane API for managing pods in a provider.
type PodProvider interface {
	// CreatePod takes a Kubernetes Pod and deploys it within the provider.
	CreatePod(ctx context.Context, pod *v1.Pod) error

	// UpdatePod takes a Kubernetes Pod and updates it within the provider.
	UpdatePod(ctx context.Context, pod *v1.Pod) error

	// DeletePod takes a Kubernetes Pod and deletes it from the provider.
	DeletePod(ctx context.Context, pod *v1.Pod) error

	// GetPod retrieves a pod by name from the provider (can be cached).
	GetPod(ctx context.Context, namespace, name string) (*v1.Pod, error)

	// GetPods retrieves a list of all pods running on the provider (can be cached).
	GetPods(context.Context) ([]*v1.Pod, error)

	// NotifyPods instructs the notifier to call the passed in function when
	// the pod status changes.
	//
	// NotifyPods should not block callers.
	NotifyPods(context.Context, func(*v1.Pod))
}

// RuntimeExecutor deals with interactions with the actual pods.
// These are typically synchronous actions called by the Kubernetes API server to give clients access to an actual pod
type RuntimeExecutor interface {
    	// GetContainerLogs retrieves the logs of a container by name from the provider.
	GetContainerLogs(ctx context.Context, namespace, podName, containerName string, opts ContainerLogOpts) (io.ReadCloser, error)

	// ExecInContainer executes a command in a container in the pod, copying data
	// between in/out/err and the container's stdin/stdout/stderr.
	ExecInContainer(ctx context.Context, namespace, podName, containerName string, cmd []string, attach AttachIO) error


	// PortForward forwards a port from virtual-kubelet to the pod
	PortForward(name string, uid types.UID, port int32, stream io.ReadWriteCloser) 
}

// AttachIO is used to pass in streams to attach to a container process
type AttachIO interface {
	Stdin() io.Reader
	Stdout() io.WriteCloser
	Stderr() io.WriteCloser
	TTY() bool
	Resize() <-chan TermSize
}

// TermSize is used to set the terminal size from attached clients.
type TermSize struct {
	Width  uint16
	Height uint16
}

// ContainerLogOpts are used to pass along options to be set on the container
// log stream.
type ContainerLogOpts struct {
	Tail       int
	Since      time.Duration
	LimitBytes int
	Timestamps bool
}

// PodMetricsProvider is an optional interface that providers can implement to expose pod stats
type PodMetricsProvider interface {
	GetStatsSummary(context.Context) (*stats.Summary, error)
}

// NodeProvider is the interface used for registering a node and updating its
// status in Kubernetes.
//
// Note: Implementaters can choose to manage a node themselves, in which case
// it is not needed to provide an implementation for this interface.
type NodeProvider interface {
	// GetNode is used when registering a node with Kubernetes
	GetNode(context.Context) (*v1.Node, error)

	// Ping checks if the node is still active.
	// This is intended to be lightweight as it will be called periodically as a
	// heartbeat to keep the node marked as ready in Kubernetes.
	Ping(context.Context) error

	// NotifyNodeStatus is used to asyncronously monitor the node.
	// The passed in callback should be called any time there is a change to the
	// node's status.
	// This will generally trigger a call to the Kubernetes API server to update
	// the status.
	//
	// NotifyNodeStatus should not block callers.
	NotifyNodeStatus(ctx context.Context, cb func(*v1.Node))
}
```

---

In general I'd say this interface is not finalized until all are true:

1. Providers are all re-written to use the interface
2. There are multiple implementations of a VK daemon (e.g., a CRD implementing VK and something similar to what we currently have).

I'm posting this for feedback. I do not expect everyone to just agree with these changes, so please speak up if you don't.

**Comment by cpuguy83** [comment]
Maybe a 1.4.1 and 1.3.1 respectively?

**Comment by danielvmw** [comment]
Thanks for this proposal, @cpuguy83. Allow me to comment on the `GetContainerLogs` & `ExecInContainer` methods, sort of as a follow up to https://github.com/virtual-kubelet/virtual-kubelet/issues/423.

The problem I see with the proposed interface (and granted, that is a problem not too many providers are likely to have) is that it assumes local handling of the request. What we do is we use the provider only as a proxy. So we'd like to have a way to merely forward incoming requests for logs/exec/attach, etc to another entity that does the bulk of the work and reports back.

As you mentioned in #423:
> Negotiating streams at the provider level complicates things quite a bit

and that is exactly what we are trying to avoid but what seems to be inherent in the proposed design.

Do you see a way how the two worlds can be combined?

I could envision a "staged" API where clients could hook into either the "raw request" (e.g., `ExecInContainer(w http.ResponseWriter, req *http.Request)`) or the higher level APIs that you propose. In a way that could be similar to the split between `PodProvider` and `NodeProvider` you propose. The "raw" APIs could and should have default implementations that just forward to the higher level ones. They could also be less stringent in terms of compatibility guarantees.

What are your thoughts on the matter?

**Comment by cpuguy83** [comment]
@danielvmw I do not understand why an io.Reader/io.Writer is problematic in a proxy model. Can you explain more?
In this case it's just a raw I/O stream with the protocol abstracted away.

`ExecInContainer(w http.ResponseWriter, req *http.Request)` -- This is an http.HandlerFunc, why not implement this on the API side?

**Comment by danielvmw** [comment]
> @danielvmw I do not understand why an io.Reader/io.Writer is problematic in a proxy model. Can you explain more?
> In this case it's just a raw I/O stream with the protocol abstracted away.

Right, which means we need to somehow take care of putting all the stream data again into some form of protocol to get it to the final end point. So that means the spherelet is acting as a server and a client and needs to contain logic for all of that, which is extensive.
I believe we could equally well just establish the streams directly between the endpoint and the caller, and just stupidly proxy data at a lower level.

> `ExecInContainer(w http.ResponseWriter, req *http.Request)` -- This is an http.HandlerFunc, why not implement this on the API side?

Yes, basically that level is fine. My familiarity with the code base dates back a few versions and I see things changed quite a bit. From a quick glance I still can't find a way to hook in at that level properly, though. Am I mistaken here?

**Comment by cpuguy83** [comment]
> Right, which means we need to somehow take care of putting all the stream data again into some form of protocol to get it to the final end point

Can you explain? This should be wiring up I/O streams from the container, the stream we pass to the Exec would be just the raw data stream, there should be no need for protocol interaction because the stream is literally just a stream of bytes, protocol is handled at the API layer. So I guess I'm really just not understanding the use case still.

> From a quick glance I still can't find a way to hook in at that level properly

Ultimately we are providing a framework to build on top of, part of that is including default HTTP handlers to reduce boiler plate. It would be nice for these to work for you, but if they don't they should just be replaced with a custom implementation.
Here is how we setup the HTTP server in provided binary: https://github.com/virtual-kubelet/virtual-kubelet/blob/bd103a43bd19ffdb84d4190ed7fbda1a47d0a55c/cmd/http.go#L75-L76

https://github.com/virtual-kubelet/virtual-kubelet/blob/bd103a43bd19ffdb84d4190ed7fbda1a47d0a55c/vkubelet/apiserver.go#L58-L64

https://github.com/virtual-kubelet/virtual-kubelet/blob/bd103a43bd19ffdb84d4190ed7fbda1a47d0a55c/vkubelet/apiserver.go#L25-L32

https://github.com/virtual-kubelet/virtual-kubelet/blob/bd103a43bd19ffdb84d4190ed7fbda1a47d0a55c/vkubelet/api/exec.go#L16-L17

As you can see we have a chain of helpers here for building an HTTP server. To provide a custom Exec implementation you probably would not be able to use these helpers directly.

**Comment by danielvmw** [comment]
> > Right, which means we need to somehow take care of putting all the stream data again into some form of protocol to get it to the final end point
> 
> Can you explain? This should be wiring up I/O streams from the container, the stream we pass to the Exec would be just the raw data stream, there should be no need for protocol interaction because the stream is literally just a stream of bytes, protocol is handled at the API layer. So I guess I'm really just not understanding the use case still.

For, say, exec we have potentially three streams: stdin, stdout, and stderr. It is possible to establish three connections -- one for each stream -- and push the content over that byte-by-byte. For different reasons we do not want to do that but only have a single connection to the container. That means we need logic to multiplex those three streams onto a single one and recover the original three streams on the container side of things.

> > From a quick glance I still can't find a way to hook in at that level properly
> 
> As you can see we have a chain of helpers here for building an HTTP server. To provide a custom Exec implementation you probably would not be able to use these helpers directly.

What I am getting at it that nothing of this is customizable by client code from what I can tell. All that logic is hardwired to behave this way and no way else -- no extension/hook-in points. Of course we can modify the `virtual-kubelet` code to suit our needs, but the goal is not to.

`setupHTTPServer` accept only a `Context` and an `apiServerConfig` -- nothing customizable here except for certificates and ports. This function creates a default `ServeMux` -- no way to influence that. It invokes `vkubelet.AttachPodRoutes` which attaches a bunch of hard coded handlers with said hard coded `mux` and the provider to use.
So when the call ends up at the provider interface it is arriving in preprocessed form (streams decoded etc.) which, as I tried to explain, is not suitable for us.

**Comment by cpuguy83** [comment]
@danielvmw 
> That means we need logic to multiplex those three streams

This seems like a provider concern. Why wouldn't the request from the provider to the backend deal with this?

> What I am getting at it that nothing of this is customizable by client code

I've brought this up a few times with other people, I really want to push people to build their own implementations rather than piling everything into a generic virtual-kubelet binary. It will be a much better experience for all involved, I think.

But also again as I mentioned above, why wouldn't the provider broker this?

**Comment by cpuguy83** [comment]
One more concern here, the `GetPods` API is not great, particularly because this can consume lots of memory if there are many pods to fetch. Maybe something like this could work:

```go
ForEach(func(*v1.Pod) error)
```

But maybe this is even lower level than we really need.
What this would really only be used for is initial state reconciliation on startup.

**Comment by cpuguy83** [comment]
I've updated the proposed interface to split out the container level actions into a separate interface. These are only called by the HTTP handlers and not the vk core reconciliation loops. I thought it was fitting to split them for this reason.
Also added port forwarding to this interface.

**Comment by srrengar** [comment]
@VDuleb can you take a look at what this would mean for the ACI provider

**Comment by cpuguy83** [comment]
These changes have been implemented.
The one thing that was not is a means of iterating over pods in the provider without having to instantiate all in memory at once.
We can address this separately as it does not necessarily mean we need to change the provider interface, and if can be done in an additive way.
