### ISSUE TITLE
Point users to official website

### ISSUE THREAD

**Issue by lucperkins** [virtual-kubelet/virtual-kubelet#525]
As it stands, there's no indication in this repository that there's an official website for VK at https://virtual-kubelet.io. This should be added to the repo description and mentioned in the README.

**Comment by rbitia** [comment]
Agreed. I'll work on this.

**Comment by lucperkins** [comment]
The official website is now linked in the repo description. In the future we should decided on a division of labor between the official docs and the README but this should be good for now.
