### ISSUE TITLE
Clarify "inside" vs. "outside" in the documentation

### ISSUE THREAD

**Issue by lucperkins** [virtual-kubelet/virtual-kubelet#545]
To write the [VK usage docs](https://virtual-kubelet.io/docs/usage/) I borrowed liberally from the README, which speaks in terms of "inside" and "outside" a Kubernetes cluster. This language is pretty confusing. We should refine the language and standardize on some terms.

**Comment by rbitia** [comment]
Yeah or maybe "with or without a Kubernetes cluster." Are there other projects with needs for a similar language? Maybe we should check in to see what they do
