### ISSUE TITLE
Connection to master server fails after executing kubectl exec

### ISSUE THREAD

**Issue by rkttu** [virtual-kubelet/virtual-kubelet#556]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
Azure ACI

Version (e.g. 0.1, 0.2-beta)
0.5.0

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
Docker for Desktop (Windows)

Install Method (e.g. Helm Chart, )
Helm Chart

### Issue Details
We succeeded in distributing Windows Pod and Linux Pod one by one using ACI Connector. If you then use the kubectl exec to connect to the Pod, it will succeed at first. If you then use the kubectl command to connect to another pod, all requests to the API server will fail.

It displayed as below.

```
Microsoft Windows [Version 10.0.18356.16]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\rkttu>kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout
```

### Repro Steps
a. Install Virtual Kubelet into Docker for Desktop (Windows) kubernetes cluster with linux and windows virtual node
b. Deploy two pods (Windows, Linux pod)
c. Try connect to any running pod with exec command.
d. Close the session, and try issue any kubectl command.

**Comment by srrengar** [comment]
we don't support this scenario
