### ISSUE TITLE
GCP Cloud Run provider for VK

### ISSUE THREAD

**Issue by Pothulapati** [virtual-kubelet/virtual-kubelet#577]
GCP announced [Cloud Run](https://cloud.google.com/run/) recently, which is a way to run HTTP containers _serverlessly_ . It should be a very interesting provider for VK Because it follows the same Knative API, so supporting this would also allow VK to offload workloads to both Induvidual Clusters running Knative API and Cloud Run.

Iam willing to work on this, So Just wanted to give a heads up!

Thanks :smile: 

cc @rbitia @cpuguy83 @pires

**Comment by pires** [comment]
Hey @Pothulapati! Thank you for the idea. However, the goal right now for VK is to move providers out-of-tree and ultimately have VK as a library one can use to build their providers. This means to me adding providers is not something we should look for at this point.

**Comment by cpuguy83** [comment]
You should be able to build an integration out of tree at this point.
The package level API's are still subject to some change, though there shouldn't be much movement outside of what's opened in PR's now.

**Comment by innerop** [comment]
Hi,

is there any community activity at this point around the idea of people building their own provider integrations? 

I'm interested in the KNative provider.

**Comment by pires** [comment]
@innerop definitely! There are many providers out there that leverage VK. Examples are the Azure ACI, AWS Fargate or systemk, all of them versioned in repos under this same organization.

**Comment by pires** [comment]
I'm closing this as we haven't seen anyone stepping up to address the requested provider.
