### ISSUE TITLE
Consider Adding Timeout in cache.WaitForCacheSync

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#594]
This can last forever: https://github.com/virtual-kubelet/virtual-kubelet/blob/1942522cf6ac050eb84ac437d3f28788035dea5d/vkubelet/podcontroller.go#L123-L125

The node will show up, and continue to heartbeat, but never get back into sync. I suggest two things:
1. That the node doesn't show up as up until this completes
2. We add a timeout here that's reasonable, or configurable.

**Comment by sargun** [comment]
See: https://github.com/virtual-kubelet/virtual-kubelet/pull/597

**Comment by sargun** [comment]
Fixed!

**Comment by srinat999** [comment]
Hi. I'm facing this issue too. What was the solution at the end? I tried using --startup-timeout option, but the startup just exits once the timeout has reached.
