### ISSUE TITLE
Azure Provider Virtual-kubelet not start with Error

### ISSUE THREAD

**Issue by dotnetstep** [virtual-kubelet/virtual-kubelet#601]
I get following error. ( this is message from kubectl log <<pod>>

Flag --taint has been deprecated, Taint key should now be configured using the VK_TAINT_KEY environment variable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b33d27]

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/cmd.setupHTTPServer.func2(0xc000a5bb80, 0xc000a5bb78)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/http.go:56 +0x37
github.com/virtual-kubelet/virtual-kubelet/cmd.setupHTTPServer(0x2594b80, 0xc000623280, 0xc00008d400, 0x0, 0x256bfe0, 0xc00052bd40)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/http.go:68 +0x853
github.com/virtual-kubelet/virtual-kubelet/cmd.glob..func1(0x3de34a0, 0xc0003e7720, 0x0, 0xa)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:111 +0x32c
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).execute(0x3de34a0, 0xc00004a0c0, 0xa, 0xa, 0x3de34a0, 0xc00004a0c0)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:760 +0x2cc
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3de34a0, 0x3de34a0, 0xc000a5bf30, 0x1)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).Execute(0x3de34a0, 0x405700, 0xc0000560b8)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/virtual-kubelet/virtual-kubelet/cmd.Execute()
        /go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:126 +0x31
main.main()
        /go/src/github.com/virtual-kubelet/virtual-kubelet/main.go:20 +0x20

**Comment by cpuguy83** [comment]
Fixed by #579
