### ISSUE TITLE
Pod Status Updates can be delivered out-of-order

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#602]
If you use the async provider implementation, under cases of heavy load, your updates can be delivered out of order because there's no per-pod serialization on the queue. In addition, since we don't have a round-trip necessarily to fully order the pod status updates, you get into a permanently bad state.

**Comment by sargun** [comment]
Easy solution: Rather than having N workers read off 1 queue -- create N queues, for N workers, and at queue time do per-pod assignment to a queue.

**Comment by cpuguy83** [comment]
Can you explain further?
Right now the notification is added to a queue with just the `<namespace>/<name>` key, when the worker processes the notification it must fetch the pod to work on it.

**Comment by sargun** [comment]
@cpuguy83 It seems like there can be multiple workers working on the same `<namespace>/<name>` at the same time.

The pattern seems:
1. Worker 1 gets a work item for default/pod1
2. Worker 2 gets a work item for default/pod1
3. Worker 1 does a GetPodStatus
4. Worker 2 does a GetPodStatus 
-- At this point Worker 2's pod status is "in the future" compared to worker 1.
Worker 2 does a write, and updates the pod status. 
Worker 1 does a write and it reverts the pod status.

**Comment by cpuguy83** [comment]
But shouldn't the queue be preventing multiple entries of the same item?

**Comment by sargun** [comment]
hrm, you're right. I wonder if the pod is getting recreated and put in the pending state by something else.
