### ISSUE TITLE
Dependency hell / import loop from mock to vkubelet package

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#632]
If we want to use any of the interfaces from the vkubelet in mock (for example, if you want to assert that you implement the PodNotifier interface), you cannot, because pod_test in vkubelet uses the mock provider to test.

This is due to a combination of:
* https://github.com/virtual-kubelet/virtual-kubelet/pull/626
* https://github.com/virtual-kubelet/virtual-kubelet/pull/613

It'd be nice if either pod_test wasn't in the vkubelet package, the pod notifier interface was moved out of the vkubelet package.

**Comment by sargun** [comment]
CC: @cpuguy83 @jeremyrickard

**Comment by cpuguy83** [comment]
I don't like either of these solutions.
For a the "remove server object" pr I just changed the one call in the mock provider to not call into the providers package.

Really we can make a mock in vkubelet for testing instead.
