### ISSUE TITLE
Cut a 1.0 Release

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#636]
We are announcing 1.0 this week at KubeCon and we'd like to cut a symbolic 1.0 release this week. All the core maintainers should sign off on this issue before we cut the release. Also core maintainers, please comment on this issue with blocking issues or PRs for 1.0. Let's focus on pushing those forward for the next day or two!!

**Comment by cpuguy83** [comment]
I've pruned down the milestone, not that it is neccessarily an exhaustive list.

**Comment by pires** [comment]
I've added this issue to the same milestone.

**Comment by rbitia** [comment]
@pires @corrieb @cpuguy83  as core maintainers can you ack that we are ready to cut a 1.0 release? 

I myself believe we are. :)

**Comment by pires** [comment]
@rbitia I do think we are ready but I'd like to propose we wait a few days for some community folks to validate the state of things while they build their provider from scratch. I'm looking specifically at @gabrielhartmann and a good example already is #676. This would definitely increase my confidence in all of the recent changes.

**Comment by pires** [comment]
Also #674 seems like something you want to get in too, right @cpuguy83?

**Comment by cpuguy83** [comment]
Ok, tagging the 1.0 release now.

**Comment by cpuguy83** [comment]
https://github.com/virtual-kubelet/virtual-kubelet/releases/tag/v1.0.0

Preparing a blog post.
Also need to deal with helm charts, probably sooner rather than later.
I'm checking with the ACI team if they are depending on these charts at all.
