### ISSUE TITLE
Multiple vNet support for ACI

### ISSUE THREAD

**Issue by devblackops** [virtual-kubelet/virtual-kubelet#644]
It doesn't appear possible now, but would it be feasible in the future to have a single AKS instance support multiple vNets and allow vNet selection with deploying to ACI?

Reasoning: I'm exploring ways to manage multiple instances of an application with full network isolation from each other but minimize the number of AKS instances to manage.

**Comment by srrengar** [comment]
I don't think this is on the roadmap, but you could potentially have those apps in different subnets and isolate that way?

**Comment by devblackops** [comment]
It's my understanding (I could be wrong!) that the container groups are always deployed into the single subnet and we're not able to specify another one.

**Comment by srrengar** [comment]
Yeah that is correct, I thought you were talking about apps on the AKS cluster too. This is good feedback though and we'll consider having a subnet selection in the future for pods deployed to ACI.

**Comment by srrengar** [comment]
This is on our roadmap now, closing this issue
