### ISSUE TITLE
Introduce a management agent

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#655]
Right now there is a lot of setup for consumers of the core.
It would be nice to introduce some sort of agent for setting up and managing the node and pod controller.

This could basically take a `kubernetes.Client` and node config, then handle the initialization... basically much of what is in `cmd/virtual-kubelet/commands/root/root.go` right now.

For performance the agent could allow callers to optionally pass in things like pre-created informers.

**Comment by pires** [comment]
I like this idea! We should aim to remove any setup that isn't strictly managed by the VK pieces.

**Comment by cpuguy83** [comment]
I don't think we'll need to break anything.
This would be a new object that consumers can use if they want to.
This would end up being a 1.X release.

**Comment by pires** [comment]
Oh, if it's opt-in, OK then.

**Comment by cpuguy83** [comment]
This was added in node/nodeutil
