### ISSUE TITLE
https://github.com/Azure-Samples/virtual-node-autoscale/issues/40

### ISSUE THREAD

**Issue by anujgeek** [virtual-kubelet/virtual-kubelet#656]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, )

**Comment by cpuguy83** [comment]
Is this an issue?
