### ISSUE TITLE
Feature Request: make pod's cidr configurable in mock provider

### ISSUE THREAD

**Issue by varuzam** [virtual-kubelet/virtual-kubelet#677]
hello
I would like to use the virtual kubelet as ephemeral kubernetes node to expand cluster network across all servers. Is it possible to make pod cidr configurable in mock provider?

**Comment by k4korea** [comment]
I am also interested.
If you have any progress, please

**Comment by cpuguy83** [comment]
I do not understand this request.
The mock provider here an internal tool for e2e tests.
If you need a mock as well, please copy and use as needed... honestly I even find the mock provider annoying to use because of the weird config format.

Closing since folks should just build the mock they need.
