### ISSUE TITLE
Allow Runtime Definition of Node Annotations

### ISSUE THREAD

**Issue by gabrielhartmann** [virtual-kubelet/virtual-kubelet#678]
---

### Environment summary

Provider: Generic
Version: N/A
K8s Master Info: Bare metal
Install Method: Custom

### Issue Details

Authors of Providers are unable to provide Annotations on Node metadata in the current `NodeFromProvider` function in `node.go`.  These Annotations are potentially important to arbitrary Kubernetes deployments.

Various fields are currently populated in the status and metadata subsections of the Node object today.  Further extension of the current mechanism of Node definition from the provider is undesirable.  See PR #676.  A new method of defining nodes with input from the provider authors is therefore needed.

### Repo Steps
N/A

**Comment by cpuguy83** [comment]
Thanks for opening this.

What I propose is to add something like this to the provider interface

```
InitializeNode(*corev1.Node)
```

This would replace the existing functions like `Capacity`, etc.
I say to handle it like this so we can set VK defaults, such as taints which is configured through the CLI anyway... but it gives the provider a chance to change whatever they need to in the node spec.
