### ISSUE TITLE
[Azure] VK Node deleted 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#68]
The node deleted itself while the pod is still running. I didn't remove the connector or delete the node. 

Rias-MBP:community riabhatia$ kubectl get po
NAME                                                    READY     STATUS    RESTARTS   AGE
demo-fr-backend-867bc8fc46-xdj7l                        1/1       Running   0          2h
demo-fr-frontend-5577d588f9-m647s                       1/1       Running   0          2h
demo-fr-ir-5d6954684f-l4wqb                             1/1       Running   0          2h
demo-fr-ir-aci-67cd7d8bb8-5r8k5                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-5s9pk                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-66m5n                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-lfvh6                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-lsw85                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-snl72                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-szjkq                         0/1       Pending   0          14s
demo-fr-ir-aci-67cd7d8bb8-tldbr                         0/1       Pending   0          14s
demo-fr-ir-aci-847b4c59f8-28d9q                         0/1       Pending   0          14s
demo-fr-ir-aci-847b4c59f8-8fkqq                         0/1       Pending   0          14s
demo-fr-ir-aci-847b4c59f8-8t74k                         0/1       Pending   0          14s
demo-fr-ir-aci-847b4c59f8-b6w8b                         0/1       Pending   0          14s
demo-fr-ir-aci-847b4c59f8-v54nd                         0/1       Pending   0          14s
myaciconnector-linux-virtual-kubelet-76864d69dd-lq4ff   1/1       Running   3          2h
Rias-MBP:community riabhatia$ kubectl logs myaciconnector-linux-virtual-kubelet-76864d69dd-lq4ff
/.kube/config
2018/01/22 21:48:56 Node 'virtual-kubelet-myaciconnector-linux' with OS type 'Linux' registered
2018/01/22 21:48:56 open : no such file or directory
2018/01/22 21:49:46 Failed to retrieve node: nodes "virtual-kubelet-myaciconnector-linux" not found
2018/01/22 21:50:31 Failed to retrieve node: nodes "virtual-kubelet-myaciconnector-linux" not found
2018/01/22 21:51:16 Failed to retrieve node: nodes "virtual-kubelet-myaciconnector-linux" not found

**Comment by robbiezhang** [comment]
I hit this issue once because I call `aks install-connector` right after `aks remove-connector`. The VK doesn't re-register or update the status of the node since during that period, a phantom node is still there. The issue should have been fixed in the new `az aks remove-connector` (2.0.27). If you still use the old, the workaround it to delete the node explicitly after you run the `aks remove-connector` or wait for 1 minute before run `aks install-connector`.

**Comment by rbitia** [comment]
expected behavior so closing
