### ISSUE TITLE
GetPodStatus called after DeletePod

### ISSUE THREAD

**Issue by gabrielhartmann** [virtual-kubelet/virtual-kubelet#684]
### Environment summary

Provider: Generic

Version: N/A

K8s Master Info: bare metal

Install Method: custom

### Issue Details
The Provider interface has methonds: `GetPodStatus` and `DeletePod`.  `GetPodStatus` should not be called after `DeletePod`.  This can happen today if `DeletePod` initiates a call to the `PodNotifier` to update the final status of a pod.  For example the behavior below is common.

```
Provider.DeletePod(foo)
    Remove pod from in-memory map of pods
    Kill container
    Call PodNotifier with updated pod status
Provider.GetPodStatus(foo)!
```

### Repo Steps
Call the PodNotifier from within `Provider.DeletePod`

**Comment by gabrielhartmann** [comment]
This bug boils down to the [behavior defined here](https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/queue.go#L56-L58).  Quote:
```
// We expect strings to come off the work queue.
// These are of the form namespace/name.
// We do this as the delayed nature of the work queue means the items in the informer cache may actually be more up to date that when the item was initially put onto the workqueue.
```
Because the queue really only takes pods as `namespace/name` keys it must always query the `Provider` to get the latest state of a pod.  Event handlers subsequently use this more recent version of the pod.

**Comment by cpuguy83** [comment]
The queue works this way because we can end up getting multiple status updates... or basically the underlying pod state can change and we don't want to work with outdated information.

I agree this is funky for `DeletePod`.
perhaps `DeletePod`'s signature should be updated to return a pod status as well?

**Comment by gabrielhartmann** [comment]
We could change the `DeletePod` interface, but I'd like to understand why multiple status updates is a problem, or outdated information is a problem.  If the pod transitions through intermediate states and arrives at the final status, all is well right?

**Comment by cpuguy83** [comment]
>  If the pod transitions through intermediate states

This requires updates to be processed in order, one at a time.
We also don't want unnecessary updates to the API server.

The other side of this is when we call `DeletePod`, currently we actually delete the pod from Kubernetes (though as I recall the error handling logic is a bit off and needs to be addressed), which means we aren't going to be able to apply any pod status updates anyway.

**Comment by gabrielhartmann** [comment]
> > If the pod transitions through intermediate states
> 
> This requires updates to be processed in order, one at a time.
> We also don't want unnecessary updates to the API server.
Processing updates in order, one at a time sounds like a good idea to me as long as each pod's updates are processed independently and deduplication logic is in place.

> The other side of this is when we call `DeletePod`, currently we actually delete the pod from Kubernetes (though as I recall the error handling logic is a bit off and needs to be addressed), which means we aren't going to be able to apply any pod status updates anyway.

Yes this is related to #681 and #587.  Terminal states of pods are important and are currently lost / unable to be propagated.

**Comment by gabrielhartmann** [comment]
Looking at the code changing the interface of `DeletePod` seems complicated given its interaction with the queueing system.  We may be able to address this issue and the others referenced above by decoupling the killing of a pod from the garbage collection of its representation.

The GC of pods could be driven by a component making decisions based on the GracePeriod.   It would observe API server state.  When pods marked for deletion exceed their grace period, Providers would be notified that it's time to GC a pod.  The response to this Provider API call could also indicate if VK should proceed with deleting the Pod object from the API server.

**Comment by cpuguy83** [comment]
If I understand your suggestion, you want to split termination from deletion. Is that correct?
I think this makes sense.

**Comment by gabrielhartmann** [comment]
Yes.  Termination of a pod and deletion should be separated.

**Comment by sargun** [comment]
Fixed: https://github.com/virtual-kubelet/virtual-kubelet/pull/751

**Comment by sargun** [comment]
Fixed: https://github.com/virtual-kubelet/virtual-kubelet/pull/751
