### ISSUE TITLE
make skaffold is broken

### ISSUE THREAD

**Issue by pires** [virtual-kubelet/virtual-kubelet#693]
The `README.md` we provide mentions at least three `skaffold` related calls, `make skaffold`, `make skaffold MODE=run` and `make e2e`. The first two are broken, at least on MacOS:

```
$ make skaffold
make: Circular skaffold <- skaffold dependency dropped.
make: Nothing to be done for `skaffold'.
```

```
$ make skaffold MODE=run
skaffold run \
		-f /Users/pires/work/virtual-kubelet/hack/skaffold/virtual-kubelet/skaffold.yml \
		-p local
Generating tags...
 - virtual-kubelet -> virtual-kubelet:v0.11.1-6-gcd0abc4d-dirty
Tags generated in 22.50431ms
Starting build...
Found [minikube] context, using local docker daemon.
Building [virtual-kubelet]...
Sending build context to Docker daemon

FATA[0000] failed to build: build failed: building [virtual-kubelet]: build artifact: docker build: error during connect: Post https://192.168.64.3:2376/v1.38/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=hack%2Fskaffold%2Fvirtual-kubelet%2FDockerfile&forcerm=1&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=virtual-kubelet%3Av0.11.1-6-gcd0abc4d-dirty&target=&ulimits=null: creating docker context: getting relative tar paths: file pattern [bin/e2e/virtual-kubelet] must match at least one file
make: *** [skaffold/run] Error 1
```

@cpuguy83 this is the result of the changes in #564. Can you, please, fix, so that the commands above work again? Thank you!

**Comment by cpuguy83** [comment]
I do not see these errors.
Though for me `make skaffold` is not working as expected, it seems to be calling `skaffold/.o` instead of `skaffold/$(MODE)`.
If I change the definition form

```Makefile
skaffold: skaffold/$(MODE)
```

to:
```Makefile
skaffold:
  $(MAKE) sakffold/$(MODE)
```

it seems to work for me.
But again I'm not seeing the errors you mention in any case.

**Comment by cpuguy83** [comment]
Ok, I see.
`make skaffold` (no mode) is not working because `$(MODE)` is evaluated before `MODE` is set

```
skaffold: MODE ?= dev
skaffold: skaffold/$(MODE)
```

And then if I set a mode on the CLI indeed I see the 2nd error you mentioned.
This occurs when `bin/e2e/virtual-kubelet` does not exist.
So setting `bin/e2e/virtual-kubelet` as a pre-req for `skaffold/%` would seem to do the trick.

**Comment by pires** [comment]
> So setting bin/e2e/virtual-kubelet as a pre-req for skaffold/% would seem to do the trick.

That means that `make skaffold/delete` or `make skaffold MODE=delete` would run `bin/e2e/virtual-kubelet`, right?

**Comment by cpuguy83** [comment]
Yes, so instead I made it explicit to only be a pre-req on `skaffold/run` and `skaffold/dev`
