### ISSUE TITLE
How to do inter cluster networking ?

### ISSUE THREAD

**Issue by atakanyenel** [virtual-kubelet/virtual-kubelet#713]
I have Rpi with virtual kubelet installed. I have processes running on it exposing a localhost port. I believe (not yet implemented) I can reach the Rpi processes by returning the ipv6 address as `hostIP` and exposed ports as `podIP->"localhost:PORT"`.

How does it work the other way around ? How can I send a request from RPi Processes created by virtual kubelet to an internal service like `http://my-service`. I'm assuming that the ACI instances have a virtual network between them or they are using public-ips in the demo to communicate ?

I can update /etc/hosts file, but that would only work for publicly reachable services. I can't get my head around how that would work only with virtual kubelet and maybe kubectl.

Is this possible ?

**Comment by cpuguy83** [comment]
@atakanyenel Networking is totally handled by the provider.
In ACI containers either get a public IP or indeed run on a private vnet.

**Comment by atakanyenel** [comment]
Thanks. I will close the issue tomorrow, if no comments come up.
