### ISSUE TITLE
Illegal base64 data when using imagePullSecrets

### ISSUE THREAD

**Issue by gabrtv** [virtual-kubelet/virtual-kubelet#73]
Receiving the following error when using `imagePullSecrets` specified in the default service account:

```
2018/01/25 20:48:15 Error creating pod 'demo-fr-ir-aci-547fdc6c66-wjz7z': illegal base64 data at input byte 0
```

Removing the `imagePullSecret` from the service account resolves the error.  Note the same pull secret is working for other non-VK workloads.

**Comment by robbiezhang** [comment]
Guess it's because we don't support all types of image pull secrets.

https://github.com/virtual-kubelet/virtual-kubelet/blob/3668b0d6b9973df14646fd23e5824d1fb95c981c/providers/azure/aci.go#L367-L369

@gabrtv, can you send me the pod spec the image pull secret?
