### ISSUE TITLE
broken links in virtual-kubelet docs

### ISSUE THREAD

**Issue by rugwirobaker** [virtual-kubelet/virtual-kubelet#737]
### Issue Details
On the page about [providers](https://virtual-kubelet.io/docs/providers/) there some links that are supposed to lead to code examples of the `Provider interface` implementation but they don't work. 

At first I thought it was one link but after further investigation it seems all the links in that page leading to code docs or examples don't work.

**Comment by rbitia** [comment]
@lucperkins are you able to fix this? :D

**Comment by lucperkins** [comment]
@rbitia I can try to fix this but I'd recommend appointing somebody from amongst the VK maintainers to keep the site/docs in sync with changes in VK. I'm not sure, for example, what has happened to the `Provider` interface and wasn't aware that the provider implementations have been moved to separate repos.

**Comment by lucperkins** [comment]
@rbitia Okay, I looked into this and I will unfortunately need to defer to others on this. The provider doc is essentially deprecated and will need to be rewritten, preferably by someone "closer to the metal" 😀

**Comment by cpuguy83** [comment]
Best pace for docs right now would be godoc.
https://godoc.org/github.com/virtual-kubelet/virtual-kubelet

Will need to look into changes for the website.

**Comment by cpuguy83** [comment]
I'm taking the next couple of weeks off so it may take some time to be able to update this.

**Comment by rbitia** [comment]
@lucperkins can we close this issue? Looks like @chewong provided some updates.

**Comment by lachie83** [comment]
I believe this issue is resolved via PR #754. We can close this
