### ISSUE TITLE
virtual kubelet on prem

### ISSUE THREAD

**Issue by matancarmeli7** [virtual-kubelet/virtual-kubelet#752]
---
I have kubernetes cluster on several vms in on prem environment and i want to connect to it several raspberry pi devices, i want to be able to run pods on the raspberry pi devices and control it from the kubernetes cluster.  Can i use virtual kubelet in this case or i just can add the raspberry pi devices as worker nodes to the kubernetes cluster?

**Comment by cpuguy83** [comment]
In the general case I would recommend to add the Pi's as worker nodes on the cluster.

VK can, however, be used to do any number of things. It only provides the API's and runtime for operating a node in k8s, the actual implementation for how
