### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#756]
There are a number of fixes on master that would be nice to have in a patch release for 1.0.

As of this writing it seems like we can just fast-forward 1.0 to master.
The biggest point of contention here (I think) would be that we have updated k8s libs to v1.15 from v1.13 in order to fix some bugs.

**Comment by cpuguy83** [comment]
@sargun suggested to wait until #744 is fixed as well.

**Comment by pires** [comment]
As mentioned over slack, Kubernetes 1.13 will be unsupported in a couple weeks so moving to 1.15 is recommended, if we are to make a new release.

**Comment by cpuguy83** [comment]
On #764 it was decided that this update warrants a minor version bump rather than a patch version bump.

The reason for this is the k8s dependencies being bumped to 1.15 (from 1.13).
As such 1.1.0 was just fast forwarded to master since there are no other significant changes other than some minor features that are isolated changes.

**Comment by cpuguy83** [comment]
The release will be tagged from the release-1.1 branch.

**Comment by cpuguy83** [comment]
Release is done! https://github.com/virtual-kubelet/virtual-kubelet/releases/tag/v1.1.0
