### ISSUE TITLE
cant build virtual-kubelet

### ISSUE THREAD

**Issue by percy143** [virtual-kubelet/virtual-kubelet#757]
---
i am cloning this git repository into the path /root/src/github.com/
my GOPATH=/root/src/
my GOROOT=/root/
my GOBIN="/root/src/github.com/virtual-kubelet/bin"
and i enter /root/src/github.com/virtual-kubelet directory and run the make build command, i get this error:

`which: no gobin in (/bin:/root/src/github.com//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/usr/local/go/bin:/root/bin)
which: no gobin in (/bin:/root/src/github.com//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/usr/local/go/bin:/root/bin)
which: no gobin in (/bin:/root/src/github.com//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/usr/local/go/bin:/root/bin)
which: no gobin in (/bin:/root/src/github.com//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/usr/local/go/bin:/root/bin)
which: no gobin in (/bin:/root/src/github.com//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/root/bin:/usr/local/go/bin:/usr/local/go/bin:/root/bin)
Building...
cmd/virtual-kubelet/main.go:18:2: cannot find package "context" in any of:
        /root/src/context (from $GOROOT)
        /root/src/src/context (from $GOPATH)
cmd/virtual-kubelet/main.go:25:2: cannot find package "github.com/pkg/errors" in any of:
        /root/src/github.com/pkg/errors (from $GOROOT)
        /root/src/src/github.com/pkg/errors (from $GOPATH)
cmd/virtual-kubelet/main.go:26:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /root/src/github.com/sirupsen/logrus (from $GOROOT)
        /root/src/src/github.com/sirupsen/logrus (from $GOPATH)
cmd/virtual-kubelet/main.go:27:2: cannot find package "github.com/spf13/cobra" in any of:
        /root/src/github.com/spf13/cobra (from $GOROOT)
        /root/src/src/github.com/spf13/cobra (from $GOPATH)
cmd/virtual-kubelet/main.go:28:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/providers" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/providers (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/providers (from $GOPATH)
cmd/virtual-kubelet/main.go:29:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root (from $GOPATH)
cmd/virtual-kubelet/main.go:30:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/version" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/version (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/version (from $GOPATH)
cmd/virtual-kubelet/main.go:31:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/provider" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/provider (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/provider (from $GOPATH)
cmd/virtual-kubelet/register.go:5:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/provider/mock" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/provider/mock (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/provider/mock (from $GOPATH)
cmd/virtual-kubelet/main.go:32:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/log" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/log (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/log (from $GOPATH)
cmd/virtual-kubelet/main.go:33:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/log/logrus" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/log/logrus (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/log/logrus (from $GOPATH)
cmd/virtual-kubelet/main.go:34:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/trace" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/trace (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/trace (from $GOPATH)
cmd/virtual-kubelet/main.go:35:2: cannot find package "github.com/virtual-kubelet/virtual-kubelet/trace/opencensus" in any of:
        /root/src/github.com/virtual-kubelet/virtual-kubelet/trace/opencensus (from $GOROOT)
        /root/src/src/github.com/virtual-kubelet/virtual-kubelet/trace/opencensus (from $GOPATH)
cmd/virtual-kubelet/main.go:19:2: cannot find package "os" in any of:
        /root/src/os (from $GOROOT)
        /root/src/src/os (from $GOPATH)
cmd/virtual-kubelet/main.go:20:2: cannot find package "os/signal" in any of:
        /root/src/os/signal (from $GOROOT)
        /root/src/src/os/signal (from $GOPATH)
cmd/virtual-kubelet/main.go:21:2: cannot find package "path/filepath" in any of:
        /root/src/path/filepath (from $GOROOT)
        /root/src/src/path/filepath (from $GOPATH)
package github.com/virtual-kubelet/cmd/virtual-kubelet
        imports runtime: cannot find package "runtime" in any of:
        /root/src/runtime (from $GOROOT)
        /root/src/src/runtime (from $GOPATH)
cmd/virtual-kubelet/main.go:22:2: cannot find package "strings" in any of:
        /root/src/strings (from $GOROOT)
        /root/src/src/strings (from $GOPATH)
cmd/virtual-kubelet/main.go:23:2: cannot find package "syscall" in any of:
        /root/src/syscall (from $GOROOT)
        /root/src/src/syscall (from $GOPATH)
make: *** [build] Error 1
`
Are you have any solutions?
Thanks and regards,

**Comment by percy143** [comment]
my GOROOT=/usr/local/go
my GOPATH=/root

**Comment by chewong** [comment]
What is your Go version (`go version`)?

**Comment by cpuguy83** [comment]
virtual-kubelet is a library which does not produce an executable except for testing purposes.

That said there does seem to be some extra stuff in the Makefile that's no longer needed, including this lookup for `gobin`

**Comment by MIBc** [comment]
I think you should download vendor with `go mod`  first.
