### ISSUE TITLE
Fail to build new project depending on virtual-kubelet v1.1.0 with go1.13

### ISSUE THREAD

**Issue by uzuku** [virtual-kubelet/virtual-kubelet#767]
---

### Environment summary

go version
go1.13 darwin/amd64

### Issue Details

Fail to build a new project depending on `github.com/virtual-kubelet/virtual-kubelet/log` with go1.13

After i set up the repo and try to build for the first to resolve all the dependencies with `go build`

![image](https://user-images.githubusercontent.com/42673593/65431568-45b6cf00-de4c-11e9-9b2c-4f1d41f0442a.png)

no error occurs if i run `go get github.com/virtual-kubelet/virtual-kubelet@v1.0.0` first to change the version of virtual kubelet to 1.0.0.

I think the following lines in go.mod is to blame:

https://github.com/virtual-kubelet/virtual-kubelet/blob/release-1.1/go.mod#L41-L42

### Repo Steps

Set up a new go repo and import `github.com/virtual-kubelet/virtual-kubelet/log`, do whatever and run `go mod init example.com/foo/bar && go build` with go1.13.

sample code looks like following

```go
package main

import (
	"context"

	"github.com/virtual-kubelet/virtual-kubelet/log"
)

func main() {
	log.G(context.TODO()).Info("i am main")
}

```

**Comment by Uzuku** [comment]
Also fail on go1.12.6 with GO111MODULE=on, no luck
![image](https://user-images.githubusercontent.com/42673593/65434450-69c8df00-de51-11e9-88c3-bb4ca76ce75b.png)

**Comment by sargun** [comment]
@Uzuku Can you copy and paste the following into your go.mod:

```

replace k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20190805144654-3d5bf3a310c1

replace k8s.io/cloud-provider => k8s.io/cloud-provider v0.0.0-20190805144409-8484242760e7

replace k8s.io/cli-runtime => k8s.io/cli-runtime v0.0.0-20190805143448-a07e59fb081d

replace k8s.io/apiserver => k8s.io/apiserver v0.0.0-20190805142138-368b2058237c

replace k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.0.0-20190805144531-3985229e1802

replace k8s.io/cri-api => k8s.io/cri-api v0.0.0-20190531030430-6117653b35f1

replace k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.0.0-20190805142416-fd821fbbb94e

replace k8s.io/kubelet => k8s.io/kubelet v0.0.0-20190805143852-517ff267f8d1

replace k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.0.0-20190805144128-269742da31dd

replace k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190612205821-1799e75a0719

replace k8s.io/api => k8s.io/api v0.0.0-20190805141119-fdd30b57c827

replace k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.0.0-20190805144246-c01ee70854a1

replace k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20190805143734-7f1675b90353

replace k8s.io/component-base => k8s.io/component-base v0.0.0-20190805141645-3a5e5ac800ae

replace k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20190805144012-2a1ed1f3d8a4

replace k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20190805143126-cdb999c96590

replace k8s.io/metrics => k8s.io/metrics v0.0.0-20190805143318-16b07057415d

replace k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20190805142637-3b65bc4bb24f

replace k8s.io/code-generator => k8s.io/code-generator v0.0.0-20190612205613-18da4a14b22b

replace k8s.io/client-go => k8s.io/client-go v0.0.0-20190805141520-2fe0317bcee0
```

**Comment by Uzuku** [comment]
@sargun It works after i paste the replace statements into go.mod.
However i think it is necessary to do some fix here, as module indirectly depending on vk though my module will still fail, so currently i choose to explicitly depend on vk v1.0.0 to avoid it.
i tried to figure the fix out, but it seems that the v0.0.0 version of k8s.io/api is from k8s.io/kubernetes 1.15.2.

**Comment by Uzuku** [comment]
Accidently close the issue...Reopen it

**Comment by sargun** [comment]
How do you suggest we fix it?

**Comment by Uzuku** [comment]
@sargun I think depending on k8s internal packages is fine, as v1.0.0 also has these dependencies and do not trigger such problem. The concern is which version of k8s vk is depending on.

I digged it a little and find that the v1.0.0 depends on k8s.io/kubernetes v1.13.7, which didn't migrate to go mod yet, so version of k8s.io/api is resolved separately. But for k8s.io/kubernetes v1.15.2 depended by v1.1.0, kubernetes has migrated to go mod and it seems that vk just use the version claimed by go mod in kubernetes (which is v0.0.0, kubernetes also replaces it). 

I've tried following code to show the case.

 ***

case 1:

directly import k8s.io/api

```
package main

import (
	"fmt"

	corev1 "k8s.io/api/core/v1"
)

func main() {
	fmt.Println(corev1.PodFailed)
}
```

go1.13 can get on well with this module:

![image](https://user-images.githubusercontent.com/42673593/65668680-b93b2500-e074-11e9-885a-2a1d3a375f1a.png)


***

case 2:

import k8s.io/kubernetes to indirectly import k8s.io/api

```
package main

import (
	"fmt"

	"k8s.io/kubernetes/pkg/api/v1/pod"
)

func main() {
	fmt.Println(pod.Visitor("aaa"))
}
```

similar error is triggered

![image](https://user-images.githubusercontent.com/42673593/65669009-6150ee00-e075-11e9-8747-e965321488b4.png)

***

case 3:

import  both k8s.io/kubernetes and k8s.io/api directly.

```
package main

import (
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/kubernetes/pkg/api/v1/pod"
)

func main() {
	fmt.Println(pod.Visitor("aaa"))
	fmt.Println(corev1.PodFailed)
}
```

just like case 2:

![image](https://user-images.githubusercontent.com/42673593/65669414-14b9e280-e076-11e9-9d2d-a5474670a6cb.png)


***

So it seems an upstream issue (k8s.io/kubernetes), we should resolve it there and let vk import a resolved version of k8s.io/kubernetes, and before that version bump of vk should be carefully evaluated.

**Comment by Uzuku** [comment]
https://github.com/kubernetes/kubernetes/issues/81878

seems that related issue has been opened in upstream.

**Comment by sargun** [comment]
This should be fixed with the work done by @adrienjt.

**Comment by sargun** [comment]
(or at least much better)
