### ISSUE TITLE
[VK] If the pod is removed from the provider, VK behaves badly

### ISSUE THREAD

**Issue by robbiezhang** [virtual-kubelet/virtual-kubelet#78]
If the pod is removed from the provider, the VK will not re-create it, but continue getting the pod repeatedly. It might cause the provider throttling.

**Comment by rbitia** [comment]
To be fixed eventually..

**Comment by cpuguy83** [comment]
Is this fixed by #227?

**Comment by robbiezhang** [comment]
Yes, the throttling issue is fixed. 
I'm wondering whether we should reconcile the pods, since the pods in provider side seems out of sync. Currently, we only reconcile on ADD/UPDATE/DELETE pod event.

**Comment by rbitia** [comment]
Robbie says it's fixed so closing for now!
