### ISSUE TITLE
VK v1.1.0 crash when provider returns nil, nil from GetPodStatus() during new creations

### ISSUE THREAD

**Issue by ibabou** [virtual-kubelet/virtual-kubelet#781]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
ACI

Version (e.g. 0.1, 0.2-beta)
VK 1.1.0

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS

Install Method (e.g. Helm Chart, )
Manual

### Issue Details
Crash happens when GetPodStatus() returns nil, nil (which currently the behavior in ACI's provider when it is not found). The crash happens for the newly created pods, while syncing its state from provider.

### Repo Steps
This doesn't happen in current officially published connector. it got discovered while testing the move to v1.1.0 within ACI repo.

Fix: For now, i'll change the provider behavior to return NotFound error. The sync loop code got removed now, but @cpuguy83  mentioned it might be re-added. Anyway, we can patch v1.1.0 and change the following:

`(in func (pc *PodController) fetchPodStatusFromProvider()):
podStatus.ContainerStatuses[i].State.Running = nil } } else if err != nil { return nil, nil } } else if err != nil { return nil, err } pod := podFromKubernetes.DeepCopy() podStatus.DeepCopyInto(&pod.Status)`
to
`podStatus.ContainerStatuses[i].State.Running = nil } } else { //<-- here, so podStatus is not accessed while nil --> return nil, nil } } else if err != nil { return nil, err } pod := podFromKubernetes.DeepCopy() podStatus.DeepCopyInto(&pod.Status)`

PR in ACI repo: [here](https://github.com/virtual-kubelet/azure-aci/pull/19)

**Comment by cpuguy83** [comment]
FYI we released 1.2.0.
We re-added support for synchronous providers. The crash should be fixed in the new implementation.
