### ISSUE TITLE
No version higher than 0.9.1 for AKS

### ISSUE THREAD

**Issue by scabana** [virtual-kubelet/virtual-kubelet#782]
There seems to be no available image for provisioning a virtual-kubelet when running in AKS. No docke image seem to have been published since 0.9.1: https://hub.docker.com/r/microsoft/virtual-kubelet/tags?page=1

Is this the right repo? The helm chart source seems to be from here.

Thanks!

**Comment by cpuguy83** [comment]
This should go into github.com/virtual-kubelet/azure-aci
The team is aware and is preparing a release based on VK 1.1.

Thanks for reporting!
