### ISSUE TITLE
kubectl exec api conn idleTimeout 30s too short.

### ISSUE THREAD

**Issue by lauly** [virtual-kubelet/virtual-kubelet#791]
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/api/exec.go
This code file ###idleTimeout := time.Second * 30### is too short,Can I config the idleTimeout param?

**Comment by cpuguy83** [comment]
If the Kubelet API has a param for this we could add support for it.
Otherwise, the design of this package is such that you can bring your own handlers.

**Comment by cwdsuzhou** [comment]
I have the same issue

/help
