### ISSUE TITLE
Kubernetes Provider

### ISSUE THREAD

**Issue by weiwei04** [virtual-kubelet/virtual-kubelet#798]
I am new to virtual-kubelet and invesgating to use virtual-kubelet to implement a cluster federation. But in the project readme it's not recommend  to use virtual-kubelet to implement kubernetes federation "However, it should be noted that VK is explicitly not intended to be an alternative to Kubernetes federation". 

Like https://github.com/virtual-kubelet/virtual-kubelet/issues/32#issuecomment-352956441  kubernetes federation v1/v2 are too complicated for our use cases. In our use cases, we only use Deployment, Job and Pod, we want to implement a kubernetes provider, one virtual-kubelet per real kubernetes cluster, and join these virtual-kubelet to master kubernetes cluster, and user use master apiserver to submit deployment/job, the master cluster controller-manager will create pods for deployment, and scheduler will schedule pod onto node (virtual-kubelet + kubernetes provider), kubernetes provider will create pod in the real cluster and sync pod status between master cluster and virtual-kubelet cluster. 

I want to know if there some weakness or design decision makes virtual-kubelet not suitable for federate kubernetes clusters. Our use case is very simple, we only use Deployment, Job and Pod.

**Comment by sargun** [comment]
What aspect of Kubernetes are you trying to scale out in your implementation of K8s federation built on top of Virtual Kubelet?

**Comment by carmark** [comment]
@sargun I have also same requirement as @weiwei04 .  I need to provide a multi-tenant Kubernetes cluster to user, but they will share same super-master kubernetes cluster, like this architecture:

![image](https://user-images.githubusercontent.com/1132167/70874288-768e4680-1fec-11ea-982b-c108b35967f4.png)

**Comment by cpuguy83** [comment]
VK can indeed be made to do this, however there is no way to do things like influence scheduling decisions. There are probably many trade-offs that I could not list here since I have not tried to implement this.

Trying to treat a cluster as a node seems nice in principal but people should definitely be careful relying on that.

**Comment by tghartland** [comment]
I have been trying something like this. Our use case would be for batch processing, so pods have no inter-pod networking requirements, few or no requirements on other cluster resources, multi-cluster is only used to expand the processing capacity (prioritise using clusters in our own data center, bursting to commercial cloud providers when necessary). We would implement scheduling policies with [scheduler extender](https://github.com/kubernetes/community/blob/9a4bfdc2385379f3b4958b039706227381934d1a/contributors/design-proposals/scheduling/scheduler_extender.md).

My WIP is [here](https://gitlab.cern.ch/thartlan/virtual-cluster).

> Trying to treat a cluster as a node seems nice in principal but people should definitely be careful relying on that.

@cpuguy83 could you expand on this?

**Comment by cwdsuzhou** [comment]
We are also trying the similar thing. I think we could do this together @tghartland @cpuguy83

**Comment by cpuguy83** [comment]
If you can influence the scheduler it does change things a bit.

**Comment by cwdsuzhou** [comment]
Based on the latest scheduler framework, we may implement it.

**Comment by adrienjt** [comment]
@weiwei04 @carmark @cwdsuzhou (I'm already in touch with @tghartland :wink:) [multicluster-scheduler](https://github.com/admiraltyio/multicluster-scheduler) implements virtual-kubelet (since last week). It uses a custom multi-cluster scheduling mechanism (with a rather simple resource-based algorithm for now), but I have plans to re-use most of the Kubernetes scheduler. Please let me know what you think of it.

**Comment by cwdsuzhou** [comment]
> @weiwei04 @carmark @cwdsuzhou (I'm already in touch with @tghartland 😉) [multicluster-scheduler](https://github.com/admiraltyio/multicluster-scheduler) implements virtual-kubelet (since last week). It uses a custom multi-cluster scheduling mechanism (with a rather simple resource-based algorithm for now), but I have plans to re-use most of the Kubernetes scheduler. Please let me know what you think of it.

oh, thanks. Looks amazing,  would you like to talk about it with me after I have read the design and code?

**Comment by cwdsuzhou** [comment]
@cpuguy83  @sargun  we have implemented a k8s provider, including a vk scheduler. How could we contribute to this repo.

**Comment by cpuguy83** [comment]
We can add a repo for it in the vk org.
On Wed, Jun 17, 2020 at 3:13 AM GitHub <notifications@github.com> wrote:

“@cpuguy83@sargun we have implemented a k8s provider, including a vk scheduler. How could we contribute to this repo.”

**Comment by cwdsuzhou** [comment]
> We can add a repo for it in the vk org. On Wed, Jun 17, 2020 at 3:13 AM GitHub <notifications@github.com> wrote: “@cpuguy83@sargun we have implemented a k8s provider, including a vk scheduler. How could we contribute to this repo.” — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks @cpuguy83 ,  please let me know if you have added a repo for it or anything else we should do before you add the repo.

**Comment by tghartland** [comment]
@cwdsuzhou @cpuguy83 Please let me know once you've got the code moved into a VK repository, I'd like to give it a try. (Or if you've got another repository I could start looking at already).

**Comment by rbitia** [comment]
Hey wanted to double check, I can create a repo for y'all called "tensile-kube." I also need one or two names, github ids, email addresses and companies to list in our project maintainer list. 
Thanks!

**Comment by cwdsuzhou** [comment]
> Hey wanted to double check, I can create a repo for y'all called "tensile-kube." I also need one or two names, github ids, email addresses and companies to list in our project maintainer list.
> Thanks!
 
Please add me.
Name, ID, email, company
Weidong Cai, cwdsuzhou, cwdsuzhou@gmail.com, Tencent



Thanks!

**Comment by rochaporto** [comment]
@rbitia we have a similar implementation internally that we've started deploying, @tghartland mentioned it above. It would be great to combine this effort with others, ping us as well if there's a common repo coming up.

**Comment by cwdsuzhou** [comment]
> > Hey wanted to double check, I can create a repo for y'all called "tensile-kube." I also need one or two names, github ids, email addresses and companies to list in our project maintainer list.
> > Thanks!
> 
> Please add me.
> Name, ID, email, company
> Weidong Cai, cwdsuzhou, [cwdsuzhou@gmail.com](mailto:cwdsuzhou@gmail.com), Tencent
> 
> Thanks!

@ritazh can you grant me `write` access to `tensile-kube`, otherwise, we can not merge/review PRs

**Comment by cwdsuzhou** [comment]
> > Hey wanted to double check, I can create a repo for y'all called "tensile-kube." I also need one or two names, github ids, email addresses and companies to list in our project maintainer list.
> > Thanks!
> 
> Please add me.
> Name, ID, email, company
> Weidong Cai, cwdsuzhou, [cwdsuzhou@gmail.com](mailto:cwdsuzhou@gmail.com), Tencent
> 
> Thanks!

@rbitia can you grant me write access to tensile-kube, otherwise, we can not merge/review PRs

**Comment by cwdsuzhou** [comment]
> @cwdsuzhou @cpuguy83 Please let me know once you've got the code moved into a VK repository, I'd like to give it a try. (Or if you've got another repository I could start looking at already).

We have moved the codes to https://github.com/virtual-kubelet/tensile-kube

**Comment by tghartland** [comment]
@cwdsuzhou thanks for letting me know, I'll give it a try.

**Comment by cpuguy83** [comment]
Closing since it seems like this is completed.
Please let me know if that is not correct.

Thank you!
