### ISSUE TITLE
Update helm chart to support 1.16

### ISSUE THREAD

**Issue by slack** [virtual-kubelet/virtual-kubelet#800]
### Environment summary

Provider (e.g. ACI, AWS Fargate): na

Version (e.g. 0.1, 0.2-beta): chart in master

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS): AKS Engine, v1.16

Install Method (e.g. Helm Chart): helm chart

### Issue Details

Kubernetes 1.16 deprecated `extensions/v1beta1` API for Deployment resource type. We are referencing that API in our chart and should test and bump to `apps/v1`

### Repo Steps

Install current helm chart on v1.16, receive error:
```
unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by dineshgovindasamy** [comment]
thanks @slack. tagging myself so i can get an update when this issue is fixed @dineshgovindasamy

**Comment by jeremyrickard** [comment]
@cpuguy83 and @rbitia I'd be happy to take a crack at updating the Helm chart if you'd like.

**Comment by rbitia** [comment]
Would love the help @jeremyrickard!

**Comment by jeremyrickard** [comment]
@rbitia is the pattern of committing the chart tgz still in place? Doesn't look like there has been a version in quite some time.

**Comment by cpuguy83** [comment]
I would really like to see the charts move elsewhere.

**Comment by cpuguy83** [comment]
I've just been worried about breaking people.
Maybe anything new can go to a new repo.

**Comment by rbitia** [comment]
I can make a virtual-kubelet/charts repo?

**Comment by cpuguy83** [comment]
Charts are deprecated since we split providers out of the repo.
Providers should, if they desire, host their own charts where it makes sense.

Thanks!
