### ISSUE TITLE
Add multicluster-scheduler as a provider

### ISSUE THREAD

**Issue by adrienjt** [virtual-kubelet/virtual-kubelet#804]
Hi, [multicluster-scheduler](https://github.com/admiraltyio/multicluster-scheduler) was recently partially redesigned as a virtual-kubelet provider. I propose adding it to the list of available providers in the website and readme. @rbitia suggested I create this issue.

**Use Cases**

Given that multicluster-scheduler works at the pod level, it can be used as a general-purpose multi-cluster scheduler. Known adopters currently use it mostly for batch jobs, to utilize the resources of multiple clusters. Other use cases, like global services, require integrations with other tools, e.g., for ingress and cross-cluster networking.

**Comment by adrienjt** [comment]
Related issues: #798 #32

**Comment by pires** [comment]
I don't see any reason why this can't be added to the list of VK providers.

**Comment by cpuguy83** [comment]
Indeed, I'd start by opening a PR to add it to the list. If for some reason you want to bring it into the VK org that's an option, but it seems like your project already has a fair bit of visibility.

We haven't really set any rules or guidelines for adding a project to the org. I'd prefer it to have a non-generic name if so, though.

**Comment by adrienjt** [comment]
Thank you @pires and @cpuguy83, I'll open a PR. I don't see a reason to bring my project into the VK org at the moment. In my PR, I'll list the provider as "Admiralty Multi-Cluster Scheduler".
