### ISSUE TITLE
[VK] add conformance testing 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#81]
add kubernetes conformance testing for VK

**Comment by rbitia** [comment]
#123 was the first step on implementing conformance testing around VK. 
https://kubernetes.io/docs/setup/node-conformance/ < Documentation from K8s for running through the conformance testing.

**Comment by rbitia** [comment]
We should also automate a compatibility matrix and give access to folks.

**Comment by pires** [comment]
There were many discussions around this and IIRC we never settled down on what this would look like as clearly the VK cannot pass most conformance tests. There were even discussions around defining tests that would assert a Node + Pod controller should cover for, eg environment variables expansion such as for Downward API but. again IIRC, we found ourselves in a deep rabbit hole.

That said, my suggestion is we drop this goal. cc @cpuguy83 @sargun @bridgetkromhout @myechuri

**Comment by cpuguy83** [comment]
I agree, this needs to be on the the provider to handle because VK core is intentionally implementing a very small set of behavior.

**Comment by cpuguy83** [comment]
Closing this since VK can't really do conformance testing since it is just a library, this is going to require a particular provider to do that conformance.
