### ISSUE TITLE
Enhance Volcano Scheduler to support Virtual Kubelet

### ISSUE THREAD

**Issue by k82cn** [virtual-kubelet/virtual-kubelet#812]
### Description

Volcano is a kubernetes native batch system for AI/BigData/HPC workload. To make it better work other cluster, it's better to make its scheduler to support virtual kubelet. And it's also an good example for the scheduler on how to integrate with virtual kubelet :)

**Comment by rbitia** [comment]
Thanks!! Does Volcano plan to become an official provider within VK?

**Comment by k82cn** [comment]
Yes, that's also ok for Volcano to do that :)

**Comment by pires** [comment]
Is there an issue in this Volcano project we can track VK integration? Otherwise, can you, please, help me understand why we have this issue here.? Thank you!

**Comment by Sharathmk99** [comment]
@pires can you share any example implementation of volcano with VK?

**Comment by cpuguy83** [comment]
I'm going to go ahead and close this issue.
There is nothing actionable here, and I have not seen anything going on here.

I think it would be best if someone does work on this integration to do so in a separate repo and if there are issues or changes required in VK a new issue can be opened here.

Thanks!
