### ISSUE TITLE
[Azure] support docker json config 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#82]
https://github.com/virtual-kubelet/virtual-kubelet/blob/6486f651664ee35fa9b71f98311e4b2eb6110631/providers/azure/aci.go#L367-L369

**Comment by rbitia** [comment]
@resouer we will add support in VK soon so the hyper provider will also need to do this

**Comment by resouer** [comment]
Got it! Let me check the details.

**Comment by evillgenius75** [comment]
#120

**Comment by robbiezhang** [comment]
Fixed in #120
