### ISSUE TITLE
Running VK Securely Outside of Cluster

### ISSUE THREAD

**Issue by clarkmcc** [virtual-kubelet/virtual-kubelet#831]
I’ve got an interesting use case where we are using VK to manage binary workloads running on client machines. We like the idea of taking advantage of the scheduler, secret management and “pod” status tracking while bootstrapping our own use case into the system.

The hang up right now is that VK authenticates with a master using a kubeconfig file, which is obviously not something we can put on a customer machine. My question is, is there a way we can do something similar to what K3s has where authentication is done via a token? Or is this use case outside of what VK is going to support? Thanks!

**Comment by cpuguy83** [comment]
VK only takes a Kubernetes client. How you get that client is up to you.
Probably most of the implementations out there using VK use a kubeconfig, though.

**Comment by cpuguy83** [comment]
VK does not deal with auth, but we could consider a helper package to set up custom k8s clients. I'm not sure what is available in client-go for this already.

**Comment by clarkmcc** [comment]
I was able to solve this problem for myself like this

```go
func NewRESTConfig(hostname, port string, ca []byte, token string) *rest.Config {
	return &rest.Config{
		Host: "https://" + net.JoinHostPort(hostname, port),
		TLSClientConfig: rest.TLSClientConfig{
			CAData:     ca,
		},
		BearerToken: token,
	}
}
```
Where the `ca` and `token` are referring to a service account.

**Comment by sureshsankaran** [comment]
On similar lines, when running vk outside of cluster, how secure is the communication from api server to vk ? Do we really need a tunnel for this type of usecase between vk and apiserver ? @cpuguy83

**Comment by pires** [comment]
Just build a kubeconfig that points to a TLS certificate signed by the same CA as used in your Kubernetes cluster. Said TLS certificate must abide to the following rules:
- `CN: system:node:<NODENAME>`
- `O: system:nodes`

Then run your provider binary with `--kubeconfig <path/to/your/kubeconfig>`.

**Comment by pires** [comment]
Just to clarify, what you're doing w/ your Go code above is exactly the same thing as kubeconfig file, just in Go. Kubernetes supports token-based authentication in the kubeconfig and it supports TLS too, and other mechanisms.
