### ISSUE TITLE
NotifyPods may not work when vk starts up

### ISSUE THREAD

**Issue by cwdsuzhou** [virtual-kubelet/virtual-kubelet#836]
---

When vk starts up, updatw pod status may failed. There is a race between we get pod from KnowPods and and to Known pods.

https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/podcontroller.go#L246
notifyPods add pods the statusQueue

https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/podcontroller.go#L267
here we add to KnownPods

https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/pod.go#L213
when pods dequeue, it may does not exist in KnownPods

I would like send a PR to fix it

### Environment summary

Provider (e.g. ACI, AWS Fargate)

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, )

**Comment by sargun** [comment]
Looks right. Thanks for spotting this. This should just be a matter of moving:

```
	// Wait for the caches to be synced *before* starting to do work.
	if ok := cache.WaitForCacheSync(ctx.Done(), pc.podsInformer.Informer().HasSynced); !ok {
		return pkgerrors.New("failed to wait for caches to sync")
	}
	log.G(ctx).Info("Pod cache in-sync")
```

above 

```
provider.NotifyPods(ctx, func(pod *corev1.Pod) {
		pc.enqueuePodStatusUpdate(ctx, podStatusQueue, pod.DeepCopy())
	})
```

**Comment by cwdsuzhou** [comment]
> Looks right. Thanks for spotting this. This should just be a matter of moving:
> 
> ```
> 	// Wait for the caches to be synced *before* starting to do work.
> 	if ok := cache.WaitForCacheSync(ctx.Done(), pc.podsInformer.Informer().HasSynced); !ok {
> 		return pkgerrors.New("failed to wait for caches to sync")
> 	}
> 	log.G(ctx).Info("Pod cache in-sync")
> ```
> 
> above
> 
> ```
> provider.NotifyPods(ctx, func(pod *corev1.Pod) {
> 		pc.enqueuePodStatusUpdate(ctx, podStatusQueue, pod.DeepCopy())
> 	})
> ```

Yes, I think so

**Comment by sargun** [comment]
Let me know when you submit a PR.
