### ISSUE TITLE
kubectl create pod with multiple containers

### ISSUE THREAD

**Issue by nonokangwei** [virtual-kubelet/virtual-kubelet#86]
---

### Environment summary

Provider (e.g. Azure, Hyper)
azure
Version (e.g. 0.1, 0.2-beta)
latest version
K8s Master Info (e.g. AKS, ACS, Bare Metal)
AKS
Install Method (e.g. Helm Chart, )
Helm
### Issue Details
create pod with 2 containers, the second one keep restart

acidemo                                               1/2       Waiting   6          9m

### Repo Steps
pod yaml
apiVersion: v1
kind: Pod
metadata:
  name: acidemo
spec:

  containers:

  - name: nginx-container
    image: nginx
    resources:
      requests:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https

  - name: debian-container
    image: debian
    resources:
      requests:
        memory: 1G
        cpu: 1
  nodeName: virtual-kubelet-aciconnector-linux
  dnsPolicy: ClusterFirst
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule

**Comment by robbiezhang** [comment]
The 2nd container (debian) doesn't have an override command, so it will exit after start. Since you didn't specify the RestartPolicy, it uses the default value "Always", and restart any exited container. That's why it keeps restart.

**Comment by nonokangwei** [comment]
thanks, Robbie, double check the debian image it has problem. 
close this thread.
