### ISSUE TITLE
[Azure] Concatenate command and args for ACI

### ISSUE THREAD

**Issue by nonokangwei** [virtual-kubelet/virtual-kubelet#87]
---

### Environment summary

Provider (e.g. Azure, Hyper)
Azure
Version (e.g. 0.1, 0.2-beta)
latest
K8s Master Info (e.g. AKS, ACS, Bare Metal)
AKS
Install Method (e.g. Helm Chart, )
Helm
### Issue Details
create pod by using pod yaml file include command & args parameters, the pod not create successfully
### Repo Steps
apiVersion: v1
kind: Pod
metadata:
  name: debiandemo
spec:

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  - name: debian-container
    image: debian
    resources:
      requests:
        memory: 1G
        cpu: 1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-aciconnector-linux
  dnsPolicy: ClusterFirst
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule

**Comment by robbiezhang** [comment]
Thanks for reporting! This is a bug in ACI provider: ACI doesn't support args. The ACI provider doesn't concatenate command and args and send it to the ACI.

@nonokangwei, the workaround is to concatenate the command and args into the command property:

>     command: ["/bin/sh", "-c", "while true; do echo hello; sleep 10;done"]

**Comment by yolo3301** [comment]
@robbiezhang We can concatenate command + args when converting from pod to container group. But how to know if a user specified args when converting container group back to pod?

**Comment by nonokangwei** [comment]
Thanks @robbiezhang , also it seems if the pod yaml has args parameters, which will trigger the virtual-kubelet pod restart.
wei@Azure:~$ kubectl get pod
NAME                                                  READY     STATUS    RESTARTS   AGE
aciconnector-linux-virtual-kubelet-7d6bb5f576-749pl   1/1       Running   57         1d

**Comment by yolo3301** [comment]
@nonokangwei I don't think that's related. Because of this bug, the command + args is missing args, so the container will complete instantly. Because the restart policy is always, it automatically restarts. After the fix, this shouldn't happen.

**Comment by robbiezhang** [comment]
the fix is in 0.2-beta-7 or above
