### ISSUE TITLE
Handle case where node is deleted

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#886]
Right now, if the node is deleted, and recreated, it completely breaks leases. I think that we should aggressively deprecate our current lease approach, and move towards the more traditional model proposed in: https://github.com/virtual-kubelet/virtual-kubelet/pull/880

Opinions?
CC: @cpuguy83

**Comment by cpuguy83** [comment]
Leases are merged. Can we close this one?
