### ISSUE TITLE
Is there a provider that supports Podman?

### ISSUE THREAD

**Issue by Poor12** [virtual-kubelet/virtual-kubelet#888]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, )

### Issue Details
Does VK support some container runtime like katacontainer or podman?

**Comment by cpuguy83** [comment]
None that I know of. There was a generic CRI provider that was very incomplete.
I looked at enhancing it (the CRI provider) but CRI is really not great for this and might as well use kubelet if going with a CRI implementation.

**Comment by danopia** [comment]
This is an existing incomplete effort I know of using podman's varlink API: https://github.com/virtual-kubelet/podman though I'm not sure what about it makes it CRI tied so maybe that's another codebase.

I've been working on a rather opinionated VK effort using podman's REST API @ https://github.com/danopia/kube-pet-node & it will never be feature complete with Kubernetes, there's too many podspec fields to map. At this point it's basically masochism that I'm still putting effort into making a shittier kubelet :)

**Comment by pires** [comment]
Maybe @henryprecheur knows more?

**Comment by henryprecheur** [comment]
At Elotl we are working on adding support to Podman in Kip.

The work is still in the initial stage. I think we are about 50% there, but we have a project with higher priority right now. I can’t give you an ETA of when Kip will support fully the Podman runtime.

**Comment by helayoty** [comment]
@henryprecheur, Any plan to get this done? Otherwise, I think we can close this issue as not planned.

**Comment by henryprecheur** [comment]
Yes, we aren't any closer to implement Podman for Kip. It looks very unlikely to happen at this point.

You can close this.

**Comment by helayoty** [comment]
@henryprecheur  Going to archive the repository as well. https://github.com/virtual-kubelet/podman
