### ISSUE TITLE
Update Helm chart artifacts of `virtual-kubelet-for-aks` to ensure compatibility with k8s version 1.16+

### ISSUE THREAD

**Issue by subodh-dharma** [virtual-kubelet/virtual-kubelet#889]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
Azure AKS

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
1.16+ AKS

Install Method (e.g. Helm Chart, )
Helm Chart

### Issue Details

* Helm chart for virtual-kubelet-for-aks needs to be updated to make Deployment compatible with `apiVersion: apps` instead of `apiVersion: extensions/v1beta1.`

* Add `spec.selector` field in Deployment spec, since it is a mandatory field in apps/v1/Deployment

### Repo Steps

Using Helm 3.0+ install helm chart located at https://github.com/virtual-kubelet/virtual-kubelet/tree/b91d892bffd3de16089cdb82f4aaae8c7d17df80/charts/virtual-kubelet-for-aks. When installing it results with following error.

```bash
no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by cpuguy83** [comment]
These charts are in https://github.com/virtual-kubelet/azure-aci
Does this work for you?

We don't intend to update the helm charts in this repo.

**Comment by subodh-dharma** [comment]
So the `virtual-kubelet-for-aks` chart is equivalent to `virtual-kubelet-aci-for-aks.tgz` or `virtual-kubelet-latest.tgz` ?

**Comment by cpuguy83** [comment]
Yes, they should be.

**Comment by subodh-dharma** [comment]
Leaving here if anyone stumbles on this:

Updated charts can be found here: https://github.com/virtual-kubelet/azure-aci/tree/master/charts
