### ISSUE TITLE
[VK & Azure] add DNS name support 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#90]
Add DNS name support to Vk and connect the ACI api to it. Use an annotation within ACI pod specs to create a DNS name but we will not resolve conflict if used within a kubernetes deployment for ACI through the connector. 

---

### Environment summary

Provider (e.g. Azure, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal)

Install Method (e.g. Helm Chart, )

**Comment by bnookala** [comment]
@rbitia I'd like to take an attempt at this, if it's unassigned!

**Comment by rbitia** [comment]
#97

**Comment by rbitia** [comment]
merged so closing
