### ISSUE TITLE
Race issue between k8s and provider when deleting pod

### ISSUE THREAD

**Issue by cwdsuzhou** [virtual-kubelet/virtual-kubelet#907]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)

k8s

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, )

### Issue Details
1. Create Pod
2. Delete pod and re-create the pod in k8s. 
3. pod re-created may be deleted again by provider

https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/pod.go#L384

**Comment by sargun** [comment]
Someone already filed this bug: https://github.com/virtual-kubelet/virtual-kubelet/issues/867

**Comment by pires** [comment]
Closing as duplicate.
