### ISSUE TITLE
Process of getting a repo under virtual-kubelet?

### ISSUE THREAD

**Issue by miekg** [virtual-kubelet/virtual-kubelet#920]
Hello, 

I'm working on a virtual kublelet that works with systemd: https://github.com/miekg/vks (Jury is still out if this is a good or bad idea), but I'm wondering what the process is to get this under the virtual-kubelet org?

Thanks!

**Comment by sargun** [comment]
This is cool!

I think @cpuguy83 might be able to help?

**Comment by miekg** [comment]
note we are renaming vks to systemk

**Comment by pires** [comment]
I totally support this!

**Comment by cpuguy83** [comment]
Created a `systemk` repo and invited you @miekg

**Comment by miekg** [comment]
Saw it. Thanks! 👍

**Comment by miekg** [comment]
what's the minimum permission you can hand out to allow me to invite collaborators? I fear this may require setting a new team or something in the org?

**Comment by cpuguy83** [comment]
@miekg You should have privileges for this on the repo.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/virtual-kubele..." ]
>@miekg You should have privileges for this on the repo.

hmmm, shouldn't I have a 'setting' item in the menu? I don't have that.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
for this to work I need a 'settings' menu, which I def. don't have. I think Github makes you jump through hoops to make this work  (create a team -> and then some).
 
![systemk](https://user-images.githubusercontent.com/353371/101366407-37b06b00-38a5-11eb-9d4e-4c3d7dce484b.png)
![vks](https://user-images.githubusercontent.com/353371/101366410-38490180-38a5-11eb-9fd3-91323537d493.png)


I don't mind per se, but I would like to invite: 
@pathcl
@pires
@Sh4d1
which mean you need to push buttons :)

**Comment by miekg** [comment]
settings is there. Thanks! I'm moving the code into this org.

**Comment by cpuguy83** [comment]
Ah, sorry for the delay. Glad this worked.
