### ISSUE TITLE
[VK] time for AGE goes backwards 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#93]
---

### Environment summary

Provider (e.g. Azure, Hyper)
Azure
Version (e.g. 0.1, 0.2-beta)
latest
K8s Master Info (e.g. AKS, ACS, Bare Metal)
AKS
Install Method (e.g. Helm Chart, )
helm
### Issue Details

My ACI pods go "back in time" the seconds seem to be off.... 

Rias-MBP:aci-demos riabhatia$ kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
demo-fr-backend-3527464242-zr7s9                     1/1       Running   0          53s
demo-fr-frontend-851762788-rl5gq                     1/1       Running   1          53s
demo-fr-ir-3868126132-rm50j                          1/1       Running   0          52s
demo-fr-ir-aci-944532873-9fkr7                       0/1       Pending   0          7s
demo-fr-ir-aci-944532873-j4d3p                       0/1       Pending   0          2s
demo-fr-ir-aci-944532873-lbgdt                       0/1       Pending   0          5s
myconnector-linux-virtual-kubelet-1357898810-zxdf2   1/1       Running   28         20h
Rias-MBP:aci-demos riabhatia$ kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
demo-fr-backend-3527464242-zr7s9                     1/1       Running   0          1m
demo-fr-frontend-851762788-rl5gq                     1/1       Running   1          1m
demo-fr-ir-3868126132-rm50j                          1/1       Running   0          59s
demo-fr-ir-aci-944532873-gjqrd                       0/1       Pending   0          2s
demo-fr-ir-aci-944532873-j4d3p                       0/1       Pending   0          9s
demo-fr-ir-aci-944532873-td9js                       0/1       Pending   0          6s
myconnector-linux-virtual-kubelet-1357898810-zxdf2   1/1       Running   28         20h
### Repo Steps
Deploy multiple aci pods in a deployment and continue to kubectl get po and see your pods go back in time

**Comment by bnookala** [comment]
@rbitia just speculating from your console output - it looks like `demo-fr-ir-aci-944532873-lbgdt` and `demo-fr-ir-aci-944532873-gjqrd` are new pods, possibly accounting for the "going back in time" issue you noticed. is it possible that `demo-fr-ir-aci-944532873-lbgdt` and `demo-fr-ir-aci-944532873-9fkr7` encountered an error and were restarted?

**Comment by robbiezhang** [comment]
They are different pods, their name are different. Guess these pods are auto re-created by the deployment, because they are not "Running" in time. Please check
1. Whether they are assigned to the virutal-kubelet node by running `kubectl get po -o wide`
2. Check the virtual kubelet pod log to see why the old pods are not created.
