### ISSUE TITLE
Import of k8s.io/kubernetes breaks Bazel

### ISSUE THREAD

**Issue by miekg** [virtual-kubelet/virtual-kubelet#940]
It's impossible (*) to build VK (and systemk) w/ Bazel because the entirety of kubernetes is a dependency.
It seems to be because of this one file https://github.com/virtual-kubelet/virtual-kubelet/blob/master/internal/podutils/env.go

VK probably needs more stuff than the usual k8s client, but I think it worth copy and pasting a few bits and depending on *all* of kubernetes just to get a thing. Yes, I realize 'go build' works.

(*): day of trying

**Comment by miekg** [comment]
in env.go only 3 functions are used, but there are more files:
~~~
test/e2e/basic.go:	"k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
cmd/virtual-kubelet/main.go:	k8sVersion   = "v1.15.2" // This should follow the version of k8s.io/kubernetes we are importing
cmd/virtual-kubelet/internal/provider/mock/mock.go:	stats "k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
cmd/virtual-kubelet/internal/provider/provider.go:	stats "k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
node/api/exec.go:	api "k8s.io/kubernetes/pkg/apis/core"
node/api/exec.go:	"k8s.io/kubernetes/pkg/kubelet/server/remotecommand"
node/api/stats.go:	stats "k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
internal/podutils/env.go:	podshelper "k8s.io/kubernetes/pkg/apis/core/pods"
internal/podutils/env.go:	v1helper "k8s.io/kubernetes/pkg/apis/core/v1/helper"
internal/podutils/env.go:	fieldpath "k8s.io/kubernetes/pkg/fieldpath"
internal/podutils/env.go:	"k8s.io/kubernetes/pkg/kubelet/envvars"
internal/podutils/env.go:	"k8s.io/kubernetes/third_party/forked/golang/expansion"
internal/test/e2e/framework/stats.go:	stats "k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
internal/test/e2e/framework/pod.go:	podutil "k8s.io/kubernetes/pkg/api/v1/pod"
~~~

**Comment by cpuguy83** [comment]
Yes, api/exec has definitely been on a todo to fix.
But as you say, it's really problematic... a lot to fork.

**Comment by miekg** [comment]
I can't find v1alpha1.Summary anymore in the k8s repo, seems moved/gone. Found these issues: https://github.com/elastic/beats/issues/12792 and https://github.com/kubernetes/kubernetes/issues/68522

**Comment by cpuguy83** [comment]
We are no longer importing k8s.io/kubernetes on master.
Looking to cut a release soon.

**Comment by Kent-H** [comment]
What is the ETA on this release?

I would very much like to pull this change into our project; but I would prefer a release version if possible.

**Comment by cpuguy83** [comment]
I've been seeing some deadlocks when running tests and have not had enough time to hunt down the issue.
It is likely related to the queue changes but I'm not sure.

I also want to get https://github.com/virtual-kubelet/virtual-kubelet/pull/975 into the release, or revert the ControllerManager all-together before the release.

**Comment by helayoty** [comment]
@cpuguy83  Can we close this issue now?

**Comment by cpuguy83** [comment]
Yep
