### ISSUE TITLE
`stats.Summary` doesn't exists anymore in upstream kubernetes

### ISSUE THREAD

**Issue by miekg** [virtual-kubelet/virtual-kubelet#946]
This is a follow up from #940

In `node.go`: 
~~~
node/api/stats.go:type PodStatsSummaryHandlerFunc func(context.Context) (*stats.Summary, error)
~~~
`stats.Summary` is used, this pulls in kubernetes/kubernetes. While looking into copying a few files from k8s into VK it seems `stats.Summary` doesn't exist anymore - I'm unclear what the new shiny is though.

I'm inclined to remove this. Is that the best way forward?
Also happy to be pointed to the new shiny and seeing how we can incorporate that.

Is this used btw?

**Comment by cpuguy83** [comment]
Ugh, I wish I forked this...

That said I still see it on master: https://github.com/kubernetes/kubernetes/blob/bb6d0e7175e556c7f040678de4719553137f7ae6/staging/src/k8s.io/kubelet/pkg/apis/stats/v1alpha1/types.go#L24-L29

**Comment by cpuguy83** [comment]
I see there's a new set of endpoints.

**Comment by miekg** [comment]
In 'staging'. OK. Do we care that after a code import that type is different?

**Comment by cpuguy83** [comment]
I'm not sure I ever understood the staging namespace for k8s.
It would be best to not have a change here if we can avoid it, but kinda seems SOL in that regard.

Any thoughts here @pires

**Comment by pires** [comment]
`staging` is just a folder and carries no version stability version whatsoever.

The kubelet API has been getting some love and that's why we're seeing those APIs mutating. However... https://github.com/kubernetes/kubernetes/pull/92985

```
This PR moves Kubelet stats summary to kubelet staging directory, making it easy importable via "k8s.io/kubelet".
Without this PR projects that want to consume this API need to import "k8s.io/kubernetes" which is doesn't work with golang modules.
```

Guess it's just a matter of importing new paths.

**Comment by miekg** [comment]
Ok. So this only means changing the import paths. That would be good!

That only leaves exec.go and the tests (care less about those, because when
not exercised Bazel should not care)

**Comment by pires** [comment]
Pinging for approval since I mentioned it today as well during community meeting.

**Comment by sargun** [comment]
I think it's fine. I don't think it puts us in any worse of a situation we are in today.

**Comment by cpuguy83** [comment]
What we can do for the purposes of supporting older k8s is copy the stats structs internally for now.
We can use a type alias to prevent further breaking when we are ready to make the hard cut to >= k8s 1.20.
e.g. `type stats.Summary = internalstats.Summary` for now, then we can update that use stats from `k8s.io/kubelet` later.

Thoughts?

**Comment by pires** [comment]
Sure, why not?
