### ISSUE TITLE
Creation of a new provider

### ISSUE THREAD

**Issue by ansjin** [virtual-kubelet/virtual-kubelet#993]
---

### Environment summary

New Provider

### Issue Details

Hello, 

I have created a new provider, and currently I am using it in place of the [mock](https://github.com/virtual-kubelet/virtual-kubelet/tree/master/cmd/virtual-kubelet/internal/provider) provider within virtual-kubelet repository. 
I am testing it using `make skaffold` and is part of local virtual-kubelet repository. 

However, I want to separate it out from virtual-kubelet repository and create a separate repo of my provider, like all other providers have. Could you please tell me or point me towards some documentation which I need to follow to separate it out of  virtual-kubelet repository, like all other providers? I could not find any documentation related to it.

**Comment by cheimu** [comment]
Use this repo: https://github.com/virtual-kubelet/node-cli

**Comment by cpuguy83** [comment]
The godoc should give you what you need here.
I would recommend to look in at https://godoc.org/github.com/virtual-kubelet/virtual-kubelet/node/nodeutil which provides a nice higher-level integration point.

https://github.com/virtual-kubelet/node-cli is also available to get something up quickly.
