### ISSUE TITLE
Update Kubernetes client-go

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#997]
We are way behind on client-go

**Comment by yabuchan** [comment]
Hi @cpuguy83, not only client-go but also k8s.io/api, k8s.io/apimachinery, and k8s.io/apiserver are also outdated. 
May I send PR for this?

**Comment by skaegi** [comment]
I believe this should be closed now after https://github.com/virtual-kubelet/virtual-kubelet/pull/1042
